package flow;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2017年8月31日 下午04時21分20秒
 */
public class Generate_TID extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2017年8月31日 下午04時21分20秒
	 */
	public Generate_TID() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2024年11月6日 下午04時05分46秒
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("CF_check_mobile", "Default");
		next.setDebugId(675);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2024年11月6日 下午04時05分46秒
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2024年11月6日 下午04時05分46秒
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(10);
		actions.add(new com.avaya.sce.runtime.varoperations.Assign("S_TID:TID", "date:audio", false).setDebugId(676));
		actions.add(new com.avaya.sce.runtime.varoperations.Concatenate("S_TID:TID", "time:audio", false).setDebugId(677));
		actions.add(new com.avaya.sce.runtime.varoperations.SubString("S_TID:CHANNEL", "properties:Channel", 1, 1).setDebugId(831));
		actions.add(new com.avaya.sce.runtime.varoperations.Concatenate("S_TID:TID", "S_TID:CHANNEL", false).setDebugId(832));
		actions.add(new com.avaya.sce.runtime.varoperations.Concatenate("S_TID:TID", "cticallinfo:stationextension", false).setDebugId(678));
		actions.add(new com.avaya.sce.runtime.tracking.TraceInfo(com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_DEBUG, "### GenerateTID_S_TID_Channel", "S_TID:CHANNEL").setDebugId(834));
		actions.add(new com.avaya.sce.runtime.tracking.TraceInfo(com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_INFO, "### GenerateTID_S_TID", "S_TID:TID").setDebugId(679));
		actions.add(new com.avaya.sce.runtime.varoperations.Assign("getCashSubscriberInfoByKey_Input:msisdn", "S_USERDATA:ANI", false).setDebugId(1636));
		actions.add(new com.avaya.sce.runtime.varoperations.Assign("getCashSubscriberInfoByKey_Input:transBpId", "S_USERDATA:BPID", false).setDebugId(1637));
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
}
