package flow;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2017年10月26日 下午06時24分32秒
 */
public class get_CIEID_again extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2017年10月26日 下午06時24分32秒
	 */
	public get_CIEID_again() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2024年11月6日 下午03時00分33秒
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = null;
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2024年11月6日 下午03時00分33秒
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2024年11月6日 下午03時00分33秒
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(2);
		com.avaya.sce.runtime.BooleanOperation bo1 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.AND);
		com.avaya.sce.runtime.Expression be1 = new com.avaya.sce.runtime.Expression("expression1", "FE_PARM_TBL:FE_PARM_VALUE", com.avaya.sce.runtime.Expression.STRING_EQUAL, "Y", false);
		bo1.addExpression(be1);
		com.avaya.sce.runtime.Expression be2 = new com.avaya.sce.runtime.Expression("expression2", "S_USERDATA:BPID", com.avaya.sce.runtime.Expression.NOT_EMPTY);
		bo1.addExpression(be2);
		actions.add(new com.avaya.sce.runtime.varoperations.Assign("CH_FE_PARM_TBL:FE_PARM_PARM", "NCP_Enable", true).setDebugId(1012));
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;
		try {
			actions = new java.util.ArrayList(1);

			//{{START:CODEGEN:EXTENSIONPOINT:com.avaya.sce.databaseoperations
			actions.add(new connectivity.db.operations.FE_PARM_TBL(mySession).setDebugId(1014));
			//}}END:CODEGEN:EXTENSIONPOINT:com.avaya.sce.databaseoperations

			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;
		} catch (Exception e1) {
			actions = new java.util.ArrayList(1);
			actions.add(new com.avaya.sce.runtime.varoperations.CaptureException(e1).setDebugId(-1));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;
		}

		actions = new java.util.ArrayList(1);
		actions.add(new com.avaya.sce.runtime.tracking.TraceInfo(com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_INFO, "### Parm_Value2", "FE_PARM_TBL:FE_PARM_VALUE").setDebugId(1016));
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(1017)).evaluate(mySession, bo1)) {
			actions = new java.util.ArrayList(20);
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("CIE_CreateService_Input:BpId", "S_USERDATA:BPID", false).setDebugId(1021));
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("CIE_CreateService_Input:cie_createDate", "date:audio", false).setDebugId(1022));
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("CIE_CreateService_Input:cie_endDate", "date:audio", false).setDebugId(1023));
			actions.add(new com.avaya.sce.runtime.varoperations.Concatenate("CIE_CreateService_Input:cie_endDate", "time:audio", false).setDebugId(1024));
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("CIE_CreateService_Input:cie_InOutbound", "I", true).setDebugId(1025));
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("CIE_CreateService_Input:cie_isNonFET", "N", true).setDebugId(1026));
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("CIE_CreateService_Input:cie_startDate", "date:audio", false).setDebugId(1027));
			actions.add(new com.avaya.sce.runtime.varoperations.Concatenate("CIE_CreateService_Input:cie_startDate", "time:audio", false).setDebugId(1028));
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("CIE_CreateService_Input:FlowName", "380kid", true).setDebugId(1029));
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("CIE_CreateService_Input:msisdnNumber", "S_USERDATA:ANI", false).setDebugId(1030));
			actions.add(new com.avaya.sce.runtime.tracking.TraceInfo(com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_INFO, "### CreateService_msisdn2", "CIE_CreateService_Input:msisdnNumber").setDebugId(1031));
			actions.add(new com.avaya.sce.runtime.tracking.TraceInfo(com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_INFO, "### sessionId2", "session:sessionid").setDebugId(1032));
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("CIE_CreateService_Input:sessionId", "session:sessionid", false).setDebugId(1033));
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("CIE_CreateService_Input:subscriber", "getCashSubscriberInfoByKey_Output:subscriberId", false).setDebugId(1034));
			actions.add(new com.avaya.sce.runtime.tracking.TraceInfo(com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_INFO, "### CreateService_Subscriber2", "CIE_CreateService_Input:subscriber").setDebugId(1035));
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("CIE_CreateService_Input:transPath", "IVR-380", true).setDebugId(1036));
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("CH_CIE:CIE_Create_error", "CIE_Create_error", true).setDebugId(1037));
			actions.add(new com.avaya.sce.runtime.tracking.TraceInfo(com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_INFO, "#####CIE:CIE_Create_error_Before2", "CH_CIE:CIE_Create_error").setDebugId(1038));
			actions.add(new com.avaya.sce.runtime.Next("API_addCIE", "get CID").setDebugId(1050));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		} else {
			actions = new java.util.ArrayList(1);
			actions.add(new com.avaya.sce.runtime.Next("insert_CIE_Record_log2", "no CID").setDebugId(1052));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;
		}


		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
}
