package flow;

/**
 * This is a special reserved class that is repsonsible for loading application 
 * variables as well as the forward to the actual first form of the application.<br>
 * This class should not be manually edited as changes may be overridden by the 
 * code generator.<br>
 * Last generated by Orchestration Designer at: 2017年8月18日 下午02時33分30秒
 */
public class Start extends com.avaya.sce.runtime.Entry {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2017年8月18日 下午02時33分30秒
	 */
	public Start() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method is generated automatically.  Any changes may be overwritten.
	 * Returns the submit object that will redirect application flow to the first
	 * form in the application.  This also adds various standard variables to the
	 * list of data to be submitted to the runtime variable table.
	 * Last generated by Orchestration Designer at: 2024年11月15日 下午02時18分45秒
	 * @return the Submit object that contains the standard variables and the first form
	 */
	public com.avaya.sce.runtime.Submit getSubmit(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Submit submit = new com.avaya.sce.runtime.Submit("get_properties");
		return ( submit );
	}
	/**
	 * This method initializes the SCE session with the variables that
	 * are defined in the application.<BR>
	 * 
	 * This method is generated automatically and should not be manually
	 * edited because changes may be overwritten by future code 
	 * generation.
	 * Last generated by Orchestration Designer at: 2024年11月15日 下午02時18分45秒
	 */
	public void initializeVariables(com.avaya.sce.runtimecommon.SCESession session) {
		com.avaya.sce.runtimecommon.IVariable variable = null;
		String[] variableFields = null;

		variableFields = new String[] {
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_TEST_FIELD_BIRTH_DATE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_TEST_FIELD_EXCEPTION,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_TEST_FIELD_IDENTIFICATION_NUMBER,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_TEST_FIELD_LEGACY_CODE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_TEST_FIELD_PASSWORD,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_TEST_FIELD_PROCESS_ID,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_TEST_FIELD_PROCESS_NAME,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_TEST_FIELD_RETURN_CODE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_TEST_FIELD_RETURN_MESG,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_TEST_FIELD_SUBSCEIBER_ID };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_TEST, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.FLOW_NAME_FIELD_DONATION_TO_CHILD_WELFARE_LEAGUE,
			IProjectVariables.FLOW_NAME_FIELD_DONATION_TO_CHINESE_CHRISTIAN_RELIEF_ASSOCIATION,
			IProjectVariables.FLOW_NAME_FIELD_DONATION_TO_HOME_SUPPORT,
			IProjectVariables.FLOW_NAME_FIELD_DONATION_TO_PAPER_WINDMILL_TROUPE,
			IProjectVariables.FLOW_NAME_FIELD_DONATION_TO_RED_CROSS_BY_PHONE,
			IProjectVariables.FLOW_NAME_FIELD_DONATION_TO_TEACHER_CHANG,
			IProjectVariables.FLOW_NAME_FIELD_FAR_EAST_ONE_SMALL_AMOUNT,
			IProjectVariables.FLOW_NAME_FIELD_JOINTFUNDRAISING };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.FLOW_NAME, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CH__USERDATA_FIELD_ACTIVE__DATE,
			IProjectVariables.CH__USERDATA_FIELD_ANI,
			IProjectVariables.CH__USERDATA_FIELD_BIRTHDAY,
			IProjectVariables.CH__USERDATA_FIELD_BPID,
			IProjectVariables.CH__USERDATA_FIELD_BUSINESS_ENTITY_NUMBER,
			IProjectVariables.CH__USERDATA_FIELD_CITIZENSHIPTYPE,
			IProjectVariables.CH__USERDATA_FIELD_CONTACT__LANGUAGE,
			IProjectVariables.CH__USERDATA_FIELD_FLC__OFFER__ID,
			IProjectVariables.CH__USERDATA_FIELD_ID__TYPE,
			IProjectVariables.CH__USERDATA_FIELD_IDENTIFIER,
			IProjectVariables.CH__USERDATA_FIELD_LANGUAGE,
			IProjectVariables.CH__USERDATA_FIELD_OUT__VDN,
			IProjectVariables.CH__USERDATA_FIELD_PAYMENT_CATEGORY,
			IProjectVariables.CH__USERDATA_FIELD_PHONE__LENGTH,
			IProjectVariables.CH__USERDATA_FIELD_PHONE_NUMBER,
			IProjectVariables.CH__USERDATA_FIELD_SERV__NBR,
			IProjectVariables.CH__USERDATA_FIELD_SUB__TYPE,
			IProjectVariables.CH__USERDATA_FIELD_SUBSCRIBER__NO,
			IProjectVariables.CH__USERDATA_FIELD_TO_AGENT__MENU_LOG,
			IProjectVariables.CH__USERDATA_FIELD_UUI };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CH__USERDATA, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.IVR___5_9_1_9__DONATE__TRAN_FIELD_ACCOUNT__ID,
			IProjectVariables.IVR___5_9_1_9__DONATE__TRAN_FIELD_ADDRESS,
			IProjectVariables.IVR___5_9_1_9__DONATE__TRAN_FIELD_BUSINESS__ENTITY,
			IProjectVariables.IVR___5_9_1_9__DONATE__TRAN_FIELD_COUNT,
			IProjectVariables.IVR___5_9_1_9__DONATE__TRAN_FIELD_CYCLY__DATE,
			IProjectVariables.IVR___5_9_1_9__DONATE__TRAN_FIELD_DONATE__AMT,
			IProjectVariables.IVR___5_9_1_9__DONATE__TRAN_FIELD_DONATE__CD,
			IProjectVariables.IVR___5_9_1_9__DONATE__TRAN_FIELD_DONATE__DATE,
			IProjectVariables.IVR___5_9_1_9__DONATE__TRAN_FIELD_DONATE__TIME,
			IProjectVariables.IVR___5_9_1_9__DONATE__TRAN_FIELD_MSISDN,
			IProjectVariables.IVR___5_9_1_9__DONATE__TRAN_FIELD_NAME };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.IVR___5_9_1_9__DONATE__TRAN, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.FE__PARM__TBL_FIELD_FE__PARM__PARM,
			IProjectVariables.FE__PARM__TBL_FIELD_FE__PARM__VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.FE__PARM__TBL, variableFields, null, session, false, false );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.EVENT__MESSAGE, "", null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.IVR__OPERATION__CTRL__INPUT_FIELD_CTRL__FINISH__DATE,
			IProjectVariables.IVR__OPERATION__CTRL__INPUT_FIELD_CTRL__FINISH__TIME,
			IProjectVariables.IVR__OPERATION__CTRL__INPUT_FIELD_CTRL__MODIFY__DATE,
			IProjectVariables.IVR__OPERATION__CTRL__INPUT_FIELD_CTRL__START__DATE,
			IProjectVariables.IVR__OPERATION__CTRL__INPUT_FIELD_CTRL__START__TIME,
			IProjectVariables.IVR__OPERATION__CTRL__INPUT_FIELD_OPERATION__CTRL__FLAG,
			IProjectVariables.IVR__OPERATION__CTRL__INPUT_FIELD_OPERATION__CTRL__NAME,
			IProjectVariables.IVR__OPERATION__CTRL__INPUT_FIELD_OPERATION__CTRL__NO,
			IProjectVariables.IVR__OPERATION__CTRL__INPUT_FIELD_OPERATION__CTRL__TYPE,
			IProjectVariables.IVR__OPERATION__CTRL__INPUT_FIELD_VOCAL__NUM };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.IVR__OPERATION__CTRL__INPUT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CREATE_TXN__INPUT_FIELD_BILL_SUBSCR_ID,
			IProjectVariables.CREATE_TXN__INPUT_FIELD_CHANGE_ITEM_CDTYPE,
			IProjectVariables.CREATE_TXN__INPUT_FIELD_CHANNEL_FOR_CFG,
			IProjectVariables.CREATE_TXN__INPUT_FIELD_COH_GROUP_ORDER_ID,
			IProjectVariables.CREATE_TXN__INPUT_FIELD_CREATE_AGENT_CD,
			IProjectVariables.CREATE_TXN__INPUT_FIELD_CREATE_CHANNEL,
			IProjectVariables.CREATE_TXN__INPUT_FIELD_CREATE_SYSTEM,
			IProjectVariables.CREATE_TXN__INPUT_FIELD_FLOW_NAME,
			IProjectVariables.CREATE_TXN__INPUT_FIELD_IDENTIFIER_NUM,
			IProjectVariables.CREATE_TXN__INPUT_FIELD_MOBILE_GENERATION_CODEL,
			IProjectVariables.CREATE_TXN__INPUT_FIELD_MSISDN,
			IProjectVariables.CREATE_TXN__INPUT_FIELD_PAYMENT_CATEGORY,
			IProjectVariables.CREATE_TXN__INPUT_FIELD_POTENTIAL_CONT_IND,
			IProjectVariables.CREATE_TXN__INPUT_FIELD_SERVICE_PROVIDER,
			IProjectVariables.CREATE_TXN__INPUT_FIELD_TEMPORAL_TPCDTYPE,
			IProjectVariables.CREATE_TXN__INPUT_FIELD_TRANS_BP_ID,
			IProjectVariables.CREATE_TXN__INPUT_FIELD_TXN_COMPLETE_DT,
			IProjectVariables.CREATE_TXN__INPUT_FIELD_TXN_STATUS_CD,
			IProjectVariables.CREATE_TXN__INPUT_FIELD_TXN_TP_CD,
			IProjectVariables.CREATE_TXN__INPUT_FIELD_UPDATE_AGENT_CD };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CREATE_TXN__INPUT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.TO_AGENT_FIELD_ANI,
			IProjectVariables.TO_AGENT_FIELD_CALLID,
			IProjectVariables.TO_AGENT_FIELD_DNIS,
			IProjectVariables.TO_AGENT_FIELD_STATE,
			IProjectVariables.TO_AGENT_FIELD_STATIONEXTENSION,
			IProjectVariables.TO_AGENT_FIELD_UCID,
			IProjectVariables.TO_AGENT_FIELD_UUI };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.TO_AGENT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_ERRORCODE,
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_MESSAGE,
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_OBJECT,
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_STACKTRACE,
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_TYPE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DD_LAST_EXCEPTION, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DOMAINID_FIELD_ID };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DOMAINID, variableFields, "com.avaya.vp.admin.variables.runtime.AdminVariableFactory", session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.QUERY_VOUCHER_CARD_SERVICE__OUTPUT_FIELD_PIN_CODE,
			IProjectVariables.QUERY_VOUCHER_CARD_SERVICE__OUTPUT_FIELD_RETURNCODE,
			IProjectVariables.QUERY_VOUCHER_CARD_SERVICE__OUTPUT_FIELD_SEQ_NO,
			IProjectVariables.QUERY_VOUCHER_CARD_SERVICE__OUTPUT_FIELD_STATUS,
			IProjectVariables.QUERY_VOUCHER_CARD_SERVICE__OUTPUT_FIELD_VOUCHER_NUMBER };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.QUERY_VOUCHER_CARD_SERVICE__OUTPUT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.S__OD_FIELD_AN___9_9_0_8_1_0__INPUT__ERROR__COUNT,
			IProjectVariables.S__OD_FIELD_AN___9_9_0_9_1_0__COUNT,
			IProjectVariables.S__OD_FIELD_AN___9_9_0_9_1_0__LENGTH,
			IProjectVariables.S__OD_FIELD_AN___9_9_0_9_1_1__COUNT,
			IProjectVariables.S__OD_FIELD_AN___9_9_1_2_6_7__LENGHT,
			IProjectVariables.S__OD_FIELD_AN___9_9_1_2_7_7__INPUT__LENGHT,
			IProjectVariables.S__OD_FIELD_AN___9_9_1_5_6_6__INPUT__ERROR__COUNT,
			IProjectVariables.S__OD_FIELD_AN___9_9_1_5_6_7__INPUT__ERROR__COUNT,
			IProjectVariables.S__OD_FIELD_AN___9_9_2_0_0_0__COUNT,
			IProjectVariables.S__OD_FIELD_AN___9_9_5_8_8_7__COUNT,
			IProjectVariables.S__OD_FIELD_AN___9_9_7_0_0_5__INPUT__ERROR__COUNT,
			IProjectVariables.S__OD_FIELD_AN___9_9_7_0_0_5__INPUT__LENGHT,
			IProjectVariables.S__OD_FIELD_AN___9_9_7_0_0_6__INPUT__ERROR__COUNT,
			IProjectVariables.S__OD_FIELD_AN___9_9_7_0_0_8__INPUT__ERROR__COUNT,
			IProjectVariables.S__OD_FIELD_AN___9_9_7_0_0_8__INPUT__LENGHT,
			IProjectVariables.S__OD_FIELD_ANI__LENGTH,
			IProjectVariables.S__OD_FIELD_ANI_FIRST_NUMBER,
			IProjectVariables.S__OD_FIELD_ANI_FOUR_NUMBER,
			IProjectVariables.S__OD_FIELD_ANI_TWO_NUMBER,
			IProjectVariables.S__OD_FIELD_BANK__TYPE,
			IProjectVariables.S__OD_FIELD_CVV__MSG,
			IProjectVariables.S__OD_FIELD_DEPDATE,
			IProjectVariables.S__OD_FIELD_DETAIL_TEMP,
			IProjectVariables.S__OD_FIELD_FOREIGNER__TYPE,
			IProjectVariables.S__OD_FIELD_GET_CTICALL_INFO_ERROR_COUNT__ANI,
			IProjectVariables.S__OD_FIELD_ID_9DIGITS,
			IProjectVariables.S__OD_FIELD_ID_FIRST_NUMBER,
			IProjectVariables.S__OD_FIELD_ID_FIRST_TWO_NUMBER,
			IProjectVariables.S__OD_FIELD_ID_IS_CORRECT,
			IProjectVariables.S__OD_FIELD_INSERT__ATM__RESULT__CODE,
			IProjectVariables.S__OD_FIELD_MN___9_9_7_0_0_9__ERROR__COUNT,
			IProjectVariables.S__OD_FIELD_MONTH,
			IProjectVariables.S__OD_FIELD_NINE_DIGITS_PHONE_NUMBER,
			IProjectVariables.S__OD_FIELD_OPERATION__DATE__FINISH,
			IProjectVariables.S__OD_FIELD_OPERATION__DATE__START,
			IProjectVariables.S__OD_FIELD_OPERATION__TIME__FINISH,
			IProjectVariables.S__OD_FIELD_OPERATION__TIME__NOW,
			IProjectVariables.S__OD_FIELD_OPERATION__TIME__START,
			IProjectVariables.S__OD_FIELD_RANDOM_NUMBER,
			IProjectVariables.S__OD_FIELD_REQ__DATE,
			IProjectVariables.S__OD_FIELD_SELECT_COLLECT_RESULTCODE,
			IProjectVariables.S__OD_FIELD_SERVICE__CTRL__TYPE,
			IProjectVariables.S__OD_FIELD_SIM__LOST,
			IProjectVariables.S__OD_FIELD_SOCIAL__NUM__LENGHT,
			IProjectVariables.S__OD_FIELD_TRANSACTION__ANI,
			IProjectVariables.S__OD_FIELD_TRANSACTION__LIMIT__FLAG,
			IProjectVariables.S__OD_FIELD_UNHL__TYPE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.S__OD, variableFields, new String[] {"", "", "", "", "", "", "", "", "", "", "", "", "", "0", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CH__PROPERTIES_FIELD_CHANNEL,
			IProjectVariables.CH__PROPERTIES_FIELD_MIDDLEWARE_IP,
			IProjectVariables.CH__PROPERTIES_FIELD_TEST__MODE,
			IProjectVariables.CH__PROPERTIES_FIELD_VDN };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CH__PROPERTIES, variableFields, new String[] {"01", "", "1", ""}, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CTICALLINFO_FIELD_ANI,
			IProjectVariables.CTICALLINFO_FIELD_CALLID,
			IProjectVariables.CTICALLINFO_FIELD_DNIS,
			IProjectVariables.CTICALLINFO_FIELD_STATE,
			IProjectVariables.CTICALLINFO_FIELD_STATIONEXTENSION,
			IProjectVariables.CTICALLINFO_FIELD_UCID,
			IProjectVariables.CTICALLINFO_FIELD_UUI };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CTICALLINFO, variableFields, null, session, false, true );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.TENANT_FIELD_TENANT_ID };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.TENANT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.INSERT__START_TIME, "", null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.AIR__MENU__DETAIL_FIELD_COUNT,
			IProjectVariables.AIR__MENU__DETAIL_FIELD_IVRFLOW,
			IProjectVariables.AIR__MENU__DETAIL_FIELD_MENU__ID,
			IProjectVariables.AIR__MENU__DETAIL_FIELD_MENU__TIME,
			IProjectVariables.AIR__MENU__DETAIL_FIELD_STR__LEVEL__DESC,
			IProjectVariables.AIR__MENU__DETAIL_FIELD_STR__LOG,
			IProjectVariables.AIR__MENU__DETAIL_FIELD_TID };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.AIR__MENU__DETAIL, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CIE__CREATE_SERVICE__INPUT_FIELD_BP_ID,
			IProjectVariables.CIE__CREATE_SERVICE__INPUT_FIELD_CIE__CREATE_DATE,
			IProjectVariables.CIE__CREATE_SERVICE__INPUT_FIELD_CIE__END_DATE,
			IProjectVariables.CIE__CREATE_SERVICE__INPUT_FIELD_CIE__IN_OUTBOUND,
			IProjectVariables.CIE__CREATE_SERVICE__INPUT_FIELD_CIE__IS_NON_FET,
			IProjectVariables.CIE__CREATE_SERVICE__INPUT_FIELD_CIE__START_DATE,
			IProjectVariables.CIE__CREATE_SERVICE__INPUT_FIELD_FLOW_NAME,
			IProjectVariables.CIE__CREATE_SERVICE__INPUT_FIELD_MSISDN_NUMBER,
			IProjectVariables.CIE__CREATE_SERVICE__INPUT_FIELD_SESSION_ID,
			IProjectVariables.CIE__CREATE_SERVICE__INPUT_FIELD_SUBSCRIBER,
			IProjectVariables.CIE__CREATE_SERVICE__INPUT_FIELD_TRANS_PATH };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CIE__CREATE_SERVICE__INPUT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CREATE_TXN_RECORD__INPUT_FIELD_CIE_CHANGE_ITEM_TYPE,
			IProjectVariables.CREATE_TXN_RECORD__INPUT_FIELD_CIE_ID,
			IProjectVariables.CREATE_TXN_RECORD__INPUT_FIELD_CIE_TXN_LAST_UPDATE_USER,
			IProjectVariables.CREATE_TXN_RECORD__INPUT_FIELD_CONTACT_ITEM_GROUP_CODE,
			IProjectVariables.CREATE_TXN_RECORD__INPUT_FIELD_CONTACT_ITEM_GROUP_NAME,
			IProjectVariables.CREATE_TXN_RECORD__INPUT_FIELD_CONTACT_ITEM_TYPE_CODE,
			IProjectVariables.CREATE_TXN_RECORD__INPUT_FIELD_CONTACT_ITEM_TYPE_NAME,
			IProjectVariables.CREATE_TXN_RECORD__INPUT_FIELD_CREATED_SYSTEM,
			IProjectVariables.CREATE_TXN_RECORD__INPUT_FIELD_NEW_VALUE,
			IProjectVariables.CREATE_TXN_RECORD__INPUT_FIELD_OLD_VALUE,
			IProjectVariables.CREATE_TXN_RECORD__INPUT_FIELD_REMARK,
			IProjectVariables.CREATE_TXN_RECORD__INPUT_FIELD_SERVICE_PROVIDER,
			IProjectVariables.CREATE_TXN_RECORD__INPUT_FIELD_TOPICS };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CREATE_TXN_RECORD__INPUT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.TASK___3_8_0__TBL_FIELD_AMT,
			IProjectVariables.TASK___3_8_0__TBL_FIELD_ANI,
			IProjectVariables.TASK___3_8_0__TBL_FIELD_COUNT,
			IProjectVariables.TASK___3_8_0__TBL_FIELD_JOB,
			IProjectVariables.TASK___3_8_0__TBL_FIELD_MSISDN,
			IProjectVariables.TASK___3_8_0__TBL_FIELD_REASON,
			IProjectVariables.TASK___3_8_0__TBL_FIELD_REQ__DATE,
			IProjectVariables.TASK___3_8_0__TBL_FIELD_REQ__ETIME,
			IProjectVariables.TASK___3_8_0__TBL_FIELD_REQ__STIME,
			IProjectVariables.TASK___3_8_0__TBL_FIELD_SID,
			IProjectVariables.TASK___3_8_0__TBL_FIELD_STATUS,
			IProjectVariables.TASK___3_8_0__TBL_FIELD_TID };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.TASK___3_8_0__TBL, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.IVR__DONATE__TRAN_FIELD_ANI,
			IProjectVariables.IVR__DONATE__TRAN_FIELD_API__REQ__DATE,
			IProjectVariables.IVR__DONATE__TRAN_FIELD_COUNT,
			IProjectVariables.IVR__DONATE__TRAN_FIELD_CYCLY__DATE,
			IProjectVariables.IVR__DONATE__TRAN_FIELD_DONATE__CD,
			IProjectVariables.IVR__DONATE__TRAN_FIELD_SELECT__AMOUNT,
			IProjectVariables.IVR__DONATE__TRAN_FIELD_SUB__TYPE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.IVR__DONATE__TRAN, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CH__FE__PARM__TBL_FIELD_FE__PARM__PARM,
			IProjectVariables.CH__FE__PARM__TBL_FIELD_FE__PARM__VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CH__FE__PARM__TBL, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CIE__RECORD_SERVICE__OUTPUT_FIELD_APICONNECTTIMELONG,
			IProjectVariables.CIE__RECORD_SERVICE__OUTPUT_FIELD_CIECHANGE_EXCEPTION,
			IProjectVariables.CIE__RECORD_SERVICE__OUTPUT_FIELD_CIECHANGE_RETURNCODE,
			IProjectVariables.CIE__RECORD_SERVICE__OUTPUT_FIELD_EXCEPTION,
			IProjectVariables.CIE__RECORD_SERVICE__OUTPUT_FIELD_REMARK_RESPONSE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CIE__RECORD_SERVICE__OUTPUT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.TIME_FIELD_AUDIO,
			IProjectVariables.TIME_FIELD_HOUR,
			IProjectVariables.TIME_FIELD_MILLISECOND,
			IProjectVariables.TIME_FIELD_MINUTE,
			IProjectVariables.TIME_FIELD_SECOND,
			IProjectVariables.TIME_FIELD_TIMEZONE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.TIME, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.SHAREDUUI_FIELD_ID,
			IProjectVariables.SHAREDUUI_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.SHAREDUUI, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__INPUT_FIELD_CHANNEL_FOR_CFG,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__INPUT_FIELD_CHANNEL_ID,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__INPUT_FIELD_FLOW_NAME,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__INPUT_FIELD_MSISDN,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__INPUT_FIELD_PASSWORD,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__INPUT_FIELD_TRANS_BP_ID,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__INPUT_FIELD_TRANS_CHANNEL_ID,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__INPUT_FIELD_TRANS_PATH,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__INPUT_FIELD_TRANS_SUB_CHANNEL,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__INPUT_FIELD_TRANS_USER_ID,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__INPUT_FIELD_USER_ID };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__INPUT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.IVR__OPERATION__CTRL_FIELD_COUNT,
			IProjectVariables.IVR__OPERATION__CTRL_FIELD_COUNT__DONATION,
			IProjectVariables.IVR__OPERATION__CTRL_FIELD_CTRL__FINISH__DATE,
			IProjectVariables.IVR__OPERATION__CTRL_FIELD_CTRL__FINISH__TIME,
			IProjectVariables.IVR__OPERATION__CTRL_FIELD_CTRL__MODIFY__DATE,
			IProjectVariables.IVR__OPERATION__CTRL_FIELD_CTRL__START__DATE,
			IProjectVariables.IVR__OPERATION__CTRL_FIELD_CTRL__START__TIME,
			IProjectVariables.IVR__OPERATION__CTRL_FIELD_OPERATION__CTRL__FLAG,
			IProjectVariables.IVR__OPERATION__CTRL_FIELD_OPERATION__CTRL__NAME,
			IProjectVariables.IVR__OPERATION__CTRL_FIELD_OPERATION__CTRL__NO,
			IProjectVariables.IVR__OPERATION__CTRL_FIELD_OPERATION__CTRL__TYPE,
			IProjectVariables.IVR__OPERATION__CTRL_FIELD_VOCAL__NUM };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.IVR__OPERATION__CTRL, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_ADDRESS_ID,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_ADDRESS_LINE_ONE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_ADDRESS_USAGE_TYPE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_ADDRESS_USAGE_VALUE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_BILL_ADDRESS_ERROR_INDICATOR,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_BILLING_SUBSCRIBER_STATUS_TYPE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_BILLING_SUBSCRIBER_STATUS_VALUE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_BIRTH_DATE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_CITIZENSHIP_TYPE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_CITIZENSHIP_VALUE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_CITY,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_CLIENT_SYSTEM_NAME,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_COHDISTINGUISH_NAME_ID,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_COHSUBSCRIBER_STATUS_TYPE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_COHSUBSCRIBER_STATUS_VALUE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_COMPANY_NAME,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_COMPONENT_ID,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_CONTRACT_COMPONENT_ID,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_CONTRACT_COMPONENT_ID_PK,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_CONTRACT_COMPONENT_TYPE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_CONTRACT_COMPONENT_VALUE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_CONTRACT_ID,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_CONTRACT_ROLE_ID_PK,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_CONTRACT_STATUS_TYPE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_CONTRACT_STATUS_VALUE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_CREATED_DATE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_DEALER_CODE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_DEPARTMENT_NAME,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_IDENTIFICATION_NUMBER,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_IMAGE_CODE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_INITIAL_ACTIVE_DATE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_IVRLANGUAGE_PREFERENCE_TYPE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_IVRLANGUAGE_PREFERENCE_VALUE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_JOB_TITLE_TYPE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_JOB_TITLE_VALUE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_LAST_NAME,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_LEGACY_CODE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_MARITAL_STATUS_TYPE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_MARITAL_STATUS_VALUE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_MOBILE_GENERATION_CODE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_PARTY_ACTIVE_INDICATOR,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_PARTY_ADDRESS_ID_PK,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_PARTY_TYPE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_PASSWORD,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_PAYMENT_CATEGORY,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_PAYMENT_DEDUCT_SMSINDICATOR,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_PERSON_NAME,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_PERSON_PARTY_ID,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_PRIM_RESOURCE_CATEGORY,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_PROCESS_ID,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_PROCESS_NAME,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_PRODUCT_MIGRATION_ORIGINAL_ACTIVE_DATE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_PRODUCT_TYPE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_PRODUCT_VALUE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_PROMOTION_SMSINDICATOR,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_REGION,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_REQUESTER_LANGUAGE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_REQUESTER_LOCALE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_REQUESTER_NAME,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_REQUEST_ORIGIN,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_RESOURCE_START_DATE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_RESPONSE_CONTROL__RESULT_CODE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_RETURN_CODE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_RETURN_MESG,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_ROLE_TYPE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_ROLE_VALUE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_SERVICE_PROVIDER,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_SERVICE_SMSINDICATOR,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_SERVICE_TIME,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_SESSION_ID,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_START_DATE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_SUBSCRIBER_STATUS_LAST_ACTIVITY,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_SUBSCRIBER_STATUS_LAST_UPDATE_DT,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_SUBSCRIBER_STATUS_REASON,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_TCRMCONTRACT_COMPONENT_BOBJ__TCRMEXTENSION__EXTENDED_OBJECT,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_TCRMCONTRACT_PARTY_ROLE_BOBJ__PARTY_ID,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_TCRMPARTY_ADDRESS_BOBJ__PARTY_ID,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_TCRMPARTY_IDENTIFICATION_BOBJ_TYPE__IDENTIFICATION_NUMBER,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_TCRMPERSON_BOBJ__PARTY_ID,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_TCRMPERSON_BOBJ__TCRMEXTENSION__EXTENDED_OBJECT,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_TCRMPERSON_BOBJ_TYPE__BIRTH_DATE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT_FIELD_TX_RESULT__RESULT_CODE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__OUTPUT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CIE__CREATE_SERVICE__OUTPUT_FIELD_ACCOUNT_CONTACT_ID,
			IProjectVariables.CIE__CREATE_SERVICE__OUTPUT_FIELD_ACCOUNT_CONTRACT_COMP_ID,
			IProjectVariables.CIE__CREATE_SERVICE__OUTPUT_FIELD_APICONNECTTIMELONG,
			IProjectVariables.CIE__CREATE_SERVICE__OUTPUT_FIELD_BILLING_ACCOUNT_ID,
			IProjectVariables.CIE__CREATE_SERVICE__OUTPUT_FIELD_BILLING_SUBSCRIBER_ID,
			IProjectVariables.CIE__CREATE_SERVICE__OUTPUT_FIELD_CACHE_SUBSCRIBER_INFO_EXCEPTION,
			IProjectVariables.CIE__CREATE_SERVICE__OUTPUT_FIELD_CACHE_SUBSCRIBER_INFO_RESULT_CODE,
			IProjectVariables.CIE__CREATE_SERVICE__OUTPUT_FIELD_CIEADD_EXCEPTION,
			IProjectVariables.CIE__CREATE_SERVICE__OUTPUT_FIELD_CIEADD_RETURNCODE,
			IProjectVariables.CIE__CREATE_SERVICE__OUTPUT_FIELD_CIE_DETAIL_ID,
			IProjectVariables.CIE__CREATE_SERVICE__OUTPUT_FIELD_CIE_ID,
			IProjectVariables.CIE__CREATE_SERVICE__OUTPUT_FIELD_CONTRACT__ID,
			IProjectVariables.CIE__CREATE_SERVICE__OUTPUT_FIELD_EXCEPTION,
			IProjectVariables.CIE__CREATE_SERVICE__OUTPUT_FIELD_IVR__LANG,
			IProjectVariables.CIE__CREATE_SERVICE__OUTPUT_FIELD_MOBILE_GENERATION_CODE,
			IProjectVariables.CIE__CREATE_SERVICE__OUTPUT_FIELD_MSISDN,
			IProjectVariables.CIE__CREATE_SERVICE__OUTPUT_FIELD_PAYMENT_CATEGORY,
			IProjectVariables.CIE__CREATE_SERVICE__OUTPUT_FIELD_SERVICE_PROVIDER,
			IProjectVariables.CIE__CREATE_SERVICE__OUTPUT_FIELD_SUBSCRIBER__STATUS,
			IProjectVariables.CIE__CREATE_SERVICE__OUTPUT_FIELD_SUBSCRIBER__TYPE,
			IProjectVariables.CIE__CREATE_SERVICE__OUTPUT_FIELD_SUBSCRIBER_CONTACT_ID,
			IProjectVariables.CIE__CREATE_SERVICE__OUTPUT_FIELD_SUBSCRIBER_CONTRACT_COMP_ID };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CIE__CREATE_SERVICE__OUTPUT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CREATE_ORDER_EX__OUTPUT_FIELD_BASKET_ITEM_ID,
			IProjectVariables.CREATE_ORDER_EX__OUTPUT_FIELD_ORDER_ID,
			IProjectVariables.CREATE_ORDER_EX__OUTPUT_FIELD_RESERVED_1,
			IProjectVariables.CREATE_ORDER_EX__OUTPUT_FIELD_RETURN_CODE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CREATE_ORDER_EX__OUTPUT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__CALL__TYPE,
			IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__CELL__NUM,
			IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__CHANNEL,
			IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__DATE,
			IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__ENDTIME,
			IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__IN__ENTERPRISE,
			IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__IN__VDN,
			IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__INDX,
			IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__L_1,
			IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__L_1_0,
			IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__L_2,
			IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__L_3,
			IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__L_4,
			IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__L_5,
			IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__L_6,
			IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__L_7,
			IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__L_8,
			IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__L_9,
			IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__LANG,
			IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__NODE__ID,
			IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__OUT__VDN,
			IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__STARTTIME,
			IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__STR__LOG,
			IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_COUNT };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.TASK___0_8_0_9_0_0_0_8_1_1__TBL_FIELD_ENTERPRISE,
			IProjectVariables.TASK___0_8_0_9_0_0_0_8_1_1__TBL_FIELD_PIN_CODE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.TASK___0_8_0_9_0_0_0_8_1_1__TBL, variableFields, null, session, false, false );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.INSERT__TABLE_NAME, "", null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.S__USERDATA_FIELD_ACTIVE____DATE,
			IProjectVariables.S__USERDATA_FIELD_ANI,
			IProjectVariables.S__USERDATA_FIELD_BIRTHDAY,
			IProjectVariables.S__USERDATA_FIELD_BPID,
			IProjectVariables.S__USERDATA_FIELD_BUSINESS_ENTITY_NUMBER,
			IProjectVariables.S__USERDATA_FIELD_CHANNEL_FOR_CFG,
			IProjectVariables.S__USERDATA_FIELD_CHENNEL,
			IProjectVariables.S__USERDATA_FIELD_CITIZENSHIPTYPE,
			IProjectVariables.S__USERDATA_FIELD_DNIS,
			IProjectVariables.S__USERDATA_FIELD_FLC__OFFER__ID,
			IProjectVariables.S__USERDATA_FIELD_FLOW_NAME,
			IProjectVariables.S__USERDATA_FIELD_ID__TYPE,
			IProjectVariables.S__USERDATA_FIELD_IDENTIFIER,
			IProjectVariables.S__USERDATA_FIELD_NEXTVAL,
			IProjectVariables.S__USERDATA_FIELD_OUT__VDN,
			IProjectVariables.S__USERDATA_FIELD_PAYMENT_CATEGORY,
			IProjectVariables.S__USERDATA_FIELD_PHONENUMBER,
			IProjectVariables.S__USERDATA_FIELD_SUB__TYPE,
			IProjectVariables.S__USERDATA_FIELD_SUBSCRIBER__NO,
			IProjectVariables.S__USERDATA_FIELD_UCID,
			IProjectVariables.S__USERDATA_FIELD_UUI };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.S__USERDATA, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.G__ERROR__COUNT_FIELD_ACCUMULATE_TWO,
			IProjectVariables.G__ERROR__COUNT_FIELD_ERROR_COUNT_1,
			IProjectVariables.G__ERROR__COUNT_FIELD_ERROR_COUNT_2,
			IProjectVariables.G__ERROR__COUNT_FIELD_ERROR_COUNT_3,
			IProjectVariables.G__ERROR__COUNT_FIELD_ERROR_COUNT_4,
			IProjectVariables.G__ERROR__COUNT_FIELD_ERROR_COUNT_FOR_CHILD_WELFARE,
			IProjectVariables.G__ERROR__COUNT_FIELD_ERROR_COUNTFOR_FAR_EAST_ONE,
			IProjectVariables.G__ERROR__COUNT_FIELD_ERROR_COUNT_FOR_PAPER_WILDMILL,
			IProjectVariables.G__ERROR__COUNT_FIELD_ERROR_COUNT_FOR_TEACHER_CHANG,
			IProjectVariables.G__ERROR__COUNT_FIELD_RE_INPUT_COUNT_FOR_PHONE_NUMBER,
			IProjectVariables.G__ERROR__COUNT_FIELD_RE_INPUT_FOR_3_8_0__ID__CHECK,
			IProjectVariables.G__ERROR__COUNT_FIELD_RE_INPUT_PIN_CODE,
			IProjectVariables.G__ERROR__COUNT_FIELD_RE_INPUT_TENANT_IDCOUNT };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.G__ERROR__COUNT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.EVENT__NAME, "", null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_COUNT,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_CREATED__DATE,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__ACT__DATE,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__BILL__PLAN,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__BT__CUST__ID,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__CB__ACCOUNT__ID,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__CB__BA__ID,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__CB__BUSINESS__TYPE,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__CB__CID,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__CB__CON__EXPIRE__DATE,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__CB__CORP__FLAG,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__CB__CUSTOMER__ID,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__CB__CUSTOMER__TYPE,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__CB__GPRS__FLAG,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__CB__HYBRID__FLAG,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__CB__LANGUAGE__ID,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__CB__MVPN__FLAG,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__CB__PAY__CHANNEL__DESC,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__CB__PAY__CHANNEL__ID,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__CB__SERVICE__TYPE,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__CB__SIMM__FLAG,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__CB__SUBR__PWD,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__CB__SUBSCRIBER__ID,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__DATA__PLAN,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__DATA__UNLIMITED__FLAG,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__END__DATE,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__HOLDING__CUST__ID,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__PLAN__SDATE,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__PROMO__CODE,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__PUK_1,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__PUK_2,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__QOSID,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__REASON__CODE,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__SIM__NO,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__START__DATE,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__STATUS,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__MSIS__TELE__NUMB,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_FE__R_4ID,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_GRPID,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_GRPLD,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_MODIFIED__DATE,
			IProjectVariables.FE__MSIS__CB_2__TBL_FIELD_RESPONSE_CODE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.FE__MSIS__CB_2__TBL, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT_FIELD_ACCOUNT_CONTRACT_COMPONENT_ID,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT_FIELD_ACCOUNT_ID,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT_FIELD_ACCOUNT_PARTY_ID,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT_FIELD_ADMIN_FLD_NM_TP_CD,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT_FIELD_CONTRACT_COMPONENT_ID,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT_FIELD_CONTRACT_ID,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT_FIELD_CUSTOMER_ID,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT_FIELD_DATA_SOURCE,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT_FIELD_GENERATION_CODE,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT_FIELD_INIT_ACTIVE_DT,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT_FIELD_IVR_LANG,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT_FIELD_LAST_MSISDN_UPDATE_DT,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT_FIELD_LAST_SUB_ST_ACTIVITY,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT_FIELD_LAST_SUB_ST_DT,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT_FIELD_LEGACY_CODE,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT_FIELD_MSISDN,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT_FIELD_PARTY_ID,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT_FIELD_PAYMENT_CATEGORY,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT_FIELD_PROCESS_ID,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT_FIELD_PROCESS_NAME,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT_FIELD_RETURN_CODE,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT_FIELD_RETURN_MESG,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT_FIELD_SERVICE_PROVIDER,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT_FIELD_SUBSCRIBER_ID,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT_FIELD_SUBSCRIBER_STATUS,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT_FIELD_SUBSCRIBER_TYPE,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT_FIELD_SUB_ST_REASON,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT_FIELD_SUB_ST_REASON_DESR,
			IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT_FIELD_UPDATE_DT };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.GET_CASH_SUBSCRIBER_INFO_BY_KEY__OUTPUT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__CALL__TYPE,
			IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__CELL__NUM,
			IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__CHANNEL,
			IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__DATE,
			IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__ENDTIME,
			IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__IN__ENTERPRISE,
			IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__IN__VDN,
			IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__INDX,
			IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__L_1,
			IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__L_1_0,
			IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__L_2,
			IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__L_3,
			IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__L_4,
			IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__L_5,
			IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__L_6,
			IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__L_7,
			IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__L_8,
			IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__L_9,
			IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__LANG,
			IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__NODE__ID,
			IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__OUT__VDN,
			IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__STARTTIME,
			IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__STR__LOG,
			IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_COUNT };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.AIR___5_5_1_3_5__MENU__TBL, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__CALL__TYPE,
			IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__CELL__NUM,
			IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__CHANNEL,
			IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__DATE,
			IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__ENDTIME,
			IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__IN__ENTERPRISE,
			IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__IN__VDN,
			IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__INDX,
			IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__L_1,
			IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__L_1_0,
			IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__L_2,
			IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__L_3,
			IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__L_4,
			IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__L_5,
			IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__L_6,
			IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__L_7,
			IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__L_8,
			IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__L_9,
			IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__LANG,
			IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__NODE__ID,
			IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__OUT__VDN,
			IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__STARTTIME,
			IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__STR__LOG,
			IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_COUNT };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.FE__API__LOG__TBL_FIELD_API,
			IProjectVariables.FE__API__LOG__TBL_FIELD_BPID,
			IProjectVariables.FE__API__LOG__TBL_FIELD_COUNT,
			IProjectVariables.FE__API__LOG__TBL_FIELD_ETIME,
			IProjectVariables.FE__API__LOG__TBL_FIELD_IVR,
			IProjectVariables.FE__API__LOG__TBL_FIELD_MSISDN,
			IProjectVariables.FE__API__LOG__TBL_FIELD_ORDERID,
			IProjectVariables.FE__API__LOG__TBL_FIELD_ORDERSTATE,
			IProjectVariables.FE__API__LOG__TBL_FIELD_RESERVED_1,
			IProjectVariables.FE__API__LOG__TBL_FIELD_RETURNCODE,
			IProjectVariables.FE__API__LOG__TBL_FIELD_SDATE,
			IProjectVariables.FE__API__LOG__TBL_FIELD_SEC,
			IProjectVariables.FE__API__LOG__TBL_FIELD_STIME,
			IProjectVariables.FE__API__LOG__TBL_FIELD_STR__DATA,
			IProjectVariables.FE__API__LOG__TBL_FIELD_SUBSCRIBER };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.FE__API__LOG__TBL, variableFields, null, session, false, false );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.ADD_ZERO, "", null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.AIR__MENU__MASTER_FIELD_AGT__UCID,
			IProjectVariables.AIR__MENU__MASTER_FIELD_ANI,
			IProjectVariables.AIR__MENU__MASTER_FIELD_CALL__TYPE,
			IProjectVariables.AIR__MENU__MASTER_FIELD_CHANNEL,
			IProjectVariables.AIR__MENU__MASTER_FIELD_CIE__ID,
			IProjectVariables.AIR__MENU__MASTER_FIELD_COUNT,
			IProjectVariables.AIR__MENU__MASTER_FIELD_END__TIME,
			IProjectVariables.AIR__MENU__MASTER_FIELD_IN__ENTERPRISE,
			IProjectVariables.AIR__MENU__MASTER_FIELD_IN__MVPN,
			IProjectVariables.AIR__MENU__MASTER_FIELD_IN__VDN,
			IProjectVariables.AIR__MENU__MASTER_FIELD_IVR__UCID,
			IProjectVariables.AIR__MENU__MASTER_FIELD_IVRFLOW,
			IProjectVariables.AIR__MENU__MASTER_FIELD_LANG,
			IProjectVariables.AIR__MENU__MASTER_FIELD_MENU__DATE,
			IProjectVariables.AIR__MENU__MASTER_FIELD_MENU__ID,
			IProjectVariables.AIR__MENU__MASTER_FIELD_MSISDN,
			IProjectVariables.AIR__MENU__MASTER_FIELD_OUT__VDN,
			IProjectVariables.AIR__MENU__MASTER_FIELD_START__TIME,
			IProjectVariables.AIR__MENU__MASTER_FIELD_STR__LEVEL__DESC,
			IProjectVariables.AIR__MENU__MASTER_FIELD_STR__LOG,
			IProjectVariables.AIR__MENU__MASTER_FIELD_TID };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.AIR__MENU__MASTER, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.AIR__MENU_FIELD_MENU__ID };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.AIR__MENU, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CH__PHONENUM_FIELD_FLAG,
			IProjectVariables.CH__PHONENUM_FIELD_FROM,
			IProjectVariables.CH__PHONENUM_FIELD_LENGTH,
			IProjectVariables.CH__PHONENUM_FIELD_PHONE,
			IProjectVariables.CH__PHONENUM_FIELD_ZERO };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CH__PHONENUM, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__CALL__TYPE,
			IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__CELL__NUM,
			IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__CHANNEL,
			IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__DATE,
			IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__ENDTIME,
			IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__IN__ENTERPRISE,
			IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__IN__VDN,
			IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__INDX,
			IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__L_1,
			IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__L_1_0,
			IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__L_2,
			IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__L_3,
			IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__L_4,
			IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__L_5,
			IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__L_6,
			IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__L_7,
			IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__L_8,
			IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__L_9,
			IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__LANG,
			IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__NODE__ID,
			IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__OUT__VDN,
			IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__STARTTIME,
			IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__STR__LOG,
			IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_COUNT };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__CALL__TYPE,
			IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__CELL__NUM,
			IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__CHANNEL,
			IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__DATE,
			IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__ENDTIME,
			IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__IN__ENTERPRISE,
			IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__IN__VDN,
			IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__INDX,
			IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__L_1,
			IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__L_1_0,
			IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__L_2,
			IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__L_3,
			IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__L_4,
			IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__L_5,
			IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__L_6,
			IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__L_7,
			IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__L_8,
			IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__L_9,
			IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__LANG,
			IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__NODE__ID,
			IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__OUT__VDN,
			IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__STARTTIME,
			IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__STR__LOG };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.AIR___3_8_0__MENU__TBL, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CREATE_TXN_RECORD__OUTPUT_FIELD_EXCEPTION,
			IProjectVariables.CREATE_TXN_RECORD__OUTPUT_FIELD_LEGACY_CODE,
			IProjectVariables.CREATE_TXN_RECORD__OUTPUT_FIELD_PROCESS_ID,
			IProjectVariables.CREATE_TXN_RECORD__OUTPUT_FIELD_PROCESS_NAME,
			IProjectVariables.CREATE_TXN_RECORD__OUTPUT_FIELD_RETURN_CODE,
			IProjectVariables.CREATE_TXN_RECORD__OUTPUT_FIELD_RETURN_MESG };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CREATE_TXN_RECORD__OUTPUT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.SESSION_FIELD_AAI,
			IProjectVariables.SESSION_FIELD_ANI,
			IProjectVariables.SESSION_FIELD_CALLTAG,
			IProjectVariables.SESSION_FIELD_CHANNEL,
			IProjectVariables.SESSION_FIELD_CHANNELTYPE,
			IProjectVariables.SESSION_FIELD_CONVERSEFIRST,
			IProjectVariables.SESSION_FIELD_CONVERSESECOND,
			IProjectVariables.SESSION_FIELD_CURRENTLANGUAGE,
			IProjectVariables.SESSION_FIELD_DNIS,
			IProjectVariables.SESSION_FIELD_EXIT_CUSTOMER_ID,
			IProjectVariables.SESSION_FIELD_EXIT_INFO_1,
			IProjectVariables.SESSION_FIELD_EXIT_INFO_2,
			IProjectVariables.SESSION_FIELD_EXIT_PARENT_ID,
			IProjectVariables.SESSION_FIELD_EXIT_PREFERRED_PATH,
			IProjectVariables.SESSION_FIELD_EXIT_REASON,
			IProjectVariables.SESSION_FIELD_EXIT_TOPIC,
			IProjectVariables.SESSION_FIELD_LASTERROR,
			IProjectVariables.SESSION_FIELD_MEDIATYPE,
			IProjectVariables.SESSION_FIELD_PROTOCOLNAME,
			IProjectVariables.SESSION_FIELD_PROTOCOLVERSION,
			IProjectVariables.SESSION_FIELD_SESSIONID,
			IProjectVariables.SESSION_FIELD_SESSIONLABEL,
			IProjectVariables.SESSION_FIELD_SHAREDMODE,
			IProjectVariables.SESSION_FIELD_UCID,
			IProjectVariables.SESSION_FIELD_UUI,
			IProjectVariables.SESSION_FIELD_VIDEOBITRATE,
			IProjectVariables.SESSION_FIELD_VIDEOCODEC,
			IProjectVariables.SESSION_FIELD_VIDEOENABLED,
			IProjectVariables.SESSION_FIELD_VIDEOFARFMTP,
			IProjectVariables.SESSION_FIELD_VIDEOFORMAT,
			IProjectVariables.SESSION_FIELD_VIDEOFPS,
			IProjectVariables.SESSION_FIELD_VIDEOHEIGHT,
			IProjectVariables.SESSION_FIELD_VIDEONEARFMTP,
			IProjectVariables.SESSION_FIELD_VIDEOWIDTH,
			IProjectVariables.SESSION_FIELD_VPCALLEDEXTENSION,
			IProjectVariables.SESSION_FIELD_VPCONVERSEONDATA,
			IProjectVariables.SESSION_FIELD_VPCOVERAGEREASON,
			IProjectVariables.SESSION_FIELD_VPCOVERAGETYPE,
			IProjectVariables.SESSION_FIELD_VPRDNIS,
			IProjectVariables.SESSION_FIELD_VPREPORTURL };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.SESSION, variableFields, null, session, false, true );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CH__AIR__MENU_FIELD_MENU__ID };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CH__AIR__MENU, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.UNTITLED_MENU_1_FIELD_CONFIDENCE,
			IProjectVariables.UNTITLED_MENU_1_FIELD_INPUTMODE,
			IProjectVariables.UNTITLED_MENU_1_FIELD_INTERPRETATION,
			IProjectVariables.UNTITLED_MENU_1_FIELD_NOINPUTCOUNT,
			IProjectVariables.UNTITLED_MENU_1_FIELD_NOMATCHCOUNT,
			IProjectVariables.UNTITLED_MENU_1_FIELD_UTTERANCE,
			IProjectVariables.UNTITLED_MENU_1_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.UNTITLED_MENU_1, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_ACCOUNT_NO_INFO,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_AMOUNT,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_AMOUNT_CURRENCY,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_ATTRIBUTE_NAME___0,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_ATTRIBUTE_NAME___1,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_ATTRIBUTE_NAME___2,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_ATTRIBUTE_TYPE___0,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_ATTRIBUTE_TYPE___1,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_ATTRIBUTE_TYPE___2,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_BA_ID,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_BUSINESS_ENTITY,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_BUSINESS_ENTITY_NUMBER,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_CHANNEL_FOR_CFG,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_CHANNEL_ID,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_CHARGE_CODE,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_CHARGE_ORIGIN,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_CHARGE_TYPE,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_CYCLE_SEQ_RUN,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_DEFAULT_VALUE,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_DESCRIPTION,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_EFFECTIVE_DATE,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_EVENT_TYPE,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_FLOW_NAME,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_MANDATORY_IND___0,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_MANDATORY_IND___1,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_MANDATORY_IND___2,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_OFFER_ID,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_OFFER_INSTANCE,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_OFFER_ITEM_ID,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_PASSWORD,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_PAYMENT_CATEGORY,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_PCN,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_PROCESS_ID,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_PROCESS_TRANSACTION_ID,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_RECIVER_CUSTOMER_ID,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_SERVICE_RECIVER_ID,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_SERVICE_RECIVER_TYPE,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_TRANS_BP_ID,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_TRANS_CHANNEL_ID,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_TRANS_PATH,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_TRANS_SUB_CHANNEL,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_TRANS_USER_ID,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_USER_ID,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_VALUE___0,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_VALUE___1,
			IProjectVariables.CREATE_CHARGE__INPUT_FIELD_VALUE___2 };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CREATE_CHARGE__INPUT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DN___5_5_6_0_3_2_FIELD_CONFIDENCE,
			IProjectVariables.DN___5_5_6_0_3_2_FIELD_INPUTMODE,
			IProjectVariables.DN___5_5_6_0_3_2_FIELD_INTERPRETATION,
			IProjectVariables.DN___5_5_6_0_3_2_FIELD_NOINPUTCOUNT,
			IProjectVariables.DN___5_5_6_0_3_2_FIELD_NOMATCHCOUNT,
			IProjectVariables.DN___5_5_6_0_3_2_FIELD_UTTERANCE,
			IProjectVariables.DN___5_5_6_0_3_2_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DN___5_5_6_0_3_2, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DN___5_5_6_0_3_1_FIELD_CONFIDENCE,
			IProjectVariables.DN___5_5_6_0_3_1_FIELD_INPUTMODE,
			IProjectVariables.DN___5_5_6_0_3_1_FIELD_INTERPRETATION,
			IProjectVariables.DN___5_5_6_0_3_1_FIELD_NOINPUTCOUNT,
			IProjectVariables.DN___5_5_6_0_3_1_FIELD_NOMATCHCOUNT,
			IProjectVariables.DN___5_5_6_0_3_1_FIELD_UTTERANCE,
			IProjectVariables.DN___5_5_6_0_3_1_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DN___5_5_6_0_3_1, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DN___5_5_6_0_3_7_FIELD_CONFIDENCE,
			IProjectVariables.DN___5_5_6_0_3_7_FIELD_INPUTMODE,
			IProjectVariables.DN___5_5_6_0_3_7_FIELD_INTERPRETATION,
			IProjectVariables.DN___5_5_6_0_3_7_FIELD_NOINPUTCOUNT,
			IProjectVariables.DN___5_5_6_0_3_7_FIELD_NOMATCHCOUNT,
			IProjectVariables.DN___5_5_6_0_3_7_FIELD_UTTERANCE,
			IProjectVariables.DN___5_5_6_0_3_7_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DN___5_5_6_0_3_7, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DN___5_5_6_0_3_4_FIELD_CONFIDENCE,
			IProjectVariables.DN___5_5_6_0_3_4_FIELD_INPUTMODE,
			IProjectVariables.DN___5_5_6_0_3_4_FIELD_INTERPRETATION,
			IProjectVariables.DN___5_5_6_0_3_4_FIELD_NOINPUTCOUNT,
			IProjectVariables.DN___5_5_6_0_3_4_FIELD_NOMATCHCOUNT,
			IProjectVariables.DN___5_5_6_0_3_4_FIELD_UTTERANCE,
			IProjectVariables.DN___5_5_6_0_3_4_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DN___5_5_6_0_3_4, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DOAMINID_FIELD_ID };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DOAMINID, variableFields, "com.avaya.vp.admin.variables.runtime.AdminVariableFactory", session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.FE__NEWCASH__TBL_FIELD_ACTIVE__DATE,
			IProjectVariables.FE__NEWCASH__TBL_FIELD_BIRTHDAY,
			IProjectVariables.FE__NEWCASH__TBL_FIELD_CONTACT__LANGUAGE,
			IProjectVariables.FE__NEWCASH__TBL_FIELD_COUNT,
			IProjectVariables.FE__NEWCASH__TBL_FIELD_FLC__OFFER__ID,
			IProjectVariables.FE__NEWCASH__TBL_FIELD_HYBRID__EXTERNAL__ID,
			IProjectVariables.FE__NEWCASH__TBL_FIELD_ID__TYPE,
			IProjectVariables.FE__NEWCASH__TBL_FIELD_IDENTIFIER,
			IProjectVariables.FE__NEWCASH__TBL_FIELD_LANGUAGE__TYPE,
			IProjectVariables.FE__NEWCASH__TBL_FIELD_MDMID,
			IProjectVariables.FE__NEWCASH__TBL_FIELD_PAYMENT__TYPE,
			IProjectVariables.FE__NEWCASH__TBL_FIELD_PUK_1,
			IProjectVariables.FE__NEWCASH__TBL_FIELD_PUK_2,
			IProjectVariables.FE__NEWCASH__TBL_FIELD_RESULT_CONT,
			IProjectVariables.FE__NEWCASH__TBL_FIELD_SERV__NBR,
			IProjectVariables.FE__NEWCASH__TBL_FIELD_SERV__STATUS,
			IProjectVariables.FE__NEWCASH__TBL_FIELD_SUB__TYPE,
			IProjectVariables.FE__NEWCASH__TBL_FIELD_SUBSCRIBER__NO };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.FE__NEWCASH__TBL, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CIE__RECORD_SERVICE__INPUT_FIELD_BP_ID,
			IProjectVariables.CIE__RECORD_SERVICE__INPUT_FIELD_CIE__CIE_DETAIL_ID,
			IProjectVariables.CIE__RECORD_SERVICE__INPUT_FIELD_CIE__CIE_ID,
			IProjectVariables.CIE__RECORD_SERVICE__INPUT_FIELD_CIE__CREATE_DATE,
			IProjectVariables.CIE__RECORD_SERVICE__INPUT_FIELD_CIE__END_DATE,
			IProjectVariables.CIE__RECORD_SERVICE__INPUT_FIELD_CIE__START_DATE,
			IProjectVariables.CIE__RECORD_SERVICE__INPUT_FIELD_CIE__SUBSCRIBER_CONTACT_ID,
			IProjectVariables.CIE__RECORD_SERVICE__INPUT_FIELD_FLOW_NAME,
			IProjectVariables.CIE__RECORD_SERVICE__INPUT_FIELD_MENU_IDS,
			IProjectVariables.CIE__RECORD_SERVICE__INPUT_FIELD_MSISDN_NUMBER,
			IProjectVariables.CIE__RECORD_SERVICE__INPUT_FIELD_SESSION_ID,
			IProjectVariables.CIE__RECORD_SERVICE__INPUT_FIELD_STR__LOGS,
			IProjectVariables.CIE__RECORD_SERVICE__INPUT_FIELD_SUBSCRIBER,
			IProjectVariables.CIE__RECORD_SERVICE__INPUT_FIELD_TID,
			IProjectVariables.CIE__RECORD_SERVICE__INPUT_FIELD_TRANS_PATH };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CIE__RECORD_SERVICE__INPUT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.FET___0_8_0_9_0_0_0_8_1_1__STORE__LST_FIELD_ENTERPRISE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.FET___0_8_0_9_0_0_0_8_1_1__STORE__LST, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__CALL__TYPE,
			IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__CELL__NUM,
			IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__CHANNEL,
			IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__DATE,
			IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__ENDTIME,
			IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__IN__ENTERPRISE,
			IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__IN__VDN,
			IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__INDX,
			IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__L_1,
			IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__L_1_0,
			IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__L_2,
			IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__L_3,
			IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__L_4,
			IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__L_5,
			IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__L_6,
			IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__L_7,
			IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__L_8,
			IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__L_9,
			IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__LANG,
			IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__NODE__ID,
			IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__OUT__VDN,
			IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__STARTTIME,
			IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__STR__LOG,
			IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_COUNT };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DN___5_5_6_0_2_1_FIELD_CONFIDENCE,
			IProjectVariables.DN___5_5_6_0_2_1_FIELD_INPUTMODE,
			IProjectVariables.DN___5_5_6_0_2_1_FIELD_INTERPRETATION,
			IProjectVariables.DN___5_5_6_0_2_1_FIELD_NOINPUTCOUNT,
			IProjectVariables.DN___5_5_6_0_2_1_FIELD_NOMATCHCOUNT,
			IProjectVariables.DN___5_5_6_0_2_1_FIELD_RECORDING,
			IProjectVariables.DN___5_5_6_0_2_1_FIELD_RECORDINGDURATION,
			IProjectVariables.DN___5_5_6_0_2_1_FIELD_RECORDINGSIZE,
			IProjectVariables.DN___5_5_6_0_2_1_FIELD_UTTERANCE,
			IProjectVariables.DN___5_5_6_0_2_1_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DN___5_5_6_0_2_1, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_COUNT,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_CREATED__DATE,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_FE__ACCOUNT__CB__ID,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_FE__CUST__ACCOUNT__CAG,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_FE__CUST__ADJUSTMENT,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_FE__CUST__BILL__NAME,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_FE__CUST__BILLER__BALANCE,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_FE__CUST__CURRENT__BALANCE,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_FE__CUST__CUST__ID,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_FE__CUST__CUST__STATUS,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_FE__CUST__CUSTOMER__TYPE,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_FE__CUST__DEMO__ID__TYPE,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_FE__CUST__INVC__OUT__AMOUNT,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_FE__CUST__INVC__PAY__DUE__DAT,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_FE__CUST__INVOICE__CHECKSUM,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_FE__CUST__LAST__BILLED,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_FE__CUST__LAST__INVOICE,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_FE__CUST__NEW__PAYMENT,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_FE__CUST__PAY__AMOUNT,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_FE__CUST__PAY__CHANNEL__DESC,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_FE__CUST__PAY__MADE__DATE,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_FE__CUST__PAYMENT__RULE,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_FE__CUST__PAYMENT__RULE__DATE,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_FE__CUST__RC,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_FE__CUST__SOCIAL__NUM,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_FE__CUST__SOCIAL__NUM___2,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_FE__CUST__SSN,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_FE__CUST__WRITE__OFF,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_FE__MKTG__MSG__ID,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_FE__PAY__CHANNEL__CB__ID,
			IProjectVariables.FE__CUST__CB_2__TBL_FIELD_MODIFIED__DATE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.FE__CUST__CB_2__TBL, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DN___5_5_6_0_2_6_FIELD_CONFIDENCE,
			IProjectVariables.DN___5_5_6_0_2_6_FIELD_INPUTMODE,
			IProjectVariables.DN___5_5_6_0_2_6_FIELD_INTERPRETATION,
			IProjectVariables.DN___5_5_6_0_2_6_FIELD_NOINPUTCOUNT,
			IProjectVariables.DN___5_5_6_0_2_6_FIELD_NOMATCHCOUNT,
			IProjectVariables.DN___5_5_6_0_2_6_FIELD_UTTERANCE,
			IProjectVariables.DN___5_5_6_0_2_6_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DN___5_5_6_0_2_6, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DN___5_5_6_0_2_4_FIELD_CONFIDENCE,
			IProjectVariables.DN___5_5_6_0_2_4_FIELD_INPUTMODE,
			IProjectVariables.DN___5_5_6_0_2_4_FIELD_INTERPRETATION,
			IProjectVariables.DN___5_5_6_0_2_4_FIELD_NOINPUTCOUNT,
			IProjectVariables.DN___5_5_6_0_2_4_FIELD_NOMATCHCOUNT,
			IProjectVariables.DN___5_5_6_0_2_4_FIELD_UTTERANCE,
			IProjectVariables.DN___5_5_6_0_2_4_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DN___5_5_6_0_2_4, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.PROPERTIES_FIELD_API__HARDCODE,
			IProjectVariables.PROPERTIES_FIELD_CHANNEL,
			IProjectVariables.PROPERTIES_FIELD_CHANNEL_FOR_CFG,
			IProjectVariables.PROPERTIES_FIELD_CHANNEL_ID,
			IProjectVariables.PROPERTIES_FIELD_DB__API__IP,
			IProjectVariables.PROPERTIES_FIELD_FLOW_NAME,
			IProjectVariables.PROPERTIES_FIELD_ID_TYPE,
			IProjectVariables.PROPERTIES_FIELD_JNDINAME,
			IProjectVariables.PROPERTIES_FIELD_MIDDLEWARE____IP,
			IProjectVariables.PROPERTIES_FIELD_PASSWORD,
			IProjectVariables.PROPERTIES_FIELD_TEST__MODE,
			IProjectVariables.PROPERTIES_FIELD_TIMEOUT,
			IProjectVariables.PROPERTIES_FIELD_TRANS_CHANNEL_ID,
			IProjectVariables.PROPERTIES_FIELD_TRANS_PATH,
			IProjectVariables.PROPERTIES_FIELD_TRANS_SUB_CHANNEL,
			IProjectVariables.PROPERTIES_FIELD_TRANS_USER_ID,
			IProjectVariables.PROPERTIES_FIELD_USER_ID,
			IProjectVariables.PROPERTIES_FIELD_VIP__ID };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.PROPERTIES, variableFields, new String[] {"", "", "", "30790", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__CALL__TYPE,
			IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__CELL__NUM,
			IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__CHANNEL,
			IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__DATE,
			IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__ENDTIME,
			IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__IN__ENTERPRISE,
			IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__IN__VDN,
			IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__INDX,
			IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__L_1,
			IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__L_1_0,
			IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__L_2,
			IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__L_3,
			IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__L_4,
			IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__L_5,
			IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__L_6,
			IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__L_7,
			IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__L_8,
			IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__L_9,
			IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__LANG,
			IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__NODE__ID,
			IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__OUT__VDN,
			IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__STARTTIME,
			IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__STR__LOG,
			IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_COUNT };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DN___5_5_6_0_2_1___2_FIELD_CONFIDENCE,
			IProjectVariables.DN___5_5_6_0_2_1___2_FIELD_INPUTMODE,
			IProjectVariables.DN___5_5_6_0_2_1___2_FIELD_INTERPRETATION,
			IProjectVariables.DN___5_5_6_0_2_1___2_FIELD_NOINPUTCOUNT,
			IProjectVariables.DN___5_5_6_0_2_1___2_FIELD_NOMATCHCOUNT,
			IProjectVariables.DN___5_5_6_0_2_1___2_FIELD_UTTERANCE,
			IProjectVariables.DN___5_5_6_0_2_1___2_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DN___5_5_6_0_2_1___2, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.FE__OFFER__PARM__TBL_FIELD_ADJCODE,
			IProjectVariables.FE__OFFER__PARM__TBL_FIELD_ITEM__CODE,
			IProjectVariables.FE__OFFER__PARM__TBL_FIELD_ITEM__PATH,
			IProjectVariables.FE__OFFER__PARM__TBL_FIELD_ITEMAMOUNT,
			IProjectVariables.FE__OFFER__PARM__TBL_FIELD_IVR,
			IProjectVariables.FE__OFFER__PARM__TBL_FIELD_SERVICE__TYPE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.FE__OFFER__PARM__TBL, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.UNTITLED_CALL_INFO_1COPY_FIELD_ANI,
			IProjectVariables.UNTITLED_CALL_INFO_1COPY_FIELD_CALLID,
			IProjectVariables.UNTITLED_CALL_INFO_1COPY_FIELD_DNIS,
			IProjectVariables.UNTITLED_CALL_INFO_1COPY_FIELD_STATE,
			IProjectVariables.UNTITLED_CALL_INFO_1COPY_FIELD_STATIONEXTENSION,
			IProjectVariables.UNTITLED_CALL_INFO_1COPY_FIELD_UCID,
			IProjectVariables.UNTITLED_CALL_INFO_1COPY_FIELD_UUI };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.UNTITLED_CALL_INFO_1COPY, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.S__TID_FIELD_CHANNEL,
			IProjectVariables.S__TID_FIELD_NOD_ID,
			IProjectVariables.S__TID_FIELD_NOD_ID_1,
			IProjectVariables.S__TID_FIELD_START__DATE,
			IProjectVariables.S__TID_FIELD_START__TIME,
			IProjectVariables.S__TID_FIELD_TID };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.S__TID, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.REDIRECTINFO_FIELD_PRESENTATIONINFO,
			IProjectVariables.REDIRECTINFO_FIELD_REASON,
			IProjectVariables.REDIRECTINFO_FIELD_SCREENINGINFO,
			IProjectVariables.REDIRECTINFO_FIELD_URI };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.REDIRECTINFO, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CREATE_CHARGE__OUTPUT_FIELD_LEGACY_CODE,
			IProjectVariables.CREATE_CHARGE__OUTPUT_FIELD_PROCESS_ID,
			IProjectVariables.CREATE_CHARGE__OUTPUT_FIELD_PROCESS_NAME,
			IProjectVariables.CREATE_CHARGE__OUTPUT_FIELD_RESERVED_1,
			IProjectVariables.CREATE_CHARGE__OUTPUT_FIELD_RESERVED_2,
			IProjectVariables.CREATE_CHARGE__OUTPUT_FIELD_RESERVED_3,
			IProjectVariables.CREATE_CHARGE__OUTPUT_FIELD_RETURN_CODE,
			IProjectVariables.CREATE_CHARGE__OUTPUT_FIELD_RETURN_MESG,
			IProjectVariables.CREATE_CHARGE__OUTPUT_FIELD_STATUS };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CREATE_CHARGE__OUTPUT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__CELL__NUM,
			IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__CHANNEL,
			IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__DATE,
			IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__ENDTIME,
			IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__IN__ENTERPRISE,
			IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__IN__VDN,
			IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__INDX,
			IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__L_1,
			IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__L_1_0,
			IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__L_2,
			IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__L_3,
			IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__L_4,
			IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__L_5,
			IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__L_6,
			IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__L_7,
			IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__L_8,
			IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__L_9,
			IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__LANG,
			IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__NODE__ID,
			IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__OUT__VDN,
			IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__STARTTIME,
			IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_COUNT };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.G__IVR__DONATE__TRAN_FIELD_BUSINESS__ENTITY,
			IProjectVariables.G__IVR__DONATE__TRAN_FIELD_CYCLY__DATE,
			IProjectVariables.G__IVR__DONATE__TRAN_FIELD_DONATE__AMT,
			IProjectVariables.G__IVR__DONATE__TRAN_FIELD_DONATE__CD,
			IProjectVariables.G__IVR__DONATE__TRAN_FIELD_DONATE__DATE,
			IProjectVariables.G__IVR__DONATE__TRAN_FIELD_MSISDN };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.G__IVR__DONATE__TRAN, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__INPUT_FIELD_CHANNEL_FOR_CFG,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__INPUT_FIELD_CHANNEL_ID,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__INPUT_FIELD_FLOW_NAME,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__INPUT_FIELD_ID_NUMBER,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__INPUT_FIELD_ID_TYPE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__INPUT_FIELD_PASSWORD,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__INPUT_FIELD_REQUESTER_LOCALE,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__INPUT_FIELD_REQUESTER_NAME,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__INPUT_FIELD_REQUEST_ID,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__INPUT_FIELD_TRANS_BP_ID,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__INPUT_FIELD_TRANS_CHANNEL_ID,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__INPUT_FIELD_TRANS_PATH,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__INPUT_FIELD_TRANS_SUB_CHANNEL,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__INPUT_FIELD_TRANS_USER_ID,
			IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__INPUT_FIELD_USER_ID };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.GET_CONTRACT_BY_ACCOUNT_ID_OR_SUBSCRIBER_ID__INPUT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CREATE_TXN__OUTPUT_FIELD_EXCEPTION,
			IProjectVariables.CREATE_TXN__OUTPUT_FIELD_PROCESS_ID,
			IProjectVariables.CREATE_TXN__OUTPUT_FIELD_PROCESS_NAME,
			IProjectVariables.CREATE_TXN__OUTPUT_FIELD_RETURN_CODE,
			IProjectVariables.CREATE_TXN__OUTPUT_FIELD_RETURN_MESG,
			IProjectVariables.CREATE_TXN__OUTPUT_FIELD_TXN_ID };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CREATE_TXN__OUTPUT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.S__DB__API_FIELD_ACCOUNT,
			IProjectVariables.S__DB__API_FIELD_JNDINAME,
			IProjectVariables.S__DB__API_FIELD_METHOD,
			IProjectVariables.S__DB__API_FIELD_PASSWORD,
			IProjectVariables.S__DB__API_FIELD_RESPONSE_JSON_OBJECT,
			IProjectVariables.S__DB__API_FIELD_SQL,
			IProjectVariables.S__DB__API_FIELD_TABLE,
			IProjectVariables.S__DB__API_FIELD_UNTITLED };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.S__DB__API, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DATE_FIELD_AUDIO,
			IProjectVariables.DATE_FIELD_DAYOFMONTH,
			IProjectVariables.DATE_FIELD_DAYOFWEEK,
			IProjectVariables.DATE_FIELD_DAYOFWEEKNUM,
			IProjectVariables.DATE_FIELD_DAYOFYEAR,
			IProjectVariables.DATE_FIELD_MONTH,
			IProjectVariables.DATE_FIELD_MONTHINYEAR,
			IProjectVariables.DATE_FIELD_YEAR };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DATE, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CUMULATIVE__COUNT_FIELD_CUMULATIVE_MARK };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CUMULATIVE__COUNT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CH__CIE_FIELD_BOTTON,
			IProjectVariables.CH__CIE_FIELD_CIE,
			IProjectVariables.CH__CIE_FIELD_CIE__CREATE__ERROR,
			IProjectVariables.CH__CIE_FIELD_CIE__RECORD__ERROR,
			IProjectVariables.CH__CIE_FIELD_CIEDETAILID,
			IProjectVariables.CH__CIE_FIELD_CIEID,
			IProjectVariables.CH__CIE_FIELD_SUBSCRIBERCONTACTID };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CH__CIE, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.S__USERDATACOPY_FIELD_ACTIVE____DATE,
			IProjectVariables.S__USERDATACOPY_FIELD_ANI,
			IProjectVariables.S__USERDATACOPY_FIELD_BIRTHDAY,
			IProjectVariables.S__USERDATACOPY_FIELD_BPID,
			IProjectVariables.S__USERDATACOPY_FIELD_BUSINESS_ENTITY_NUMBER,
			IProjectVariables.S__USERDATACOPY_FIELD_CHANNEL_FOR_CFG,
			IProjectVariables.S__USERDATACOPY_FIELD_CHENNEL,
			IProjectVariables.S__USERDATACOPY_FIELD_CITIZENSHIPTYPE,
			IProjectVariables.S__USERDATACOPY_FIELD_DNIS,
			IProjectVariables.S__USERDATACOPY_FIELD_FLC__OFFER__ID,
			IProjectVariables.S__USERDATACOPY_FIELD_FLOW_NAME,
			IProjectVariables.S__USERDATACOPY_FIELD_ID__TYPE,
			IProjectVariables.S__USERDATACOPY_FIELD_IDENTIFIER,
			IProjectVariables.S__USERDATACOPY_FIELD_NEXTVAL,
			IProjectVariables.S__USERDATACOPY_FIELD_OUT__VDN,
			IProjectVariables.S__USERDATACOPY_FIELD_PAYMENT_CATEGORY,
			IProjectVariables.S__USERDATACOPY_FIELD_PHONENUMBER,
			IProjectVariables.S__USERDATACOPY_FIELD_SUB__TYPE,
			IProjectVariables.S__USERDATACOPY_FIELD_SUBSCRIBER__NO,
			IProjectVariables.S__USERDATACOPY_FIELD_UCID,
			IProjectVariables.S__USERDATACOPY_FIELD_UUI };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.S__USERDATACOPY, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CH__TID_FIELD_CHANNEL,
			IProjectVariables.CH__TID_FIELD_TID };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CH__TID, variableFields, null, session, false, false );
		session.putVariable(variable);
	}
	/**
	 * This method returns the name of the application.
	 * Last generated by Orchestration Designer at: 2024年11月15日 下午02時18分45秒
	 */
	public String getEntryName() {
		return("FET_0809000811");
	}
	/**
	 * This method returns a list of life cycle classes for Pluggable Connectors.
	 * Last generated by Orchestration Designer at: 2024年11月15日 下午02時18分45秒
	 */
	public java.util.Collection getPluggableLifeCycle() {
		java.util.ArrayList result = new java.util.ArrayList();
		result.add("com.avaya.vp.admin.variables.runtime.Initializer");
		result.add("com.avaya.sce.runtime.connectivity.cti.pdc.CTIConnectorInit");
		return(result);
	}
	/**
	 * This method returns a list of VXML contributor classes for Pluggable Connectors.
	 * Last generated by Orchestration Designer at: 2024年11月15日 下午02時18分45秒
	 */
	public java.util.Collection getPluggableVXMLContrib() {
		java.util.ArrayList result = new java.util.ArrayList();
		return(result);
	}
	/**
	 * This method returns the root document for the application.
	 * This method is generated automatically and should not be modified
	 * because changes may be overwritten by future code generation.
	 * Last generated by Orchestration Designer at: 2024年11月15日 下午02時18分45秒
	 */
	public String getRootDoc() {
		return("AppRoot");
	}
	/**
	 * Builds the list of input parameters that are defined for this application 
	 * entry.  This list is built automatically by adding Input Parameter
	 * nodes to AppRoot in the call flow editor.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.
	 *
	 * @return a Collection of <code>java.lang.String</code> objects that
	 * are the names of parameters the application is expecting.
	 * If the AppRoot node does not have any input parameters, then 
	 * this returns an empty list
	 * Last generated by Orchestration Designer at: 2024年11月15日 下午02時18分45秒
	 */
	public java.util.Collection getInputParams(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		list = new java.util.ArrayList();

		return list;
	}
	/**
	 * Builds the list of capture expression that are defined for this application 
	 * entry.  This list is built automatically by adding Capture Expression
	 * items to AppRoot in the call flow editor.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.
	 *
	 * @return a Collection of <code>CaptureExpression</code> objects that
	 * specify the ECMA script expression and the Orchestration Designer 
	 * session variable that will store the captured result.
	 * If the AppRoot node does not have any capture expression items, then 
	 * this returns an empty list
	 * Last generated by Orchestration Designer at: 2024年11月15日 下午02時18分45秒
	 */
	public java.util.Collection getCaptureExpressions(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		list = new java.util.ArrayList();

		return list;
	}
	/**
	 * This method returns a boolean to indicate if the approot node has a web page to show.
	 * This method is generated automatically and should not be modified
	 * because changes may be overwritten by future code generation.
	 * Last generated by Orchestration Designer at: 2024年11月15日 下午02時18分45秒
	 */
	public boolean hasWebPage(com.avaya.sce.runtimecommon.SCESession mySession) {
		return false;
	}
}
