package flow.subflow.insert_AIR_MENU_TBL;

import com.avaya.sce.runtimecommon.IComplexVariable;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.IVariable;
import com.avaya.sce.runtimecommon.IVariableField;

import flow.IProjectVariables;

/**
 * A basic servlet which allows a user to define their code, generate
 * any output, and to select where to transition to next.
 * Last generated by Orchestration Designer at: 2017年8月29日 下午06時46分46秒
 */
public class insert_AIR_MENU_TBL extends com.avaya.sce.runtime.BasicServlet {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2017年8月29日 下午06時46分46秒
	 */
	public insert_AIR_MENU_TBL() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method allows for custom integration with other Java components.
	 * You may use Java for sophisticated logic or to integrate with custom
	 * connectors (i.e. JMS, custom web services, sockets, XML, JAXB, etc.)
	 *
	 * Any custom code added here should work as efficiently as possible to prevent delays.
	 * It's important to design your callflow so that the voice browser (Voice Portal/IR)
	 * is not waiting too long for a response as this can lead to a poor caller experience.
	 * Additionally, if the response to the client voice browser exceeds the configured
	 * timeout, the platform may throw an "error.badfetch". 
	 *
	 * Using this method, you have access to all session variables through the 
	 * SCESession object.
	 *
	 * The code generator will *** NOT *** overwrite this method in the future.
	 * Last generated by Orchestration Designer at: 2017年8月29日 下午06時46分46秒
	 */
	public void servletImplementation(com.avaya.sce.runtimecommon.SCESession mySession) {

		
		IVariable TIDVarible = mySession.getVariable(IProjectVariables.S__TID);
		IComplexVariable complexTID = TIDVarible.getComplexVariable();
		IVariableField TIDfield = complexTID.getField(IProjectVariables.S__TID_FIELD_TID);
		String TID = TIDfield.getStringValue();

		IVariable userdata_Varible = mySession.getVariable(IProjectVariables.S__USERDATA);
		IComplexVariable userdata_complex = userdata_Varible.getComplexVariable();
		
		//VDN
		IVariableField dnis_field = userdata_complex.getField(IProjectVariables.S__USERDATA_FIELD_DNIS);
		String dnis = dnis_field.getStringValue();
		
		mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO, "dnis Response:" + dnis);
		
		if(dnis.equals("49913")||dnis.equals("80437039913")||dnis.equals("437039913")||dnis.equals("2149913")||dnis.equals("2011136")||dnis.equals("21136")){

			String insert_AIR_55135_MENU_TBL = "insert AIR_55135_MENU_TBL";
			String Table_55135 = "AIR_55135_MENU_TBL";
			
			IVariable air55135_Varible = mySession.getVariable(IProjectVariables.AIR___5_5_1_3_5__MENU__TBL);
			IComplexVariable air55135_complex = air55135_Varible.getComplexVariable();
			//手機號碼
			IVariableField cellNum_field = air55135_complex.getField(IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__CELL__NUM);
			String cellNum = cellNum_field.getStringValue();		
			
			IVariableField nodeID_field = air55135_complex.getField(IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__NODE__ID);
			String nodeID = nodeID_field.getStringValue();

			IVariableField index_field = air55135_complex.getField(IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__INDX);
			String index = index_field.getStringValue();

			IVariableField date_field = air55135_complex.getField(IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__DATE);
			String date = date_field.getStringValue();
			
			IVariableField startTime_field = air55135_complex.getField(IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__STARTTIME);
			String startTime = startTime_field.getStringValue();
			
			IVariableField endTime_field = air55135_complex.getField(IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__ENDTIME);
			String endTime = endTime_field.getStringValue();
			
			IVariableField l1_field = air55135_complex.getField(IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__L_1);
			String l1 = l1_field.getStringValue();
			
			IVariableField l2_field = air55135_complex.getField(IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__L_2);
			String l2 = l2_field.getStringValue();
			
			IVariableField l3_field = air55135_complex.getField(IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__L_3);
			String l3 = l3_field.getStringValue();
			
			IVariableField l4_field = air55135_complex.getField(IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__L_4);
			String l4 = l4_field.getStringValue();
			
			IVariableField l5_field = air55135_complex.getField(IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__L_5);
			String l5 = l5_field.getStringValue();
			
			IVariableField l6_field = air55135_complex.getField(IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__L_6);
			String l6 = l6_field.getStringValue();
			
			IVariableField l7_field = air55135_complex.getField(IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__L_7);
			String l7 = l7_field.getStringValue();
			
			IVariableField l8_field = air55135_complex.getField(IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__L_8);
			String l8 = l8_field.getStringValue();
			
			IVariableField l9_field = air55135_complex.getField(IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__L_9);
			String l9 = l9_field.getStringValue();

			IVariableField l10_field = air55135_complex.getField(IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__L_1_0);
			String l10 = l10_field.getStringValue();

			IVariableField strLog_field = air55135_complex.getField(IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__STR__LOG);
			String strLog = strLog_field.getStringValue();
			
			IVariableField callType_field = air55135_complex.getField(IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__CALL__TYPE);
			String callType = callType_field.getStringValue();
			//dnis
			IVariableField inVDN_field = air55135_complex.getField(IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__IN__VDN);
			String inVDN = inVDN_field.getStringValue();
			
			IVariableField outVDN_field = air55135_complex.getField(IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__OUT__VDN);
			String outVDN = outVDN_field.getStringValue();
			
			IVariableField enterprise_field = air55135_complex.getField(IProjectVariables.AIR___5_5_1_3_5__MENU__TBL_FIELD_AIR___5_5_1_3_5__MENU__IN__ENTERPRISE);
			String enterprise = enterprise_field.getStringValue();
			
			String SQL = "insert into air_55135_menu_tbl values('"+ cellNum +"','"+ nodeID +"','"+ index +"','"+ date +"','"+ startTime +"','"+ endTime +"','1','"+ l1 +"','"+ l2 +"','"+ l3 +"','"+ l4 +"','"+ l5 +"','"+ l6 +"','"+ l7 +"','"+ l8 +"','"+ l9 +"','"+ l10 +"','"+ strLog +"','"+ callType +"','"+ inVDN +"','"+ outVDN +"','"+ enterprise +"')";
			
			IVariableField SQL_varible = mySession.getVariableField(
					IProjectVariables.S__DB__API,
					IProjectVariables.S__DB__API_FIELD_SQL);
			SQL_varible.setValue(SQL);
			mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO, "SQL Response(TID:["+TID+"]"+insert_AIR_55135_MENU_TBL+"):" +SQL);
	
	
			IVariableField Table_varible = mySession.getVariableField(
					IProjectVariables.S__DB__API,
					IProjectVariables.S__DB__API_FIELD_TABLE);
			Table_varible.setValue(Table_55135);
			mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO, "Table Response(TID:["+TID+"]"+insert_AIR_55135_MENU_TBL+"):" +Table_55135);


		}else if(dnis.equals("80437039380")||dnis.equals("49380")||dnis.equals("2149380")||dnis.equals("2011137")||dnis.equals("21137")){

			String insert_AIR_380_MENU_TBL = "insert AIR_380_MENU_TBL";
			String Table_380 = "AIR_380_MENU_TBL";
			
			IVariable air380_Varible = mySession.getVariable(IProjectVariables.AIR___3_8_0__MENU__TBL);
			IComplexVariable air380_complex = air380_Varible.getComplexVariable();
			//手機號碼
			IVariableField cellNum_field = air380_complex.getField(IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__CELL__NUM);
			String cellNum = cellNum_field.getStringValue();		
			
			IVariableField nodeID_field = air380_complex.getField(IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__NODE__ID);
			String nodeID = nodeID_field.getStringValue();

			IVariableField index_field = air380_complex.getField(IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__INDX);
			String index = index_field.getStringValue();

			IVariableField date_field = air380_complex.getField(IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__DATE);
			String date = date_field.getStringValue();
			
			IVariableField startTime_field = air380_complex.getField(IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__STARTTIME);
			String startTime = startTime_field.getStringValue();
			
			IVariableField endTime_field = air380_complex.getField(IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__ENDTIME);
			String endTime = endTime_field.getStringValue();
			
			IVariableField l1_field = air380_complex.getField(IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__L_1);
			String l1 = l1_field.getStringValue();
			
			IVariableField l2_field = air380_complex.getField(IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__L_2);
			String l2 = l2_field.getStringValue();
			
			IVariableField l3_field = air380_complex.getField(IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__L_3);
			String l3 = l3_field.getStringValue();
			
			IVariableField l4_field = air380_complex.getField(IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__L_4);
			String l4 = l4_field.getStringValue();
			
			IVariableField l5_field = air380_complex.getField(IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__L_5);
			String l5 = l5_field.getStringValue();
			
			IVariableField l6_field = air380_complex.getField(IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__L_6);
			String l6 = l6_field.getStringValue();
			
			IVariableField l7_field = air380_complex.getField(IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__L_7);
			String l7 = l7_field.getStringValue();
			
			IVariableField l8_field = air380_complex.getField(IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__L_8);
			String l8 = l8_field.getStringValue();
			
			IVariableField l9_field = air380_complex.getField(IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__L_9);
			String l9 = l9_field.getStringValue();

			IVariableField l10_field = air380_complex.getField(IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__L_1_0);
			String l10 = l10_field.getStringValue();

			IVariableField strLog_field = air380_complex.getField(IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__STR__LOG);
			String strLog = strLog_field.getStringValue();
			
			IVariableField callType_field = air380_complex.getField(IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__CALL__TYPE);
			String callType = callType_field.getStringValue();
			//dnis
			IVariableField inVDN_field = air380_complex.getField(IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__IN__VDN);
			String inVDN = inVDN_field.getStringValue();
			
			IVariableField outVDN_field = air380_complex.getField(IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__OUT__VDN);
			String outVDN = outVDN_field.getStringValue();
			
			IVariableField enterprise_field = air380_complex.getField(IProjectVariables.AIR___3_8_0__MENU__TBL_FIELD_AIR___3_8_0__MENU__IN__ENTERPRISE);
			String enterprise = enterprise_field.getStringValue();
			
			String SQL = "insert into air_380_menu_tbl values('"+ cellNum +"','"+ nodeID +"','"+ index +"','"+ date +"','"+ startTime +"','"+ endTime +"','1','"+ l1 +"','"+ l2 +"','"+ l3 +"','"+ l4 +"','"+ l5 +"','"+ l6 +"','"+ l7 +"','"+ l8 +"','"+ l9 +"','"+ l10 +"','"+ strLog +"','"+ callType +"','"+ inVDN +"','"+ outVDN +"','"+ enterprise +"')";
			
			IVariableField SQL_varible = mySession.getVariableField(
					IProjectVariables.S__DB__API,
					IProjectVariables.S__DB__API_FIELD_SQL);
			SQL_varible.setValue(SQL);
			mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO, "SQL Response(TID:["+TID+"]"+insert_AIR_380_MENU_TBL+"):" +SQL);
	
			IVariableField Table_varible = mySession.getVariableField(
					IProjectVariables.S__DB__API,
					IProjectVariables.S__DB__API_FIELD_TABLE);
			Table_varible.setValue(Table_380);
			mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO, "Table Response(TID:["+TID+"]"+insert_AIR_380_MENU_TBL+"):" +Table_380);

			
		}else if(dnis.equals("49467")||dnis.equals("80437039467")||dnis.equals("437039467")||dnis.equals("2149467")){

			String insert_AIR_591939_MENU_TBL = "insert AIR_591939_MENU_TBL";
			String Table_591939 = "AIR_591939_MENU_TBL";
			
			IVariable air591939_Varible = mySession.getVariable(IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL);
			IComplexVariable air591939_complex = air591939_Varible.getComplexVariable();
			//手機號碼
			IVariableField cellNum_field = air591939_complex.getField(IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__CELL__NUM);
			String cellNum = cellNum_field.getStringValue();		
			
			IVariableField nodeID_field = air591939_complex.getField(IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__NODE__ID);
			String nodeID = nodeID_field.getStringValue();

			IVariableField index_field = air591939_complex.getField(IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__INDX);
			String index = index_field.getStringValue();

			IVariableField date_field = air591939_complex.getField(IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__DATE);
			String date = date_field.getStringValue();
			
			IVariableField startTime_field = air591939_complex.getField(IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__STARTTIME);
			String startTime = startTime_field.getStringValue();
			
			IVariableField endTime_field = air591939_complex.getField(IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__ENDTIME);
			String endTime = endTime_field.getStringValue();
			
			IVariableField l1_field = air591939_complex.getField(IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__L_1);
			String l1 = l1_field.getStringValue();
			
			IVariableField l2_field = air591939_complex.getField(IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__L_2);
			String l2 = l2_field.getStringValue();
			
			IVariableField l3_field = air591939_complex.getField(IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__L_3);
			String l3 = l3_field.getStringValue();
			
			IVariableField l4_field = air591939_complex.getField(IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__L_4);
			String l4 = l4_field.getStringValue();
			
			IVariableField l5_field = air591939_complex.getField(IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__L_5);
			String l5 = l5_field.getStringValue();
			
			IVariableField l6_field = air591939_complex.getField(IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__L_6);
			String l6 = l6_field.getStringValue();
			
			IVariableField l7_field = air591939_complex.getField(IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__L_7);
			String l7 = l7_field.getStringValue();
			
			IVariableField l8_field = air591939_complex.getField(IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__L_8);
			String l8 = l8_field.getStringValue();
			
			IVariableField l9_field = air591939_complex.getField(IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__L_9);
			String l9 = l9_field.getStringValue();

			IVariableField l10_field = air591939_complex.getField(IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__L_1_0);
			String l10 = l10_field.getStringValue();

			IVariableField strLog_field = air591939_complex.getField(IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__STR__LOG);
			String strLog = strLog_field.getStringValue();
			
			IVariableField callType_field = air591939_complex.getField(IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__CALL__TYPE);
			String callType = callType_field.getStringValue();
			//dnis
			IVariableField inVDN_field = air591939_complex.getField(IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__IN__VDN);
			String inVDN = inVDN_field.getStringValue();
			
			IVariableField outVDN_field = air591939_complex.getField(IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__OUT__VDN);
			String outVDN = outVDN_field.getStringValue();
			
			IVariableField enterprise_field = air591939_complex.getField(IProjectVariables.AIR___5_9_1_9_3_9__MENU__TBL_FIELD_AIR___5_9_1_9_3_9__MENU__IN__ENTERPRISE);
			String enterprise = enterprise_field.getStringValue();
			
			String SQL = "insert into air_591939_menu_tbl values('"+ cellNum +"','"+ nodeID +"','"+ index +"','"+ date +"','"+ startTime +"','"+ endTime +"','1','"+ l1 +"','"+ l2 +"','"+ l3 +"','"+ l4 +"','"+ l5 +"','"+ l6 +"','"+ l7 +"','"+ l8 +"','"+ l9 +"','"+ l10 +"','"+ strLog +"','"+ callType +"','"+ inVDN +"','"+ outVDN +"','"+ enterprise +"')";
			
			IVariableField SQL_varible = mySession.getVariableField(
					IProjectVariables.S__DB__API,
					IProjectVariables.S__DB__API_FIELD_SQL);
			SQL_varible.setValue(SQL);
			mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO, "SQL Response(TID:["+TID+"]"+insert_AIR_591939_MENU_TBL+"):" + SQL);
	
	
			IVariableField Table_varible = mySession.getVariableField(
					IProjectVariables.S__DB__API,
					IProjectVariables.S__DB__API_FIELD_TABLE);
			Table_varible.setValue(Table_591939);
			mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO, "Table Response(TID:["+TID+"]"+insert_AIR_591939_MENU_TBL+"):" + Table_591939);

			
		}else if(dnis.equals("49470")||dnis.equals("80437039470")||dnis.equals("437039470")||dnis.equals("2149470")){

			String insert_AIR_591980_MENU_TBL = "insert AIR_591980_MENU_TBL";
			String Table_591980 = "AIR_591980_MENU_TBL";
			
			IVariable air591980_Varible = mySession.getVariable(IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL);
			IComplexVariable air591980_complex = air591980_Varible.getComplexVariable();
			//手機號碼
			IVariableField cellNum_field = air591980_complex.getField(IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__CELL__NUM);
			String cellNum = cellNum_field.getStringValue();		
			
			IVariableField nodeID_field = air591980_complex.getField(IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__NODE__ID);
			String nodeID = nodeID_field.getStringValue();

			IVariableField index_field = air591980_complex.getField(IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__INDX);
			String index = index_field.getStringValue();

			IVariableField date_field = air591980_complex.getField(IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__DATE);
			String date = date_field.getStringValue();
			
			IVariableField startTime_field = air591980_complex.getField(IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__STARTTIME);
			String startTime = startTime_field.getStringValue();
			
			IVariableField endTime_field = air591980_complex.getField(IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__ENDTIME);
			String endTime = endTime_field.getStringValue();
			
			IVariableField l1_field = air591980_complex.getField(IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__L_1);
			String l1 = l1_field.getStringValue();
			
			IVariableField l2_field = air591980_complex.getField(IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__L_2);
			String l2 = l2_field.getStringValue();
			
			IVariableField l3_field = air591980_complex.getField(IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__L_3);
			String l3 = l3_field.getStringValue();
			
			IVariableField l4_field = air591980_complex.getField(IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__L_4);
			String l4 = l4_field.getStringValue();
			
			IVariableField l5_field = air591980_complex.getField(IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__L_5);
			String l5 = l5_field.getStringValue();
			
			IVariableField l6_field = air591980_complex.getField(IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__L_6);
			String l6 = l6_field.getStringValue();
			
			IVariableField l7_field = air591980_complex.getField(IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__L_7);
			String l7 = l7_field.getStringValue();
			
			IVariableField l8_field = air591980_complex.getField(IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__L_8);
			String l8 = l8_field.getStringValue();
			
			IVariableField l9_field = air591980_complex.getField(IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__L_9);
			String l9 = l9_field.getStringValue();

			IVariableField l10_field = air591980_complex.getField(IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__L_1_0);
			String l10 = l10_field.getStringValue();

			IVariableField strLog_field = air591980_complex.getField(IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__STR__LOG);
			String strLog = strLog_field.getStringValue();
			
			IVariableField callType_field = air591980_complex.getField(IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__CALL__TYPE);
			String callType = callType_field.getStringValue();
			//dnis
			IVariableField inVDN_field = air591980_complex.getField(IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__IN__VDN);
			String inVDN = inVDN_field.getStringValue();
			
			IVariableField outVDN_field = air591980_complex.getField(IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__OUT__VDN);
			String outVDN = outVDN_field.getStringValue();
			
			IVariableField enterprise_field = air591980_complex.getField(IProjectVariables.AIR___5_9_1_9_8_0__MENU__TBL_FIELD_AIR___5_9_1_9_8_0__MENU__IN__ENTERPRISE);
			String enterprise = enterprise_field.getStringValue();
			
			String SQL = "insert into air_591980_menu_tbl values('"+ cellNum +"','"+ nodeID +"','"+ index +"','"+ date +"','"+ startTime +"','"+ endTime +"','1','"+ l1 +"','"+ l2 +"','"+ l3 +"','"+ l4 +"','"+ l5 +"','"+ l6 +"','"+ l7 +"','"+ l8 +"','"+ l9 +"','"+ l10 +"','"+ strLog +"','"+ callType +"','"+ inVDN +"','"+ outVDN +"','"+ enterprise +"')";
			
			IVariableField SQL_varible = mySession.getVariableField(
					IProjectVariables.S__DB__API,
					IProjectVariables.S__DB__API_FIELD_SQL);
			SQL_varible.setValue(SQL);
			mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO, "SQL Response(TID:["+TID+"]"+insert_AIR_591980_MENU_TBL+"):" + SQL);
	
	
			IVariableField Table_varible = mySession.getVariableField(
					IProjectVariables.S__DB__API,
					IProjectVariables.S__DB__API_FIELD_TABLE);
			Table_varible.setValue(Table_591980);
			mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO, "Table Response(TID:["+TID+"]"+insert_AIR_591980_MENU_TBL+"):" + Table_591980);

			
		}else if(dnis.equals("49469")||dnis.equals("80437039469")||dnis.equals("2149469")){

			String insert_AIR_591933_MENU_TBL = "insert AIR_5919_MENU_TBL";
			String Table_591933 = "AIR_5919_MENU_TBL";
			
			IVariable air591933_Varible = mySession.getVariable(IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL);
			IComplexVariable air591933_complex = air591933_Varible.getComplexVariable();
			//手機號碼
			IVariableField cellNum_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__CELL__NUM);
			String cellNum = cellNum_field.getStringValue();		
			
			IVariableField nodeID_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__NODE__ID);
			String nodeID = nodeID_field.getStringValue();

			IVariableField index_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__INDX);
			String index = index_field.getStringValue();

			IVariableField date_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__DATE);
			String date = date_field.getStringValue();
			
			IVariableField startTime_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__STARTTIME);
			String startTime = startTime_field.getStringValue();
			
			IVariableField endTime_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__ENDTIME);
			String endTime = endTime_field.getStringValue();
			
			IVariableField l1_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__L_1);
			String l1 = l1_field.getStringValue();
			
			IVariableField l2_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__L_2);
			String l2 = l2_field.getStringValue();
			
			IVariableField l3_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__L_3);
			String l3 = l3_field.getStringValue();
			
			IVariableField l4_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__L_4);
			String l4 = l4_field.getStringValue();
			
			IVariableField l5_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__L_5);
			String l5 = l5_field.getStringValue();
			
			IVariableField l6_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__L_6);
			String l6 = l6_field.getStringValue();
			
			IVariableField l7_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__L_7);
			String l7 = l7_field.getStringValue();
			
			IVariableField l8_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__L_8);
			String l8 = l8_field.getStringValue();
			
			IVariableField l9_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__L_9);
			String l9 = l9_field.getStringValue();

			IVariableField l10_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__L_1_0);
			String l10 = l10_field.getStringValue();

			IVariableField strLog_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__STR__LOG);
			String strLog = strLog_field.getStringValue();
			
			IVariableField callType_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__CALL__TYPE);
			String callType = callType_field.getStringValue();
			//dnis
			IVariableField inVDN_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__IN__VDN);
			String inVDN = inVDN_field.getStringValue();
			
			IVariableField outVDN_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__OUT__VDN);
			String outVDN = outVDN_field.getStringValue();
			
			IVariableField enterprise_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_3_3__MENU__TBL_FIELD_AIR___5_9_1_9_3_3__MENU__IN__ENTERPRISE);
			String enterprise = enterprise_field.getStringValue();
			
			String SQL = "insert into air_5919_menu_tbl values('"+ cellNum +"','"+ nodeID +"','"+ index +"','"+ date +"','"+ startTime +"','"+ endTime +"','1','"+ l1 +"','"+ l2 +"','"+ l3 +"','"+ l4 +"','"+ l5 +"','"+ l6 +"','"+ l7 +"','"+ l8 +"','"+ l9 +"','"+ l10 +"','"+ strLog +"','"+ callType +"','"+ inVDN +"','"+ outVDN +"','"+ enterprise +"')";
			
			IVariableField SQL_varible = mySession.getVariableField(
					IProjectVariables.S__DB__API,
					IProjectVariables.S__DB__API_FIELD_SQL);
			SQL_varible.setValue(SQL);
			mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO, "SQL Response(TID:["+TID+"]"+insert_AIR_591933_MENU_TBL+"):" + SQL);
	
	
			IVariableField Table_varible = mySession.getVariableField(
					IProjectVariables.S__DB__API,
					IProjectVariables.S__DB__API_FIELD_TABLE);
			Table_varible.setValue(Table_591933);
			mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO, "Table Response(TID:["+TID+"]"+insert_AIR_591933_MENU_TBL+"):" + Table_591933);
		
		
		}else if(dnis.equals("49465")||dnis.equals("80437039465")||dnis.equals("437039465")||dnis.equals("2149465")){

			String insert_AIR_591993_MENU_TBL = "insert AIR_591993_MENU_TBL";
			String Table_591993 = "AIR_591993_MENU_TBL";
			
			IVariable air591933_Varible = mySession.getVariable(IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL);
			IComplexVariable air591933_complex = air591933_Varible.getComplexVariable();
			//手機號碼
			IVariableField cellNum_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__CELL__NUM);
			String cellNum = cellNum_field.getStringValue();		
			
			IVariableField nodeID_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__NODE__ID);
			String nodeID = nodeID_field.getStringValue();

			IVariableField index_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__INDX);
			String index = index_field.getStringValue();

			IVariableField date_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__DATE);
			String date = date_field.getStringValue();
			
			IVariableField startTime_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__STARTTIME);
			String startTime = startTime_field.getStringValue();
			
			IVariableField endTime_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__ENDTIME);
			String endTime = endTime_field.getStringValue();
			
			IVariableField l1_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__L_1);
			String l1 = l1_field.getStringValue();
			
			IVariableField l2_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__L_2);
			String l2 = l2_field.getStringValue();
			
			IVariableField l3_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__L_3);
			String l3 = l3_field.getStringValue();
			
			IVariableField l4_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__L_4);
			String l4 = l4_field.getStringValue();
			
			IVariableField l5_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__L_5);
			String l5 = l5_field.getStringValue();
			
			IVariableField l6_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__L_6);
			String l6 = l6_field.getStringValue();
			
			IVariableField l7_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__L_7);
			String l7 = l7_field.getStringValue();
			
			IVariableField l8_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__L_8);
			String l8 = l8_field.getStringValue();
			
			IVariableField l9_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__L_9);
			String l9 = l9_field.getStringValue();

			IVariableField l10_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__L_1_0);
			String l10 = l10_field.getStringValue();

//			IVariableField strLog_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__STR__LOG);
//			String strLog = strLog_field.getStringValue();
//			
//			IVariableField callType_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__CALL__TYPE);
//			String callType = callType_field.getStringValue();
			//dnis
			IVariableField inVDN_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__IN__VDN);
			String inVDN = inVDN_field.getStringValue();
			
			IVariableField outVDN_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__OUT__VDN);
			String outVDN = outVDN_field.getStringValue();
			
			IVariableField enterprise_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_3__MENU__TBL_FIELD_AIR___5_9_1_9_9_3__MENU__IN__ENTERPRISE);
			String enterprise = enterprise_field.getStringValue();
			
			String SQL = "insert into STI.air_591993_menu_tbl values('"+ cellNum +"','"+ nodeID +"','"+ index +"','"+ date +"','"+ startTime +"','"+ endTime +"','1','"+ l1 +"','"+ l2 +"','"+ l3 +"','"+ l4 +"','"+ l5 +"','"+ l6 +"','"+ l7 +"','"+ l8 +"','"+ l9 +"','"+ l10 +"','"+ inVDN +"','"+ outVDN +"','"+ enterprise +"')";
			
			IVariableField SQL_varible = mySession.getVariableField(
					IProjectVariables.S__DB__API,
					IProjectVariables.S__DB__API_FIELD_SQL);
			SQL_varible.setValue(SQL);
			mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO, "SQL Response(TID:["+TID+"]"+insert_AIR_591993_MENU_TBL+"):" + SQL);
	
	
			IVariableField Table_varible = mySession.getVariableField(
					IProjectVariables.S__DB__API,
					IProjectVariables.S__DB__API_FIELD_TABLE);
			Table_varible.setValue(Table_591993);
			mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO, "Table Response(TID:["+TID+"]"+insert_AIR_591993_MENU_TBL+"):" + Table_591993);
		
			
			
		}else if(dnis.equals("49452")||dnis.equals("80437039452")||dnis.equals("437039452")||dnis.equals("2149452")){

			String insert_AIR_591999_MENU_TBL = "insert AIR_591999_MENU_TBL";
			String Table_591999 = "AIR_591999_MENU_TBL";

			IVariable air591933_Varible = mySession.getVariable(IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL);
			IComplexVariable air591933_complex = air591933_Varible.getComplexVariable();
			//手機號碼
			IVariableField cellNum_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__CELL__NUM);
			String cellNum = cellNum_field.getStringValue();		
			
			IVariableField nodeID_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__NODE__ID);
			String nodeID = nodeID_field.getStringValue();

			IVariableField index_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__INDX);
			String index = index_field.getStringValue();

			IVariableField date_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__DATE);
			String date = date_field.getStringValue();
			
			IVariableField startTime_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__STARTTIME);
			String startTime = startTime_field.getStringValue();
			
			IVariableField endTime_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__ENDTIME);
			String endTime = endTime_field.getStringValue();
			
			IVariableField l1_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__L_1);
			String l1 = l1_field.getStringValue();
			
			IVariableField l2_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__L_2);
			String l2 = l2_field.getStringValue();
			
			IVariableField l3_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__L_3);
			String l3 = l3_field.getStringValue();
			
			IVariableField l4_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__L_4);
			String l4 = l4_field.getStringValue();
			
			IVariableField l5_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__L_5);
			String l5 = l5_field.getStringValue();
			
			IVariableField l6_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__L_6);
			String l6 = l6_field.getStringValue();
			
			IVariableField l7_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__L_7);
			String l7 = l7_field.getStringValue();
			
			IVariableField l8_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__L_8);
			String l8 = l8_field.getStringValue();
			
			IVariableField l9_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__L_9);
			String l9 = l9_field.getStringValue();

			IVariableField l10_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__L_1_0);
			String l10 = l10_field.getStringValue();

//			IVariableField strLog_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__STR__LOG);
//			String strLog = strLog_field.getStringValue();
//			
//			IVariableField callType_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__CALL__TYPE);
//			String callType = callType_field.getStringValue();
			//dnis
			IVariableField inVDN_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__IN__VDN);
			String inVDN = inVDN_field.getStringValue();
			
			IVariableField outVDN_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__OUT__VDN);
			String outVDN = outVDN_field.getStringValue();
			
			IVariableField enterprise_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_9_9__MENU__TBL_FIELD_AIR___5_9_1_9_9_9__MENU__IN__ENTERPRISE);
			String enterprise = enterprise_field.getStringValue();
			
			String SQL = "insert into STI.AIR_591999_MENU_TBL values('"+ cellNum +"','"+ nodeID +"','"+ index +"','"+ date +"','"+ startTime +"','"+ endTime +"','1','"+ l1 +"','"+ l2 +"','"+ l3 +"','"+ l4 +"','"+ l5 +"','"+ l6 +"','"+ l7 +"','"+ l8 +"','"+ l9 +"','"+ l10 +"','"+ inVDN +"','"+ outVDN +"','"+ enterprise +"')";
			
			IVariableField SQL_varible = mySession.getVariableField(
					IProjectVariables.S__DB__API,
					IProjectVariables.S__DB__API_FIELD_SQL);
			SQL_varible.setValue(SQL);
			mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO, "SQL Response(TID:["+TID+"]"+insert_AIR_591999_MENU_TBL+"):" + SQL);
	
	
			IVariableField Table_varible = mySession.getVariableField(
					IProjectVariables.S__DB__API,
					IProjectVariables.S__DB__API_FIELD_TABLE);
			Table_varible.setValue(Table_591999);
			mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO, "Table Response(TID:["+TID+"]"+insert_AIR_591999_MENU_TBL+"):" + Table_591999);
		
	
			
		}else if(dnis.equals("49453")||dnis.equals("80437039453")||dnis.equals("437039453")||dnis.equals("2149453")){

			String insert_AIR_591919_MENU_TBL = "insert AIR_591919_MENU_TBL";
			String Table_591919 = "AIR_591919_MENU_TBL";

			IVariable air591933_Varible = mySession.getVariable(IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL);
			IComplexVariable air591933_complex = air591933_Varible.getComplexVariable();
			//手機號碼
			IVariableField cellNum_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__CELL__NUM);
			String cellNum = cellNum_field.getStringValue();		
			
			IVariableField nodeID_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__NODE__ID);
			String nodeID = nodeID_field.getStringValue();

			IVariableField index_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__INDX);
			String index = index_field.getStringValue();

			IVariableField date_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__DATE);
			String date = date_field.getStringValue();
			
			IVariableField startTime_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__STARTTIME);
			String startTime = startTime_field.getStringValue();
			
			IVariableField endTime_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__ENDTIME);
			String endTime = endTime_field.getStringValue();
			
			IVariableField l1_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__L_1);
			String l1 = l1_field.getStringValue();
			
			IVariableField l2_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__L_2);
			String l2 = l2_field.getStringValue();
			
			IVariableField l3_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__L_3);
			String l3 = l3_field.getStringValue();
			
			IVariableField l4_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__L_4);
			String l4 = l4_field.getStringValue();
			
			IVariableField l5_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__L_5);
			String l5 = l5_field.getStringValue();
			
			IVariableField l6_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__L_6);
			String l6 = l6_field.getStringValue();
			
			IVariableField l7_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__L_7);
			String l7 = l7_field.getStringValue();
			
			IVariableField l8_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__L_8);
			String l8 = l8_field.getStringValue();
			
			IVariableField l9_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__L_9);
			String l9 = l9_field.getStringValue();

			IVariableField l10_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__L_1_0);
			String l10 = l10_field.getStringValue();

//			IVariableField strLog_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__STR__LOG);
//			String strLog = strLog_field.getStringValue();
//			
//			IVariableField callType_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__CALL__TYPE);
//			String callType = callType_field.getStringValue();
			//dnis
			IVariableField inVDN_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__IN__VDN);
			String inVDN = inVDN_field.getStringValue();
			
			IVariableField outVDN_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__OUT__VDN);
			String outVDN = outVDN_field.getStringValue();
			
			IVariableField enterprise_field = air591933_complex.getField(IProjectVariables.AIR___5_9_1_9_1_9__MENU__TBL_FIELD_AIR___5_9_1_9_1_9__MENU__IN__ENTERPRISE);
			String enterprise = enterprise_field.getStringValue();
			
			String SQL = "insert into STI.AIR_591919_MENU_TBL values('"+ cellNum +"','"+ nodeID +"','"+ index +"','"+ date +"','"+ startTime +"','"+ endTime +"','1','"+ l1 +"','"+ l2 +"','"+ l3 +"','"+ l4 +"','"+ l5 +"','"+ l6 +"','"+ l7 +"','"+ l8 +"','"+ l9 +"','"+ l10 +"','"+ inVDN +"','"+ outVDN +"','"+ enterprise +"')";
			
			IVariableField SQL_varible = mySession.getVariableField(
					IProjectVariables.S__DB__API,
					IProjectVariables.S__DB__API_FIELD_SQL);
			SQL_varible.setValue(SQL);
			mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO, "SQL Response(TID:["+TID+"]"+insert_AIR_591919_MENU_TBL+"):" + SQL);
	
	
			IVariableField Table_varible = mySession.getVariableField(
					IProjectVariables.S__DB__API,
					IProjectVariables.S__DB__API_FIELD_TABLE);
			Table_varible.setValue(Table_591919);
			mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO, "Table Response(TID:["+TID+"]"+insert_AIR_591919_MENU_TBL+"):" + Table_591919);
		
			
		}else{
		};
			

	}
	/**
	 * Builds the list of branches that are defined for this servlet object.
	 * This list is built automatically by defining Goto nodes in the call flow editor.
	 * It is the programmer's responsibilty to provide at least one enabled Goto.<BR>
	 *
	 * The user should override updateBranches() to determine which Goto that the
	 * framework will activate.  If there is not at least one enabled Goto item, 
	 * the framework will throw a runtime exception.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.  To modify the list
	 * of branches for the flow item, override:
	 *     <code>updateBranches(Collection branches, SCESession mySession)</code>
	 *
	 * @return a Collection of <code>com.avaya.sce.runtime.Goto</code>
	 * objects that will be evaluated at runtime.  If there are no gotos
	 * defined in the Servlet node, then this returns null.
	 * Last generated by Orchestration Designer at: 2024年11月20日 上午11時22分38秒
	 */
	public java.util.Collection getBranches(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		com.avaya.sce.runtime.Goto aGoto = null;
		list = new java.util.ArrayList(1);

		aGoto = new com.avaya.sce.runtime.Goto("insert_AIR_MENU_TBL-CF_insetDBAPI", 0, true, "Default");
		list.add(aGoto);

		return list;
	}
}
