package flow.subflow.CF_Menulog;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2018年6月6日 下午02時43分44秒
 */
public class check_button extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2018年6月6日 下午02時43分44秒
	 */
	public check_button() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2024年11月12日 上午09時43分43秒
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = null;
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2024年11月12日 上午09時43分43秒
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2024年11月12日 上午09時43分43秒
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		com.avaya.sce.runtime.BooleanOperation bo1 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
		com.avaya.sce.runtime.Expression be1 = new com.avaya.sce.runtime.Expression("expression1", "AIR_380_MENU_TBL:AIR_380_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo1.addExpression(be1);
		com.avaya.sce.runtime.Expression be2 = new com.avaya.sce.runtime.Expression("expression2", "AIR_55135_MENU_TBL:AIR_55135_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo1.addExpression(be2);
		com.avaya.sce.runtime.Expression be3 = new com.avaya.sce.runtime.Expression("expression3", "AIR_591933_MENU_TBL:AIR_591933_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo1.addExpression(be3);
		com.avaya.sce.runtime.Expression be4 = new com.avaya.sce.runtime.Expression("expression4", "AIR_591939_MENU_TBL:AIR_591939_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo1.addExpression(be4);
		com.avaya.sce.runtime.Expression be5 = new com.avaya.sce.runtime.Expression("expression5", "AIR_591980_MENU_TBL:AIR_591980_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo1.addExpression(be5);
		com.avaya.sce.runtime.Expression be6 = new com.avaya.sce.runtime.Expression("expression6", "AIR_591993_MENU_TBL:AIR_591993_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo1.addExpression(be6);
		com.avaya.sce.runtime.Expression be7 = new com.avaya.sce.runtime.Expression("expression7", "AIR_380_MENU_TBL:AIR_380_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo1.addExpression(be7);
		com.avaya.sce.runtime.Expression be8 = new com.avaya.sce.runtime.Expression("expression8", "AIR_55135_MENU_TBL:AIR_55135_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo1.addExpression(be8);
		com.avaya.sce.runtime.Expression be9 = new com.avaya.sce.runtime.Expression("expression9", "AIR_591933_MENU_TBL:AIR_591933_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo1.addExpression(be9);
		com.avaya.sce.runtime.Expression be10 = new com.avaya.sce.runtime.Expression("expression10", "AIR_591939_MENU_TBL:AIR_591939_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo1.addExpression(be10);
		com.avaya.sce.runtime.Expression be11 = new com.avaya.sce.runtime.Expression("expression11", "AIR_591980_MENU_TBL:AIR_591980_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo1.addExpression(be11);
		com.avaya.sce.runtime.Expression be12 = new com.avaya.sce.runtime.Expression("expression12", "AIR_591993_MENU_TBL:AIR_591993_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo1.addExpression(be12);
		com.avaya.sce.runtime.BooleanOperation bo2 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
		com.avaya.sce.runtime.Expression be13 = new com.avaya.sce.runtime.Expression("expression13", "AIR_380_MENU_TBL:AIR_380_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo2.addExpression(be13);
		com.avaya.sce.runtime.Expression be14 = new com.avaya.sce.runtime.Expression("expression14", "AIR_55135_MENU_TBL:AIR_55135_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo2.addExpression(be14);
		com.avaya.sce.runtime.Expression be15 = new com.avaya.sce.runtime.Expression("expression15", "AIR_591933_MENU_TBL:AIR_591933_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo2.addExpression(be15);
		com.avaya.sce.runtime.Expression be16 = new com.avaya.sce.runtime.Expression("expression16", "AIR_591939_MENU_TBL:AIR_591939_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo2.addExpression(be16);
		com.avaya.sce.runtime.Expression be17 = new com.avaya.sce.runtime.Expression("expression17", "AIR_591980_MENU_TBL:AIR_591980_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo2.addExpression(be17);
		com.avaya.sce.runtime.Expression be18 = new com.avaya.sce.runtime.Expression("expression18", "AIR_591993_MENU_TBL:AIR_591993_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo2.addExpression(be18);
		com.avaya.sce.runtime.Expression be19 = new com.avaya.sce.runtime.Expression("expression19", "AIR_380_MENU_TBL:AIR_380_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo2.addExpression(be19);
		com.avaya.sce.runtime.Expression be20 = new com.avaya.sce.runtime.Expression("expression20", "AIR_55135_MENU_TBL:AIR_55135_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo2.addExpression(be20);
		com.avaya.sce.runtime.Expression be21 = new com.avaya.sce.runtime.Expression("expression21", "AIR_591933_MENU_TBL:AIR_591933_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo2.addExpression(be21);
		com.avaya.sce.runtime.Expression be22 = new com.avaya.sce.runtime.Expression("expression22", "AIR_591939_MENU_TBL:AIR_591939_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo2.addExpression(be22);
		com.avaya.sce.runtime.Expression be23 = new com.avaya.sce.runtime.Expression("expression23", "AIR_591980_MENU_TBL:AIR_591980_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo2.addExpression(be23);
		com.avaya.sce.runtime.Expression be24 = new com.avaya.sce.runtime.Expression("expression24", "AIR_591993_MENU_TBL:AIR_591993_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo2.addExpression(be24);
		com.avaya.sce.runtime.BooleanOperation bo3 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
		com.avaya.sce.runtime.Expression be25 = new com.avaya.sce.runtime.Expression("expression25", "AIR_380_MENU_TBL:AIR_380_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo3.addExpression(be25);
		com.avaya.sce.runtime.Expression be26 = new com.avaya.sce.runtime.Expression("expression26", "AIR_55135_MENU_TBL:AIR_55135_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo3.addExpression(be26);
		com.avaya.sce.runtime.Expression be27 = new com.avaya.sce.runtime.Expression("expression27", "AIR_591933_MENU_TBL:AIR_591933_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo3.addExpression(be27);
		com.avaya.sce.runtime.Expression be28 = new com.avaya.sce.runtime.Expression("expression28", "AIR_591939_MENU_TBL:AIR_591939_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo3.addExpression(be28);
		com.avaya.sce.runtime.Expression be29 = new com.avaya.sce.runtime.Expression("expression29", "AIR_591980_MENU_TBL:AIR_591980_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo3.addExpression(be29);
		com.avaya.sce.runtime.Expression be30 = new com.avaya.sce.runtime.Expression("expression30", "AIR_591993_MENU_TBL:AIR_591993_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo3.addExpression(be30);
		com.avaya.sce.runtime.Expression be31 = new com.avaya.sce.runtime.Expression("expression31", "AIR_380_MENU_TBL:AIR_380_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo3.addExpression(be31);
		com.avaya.sce.runtime.Expression be32 = new com.avaya.sce.runtime.Expression("expression32", "AIR_55135_MENU_TBL:AIR_55135_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo3.addExpression(be32);
		com.avaya.sce.runtime.Expression be33 = new com.avaya.sce.runtime.Expression("expression33", "AIR_591933_MENU_TBL:AIR_591933_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo3.addExpression(be33);
		com.avaya.sce.runtime.Expression be34 = new com.avaya.sce.runtime.Expression("expression34", "AIR_591939_MENU_TBL:AIR_591939_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo3.addExpression(be34);
		com.avaya.sce.runtime.Expression be35 = new com.avaya.sce.runtime.Expression("expression35", "AIR_591980_MENU_TBL:AIR_591980_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo3.addExpression(be35);
		com.avaya.sce.runtime.Expression be36 = new com.avaya.sce.runtime.Expression("expression36", "AIR_591993_MENU_TBL:AIR_591993_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo3.addExpression(be36);
		com.avaya.sce.runtime.BooleanOperation bo4 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
		com.avaya.sce.runtime.Expression be37 = new com.avaya.sce.runtime.Expression("expression37", "AIR_380_MENU_TBL:AIR_380_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo4.addExpression(be37);
		com.avaya.sce.runtime.Expression be38 = new com.avaya.sce.runtime.Expression("expression38", "AIR_55135_MENU_TBL:AIR_55135_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo4.addExpression(be38);
		com.avaya.sce.runtime.Expression be39 = new com.avaya.sce.runtime.Expression("expression39", "AIR_591933_MENU_TBL:AIR_591933_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo4.addExpression(be39);
		com.avaya.sce.runtime.Expression be40 = new com.avaya.sce.runtime.Expression("expression40", "AIR_591939_MENU_TBL:AIR_591939_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo4.addExpression(be40);
		com.avaya.sce.runtime.Expression be41 = new com.avaya.sce.runtime.Expression("expression41", "AIR_591980_MENU_TBL:AIR_591980_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo4.addExpression(be41);
		com.avaya.sce.runtime.Expression be42 = new com.avaya.sce.runtime.Expression("expression42", "AIR_591993_MENU_TBL:AIR_591993_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo4.addExpression(be42);
		com.avaya.sce.runtime.Expression be43 = new com.avaya.sce.runtime.Expression("expression43", "AIR_380_MENU_TBL:AIR_380_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo4.addExpression(be43);
		com.avaya.sce.runtime.Expression be44 = new com.avaya.sce.runtime.Expression("expression44", "AIR_55135_MENU_TBL:AIR_55135_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo4.addExpression(be44);
		com.avaya.sce.runtime.Expression be45 = new com.avaya.sce.runtime.Expression("expression45", "AIR_591933_MENU_TBL:AIR_591933_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo4.addExpression(be45);
		com.avaya.sce.runtime.Expression be46 = new com.avaya.sce.runtime.Expression("expression46", "AIR_591939_MENU_TBL:AIR_591939_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo4.addExpression(be46);
		com.avaya.sce.runtime.Expression be47 = new com.avaya.sce.runtime.Expression("expression47", "AIR_591980_MENU_TBL:AIR_591980_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo4.addExpression(be47);
		com.avaya.sce.runtime.Expression be48 = new com.avaya.sce.runtime.Expression("expression48", "AIR_591993_MENU_TBL:AIR_591993_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo4.addExpression(be48);
		com.avaya.sce.runtime.BooleanOperation bo5 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
		com.avaya.sce.runtime.Expression be49 = new com.avaya.sce.runtime.Expression("expression49", "AIR_380_MENU_TBL:AIR_380_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo5.addExpression(be49);
		com.avaya.sce.runtime.Expression be50 = new com.avaya.sce.runtime.Expression("expression50", "AIR_55135_MENU_TBL:AIR_55135_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo5.addExpression(be50);
		com.avaya.sce.runtime.Expression be51 = new com.avaya.sce.runtime.Expression("expression51", "AIR_591933_MENU_TBL:AIR_591933_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo5.addExpression(be51);
		com.avaya.sce.runtime.Expression be52 = new com.avaya.sce.runtime.Expression("expression52", "AIR_591939_MENU_TBL:AIR_591939_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo5.addExpression(be52);
		com.avaya.sce.runtime.Expression be53 = new com.avaya.sce.runtime.Expression("expression53", "AIR_591980_MENU_TBL:AIR_591980_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo5.addExpression(be53);
		com.avaya.sce.runtime.Expression be54 = new com.avaya.sce.runtime.Expression("expression54", "AIR_591993_MENU_TBL:AIR_591993_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo5.addExpression(be54);
		com.avaya.sce.runtime.Expression be55 = new com.avaya.sce.runtime.Expression("expression55", "AIR_380_MENU_TBL:AIR_380_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo5.addExpression(be55);
		com.avaya.sce.runtime.Expression be56 = new com.avaya.sce.runtime.Expression("expression56", "AIR_55135_MENU_TBL:AIR_55135_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo5.addExpression(be56);
		com.avaya.sce.runtime.Expression be57 = new com.avaya.sce.runtime.Expression("expression57", "AIR_591933_MENU_TBL:AIR_591933_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo5.addExpression(be57);
		com.avaya.sce.runtime.Expression be58 = new com.avaya.sce.runtime.Expression("expression58", "AIR_591939_MENU_TBL:AIR_591939_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo5.addExpression(be58);
		com.avaya.sce.runtime.Expression be59 = new com.avaya.sce.runtime.Expression("expression59", "AIR_591980_MENU_TBL:AIR_591980_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo5.addExpression(be59);
		com.avaya.sce.runtime.Expression be60 = new com.avaya.sce.runtime.Expression("expression60", "AIR_591993_MENU_TBL:AIR_591993_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo5.addExpression(be60);
		com.avaya.sce.runtime.BooleanOperation bo6 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
		com.avaya.sce.runtime.Expression be61 = new com.avaya.sce.runtime.Expression("expression61", "AIR_380_MENU_TBL:AIR_380_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo6.addExpression(be61);
		com.avaya.sce.runtime.Expression be62 = new com.avaya.sce.runtime.Expression("expression62", "AIR_55135_MENU_TBL:AIR_55135_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo6.addExpression(be62);
		com.avaya.sce.runtime.Expression be63 = new com.avaya.sce.runtime.Expression("expression63", "AIR_591933_MENU_TBL:AIR_591933_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo6.addExpression(be63);
		com.avaya.sce.runtime.Expression be64 = new com.avaya.sce.runtime.Expression("expression64", "AIR_591939_MENU_TBL:AIR_591939_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo6.addExpression(be64);
		com.avaya.sce.runtime.Expression be65 = new com.avaya.sce.runtime.Expression("expression65", "AIR_591980_MENU_TBL:AIR_591980_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo6.addExpression(be65);
		com.avaya.sce.runtime.Expression be66 = new com.avaya.sce.runtime.Expression("expression66", "AIR_591993_MENU_TBL:AIR_591993_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo6.addExpression(be66);
		com.avaya.sce.runtime.Expression be67 = new com.avaya.sce.runtime.Expression("expression67", "AIR_380_MENU_TBL:AIR_380_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo6.addExpression(be67);
		com.avaya.sce.runtime.Expression be68 = new com.avaya.sce.runtime.Expression("expression68", "AIR_55135_MENU_TBL:AIR_55135_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo6.addExpression(be68);
		com.avaya.sce.runtime.Expression be69 = new com.avaya.sce.runtime.Expression("expression69", "AIR_591933_MENU_TBL:AIR_591933_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo6.addExpression(be69);
		com.avaya.sce.runtime.Expression be70 = new com.avaya.sce.runtime.Expression("expression70", "AIR_591939_MENU_TBL:AIR_591939_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo6.addExpression(be70);
		com.avaya.sce.runtime.Expression be71 = new com.avaya.sce.runtime.Expression("expression71", "AIR_591980_MENU_TBL:AIR_591980_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo6.addExpression(be71);
		com.avaya.sce.runtime.Expression be72 = new com.avaya.sce.runtime.Expression("expression72", "AIR_591993_MENU_TBL:AIR_591993_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo6.addExpression(be72);
		com.avaya.sce.runtime.BooleanOperation bo7 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
		com.avaya.sce.runtime.Expression be73 = new com.avaya.sce.runtime.Expression("expression73", "AIR_380_MENU_TBL:AIR_380_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo7.addExpression(be73);
		com.avaya.sce.runtime.Expression be74 = new com.avaya.sce.runtime.Expression("expression74", "AIR_55135_MENU_TBL:AIR_55135_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo7.addExpression(be74);
		com.avaya.sce.runtime.Expression be75 = new com.avaya.sce.runtime.Expression("expression75", "AIR_591933_MENU_TBL:AIR_591933_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo7.addExpression(be75);
		com.avaya.sce.runtime.Expression be76 = new com.avaya.sce.runtime.Expression("expression76", "AIR_591939_MENU_TBL:AIR_591939_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo7.addExpression(be76);
		com.avaya.sce.runtime.Expression be77 = new com.avaya.sce.runtime.Expression("expression77", "AIR_591980_MENU_TBL:AIR_591980_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo7.addExpression(be77);
		com.avaya.sce.runtime.Expression be78 = new com.avaya.sce.runtime.Expression("expression78", "AIR_591993_MENU_TBL:AIR_591993_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo7.addExpression(be78);
		com.avaya.sce.runtime.Expression be79 = new com.avaya.sce.runtime.Expression("expression79", "AIR_380_MENU_TBL:AIR_380_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo7.addExpression(be79);
		com.avaya.sce.runtime.Expression be80 = new com.avaya.sce.runtime.Expression("expression80", "AIR_55135_MENU_TBL:AIR_55135_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo7.addExpression(be80);
		com.avaya.sce.runtime.Expression be81 = new com.avaya.sce.runtime.Expression("expression81", "AIR_591933_MENU_TBL:AIR_591933_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo7.addExpression(be81);
		com.avaya.sce.runtime.Expression be82 = new com.avaya.sce.runtime.Expression("expression82", "AIR_591939_MENU_TBL:AIR_591939_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo7.addExpression(be82);
		com.avaya.sce.runtime.Expression be83 = new com.avaya.sce.runtime.Expression("expression83", "AIR_591980_MENU_TBL:AIR_591980_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo7.addExpression(be83);
		com.avaya.sce.runtime.Expression be84 = new com.avaya.sce.runtime.Expression("expression84", "AIR_591993_MENU_TBL:AIR_591993_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo7.addExpression(be84);
		com.avaya.sce.runtime.BooleanOperation bo8 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
		com.avaya.sce.runtime.Expression be85 = new com.avaya.sce.runtime.Expression("expression85", "AIR_380_MENU_TBL:AIR_380_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo8.addExpression(be85);
		com.avaya.sce.runtime.Expression be86 = new com.avaya.sce.runtime.Expression("expression86", "AIR_55135_MENU_TBL:AIR_55135_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo8.addExpression(be86);
		com.avaya.sce.runtime.Expression be87 = new com.avaya.sce.runtime.Expression("expression87", "AIR_591933_MENU_TBL:AIR_591933_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo8.addExpression(be87);
		com.avaya.sce.runtime.Expression be88 = new com.avaya.sce.runtime.Expression("expression88", "AIR_591939_MENU_TBL:AIR_591939_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo8.addExpression(be88);
		com.avaya.sce.runtime.Expression be89 = new com.avaya.sce.runtime.Expression("expression89", "AIR_591980_MENU_TBL:AIR_591980_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo8.addExpression(be89);
		com.avaya.sce.runtime.Expression be90 = new com.avaya.sce.runtime.Expression("expression90", "AIR_591993_MENU_TBL:AIR_591993_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo8.addExpression(be90);
		com.avaya.sce.runtime.Expression be91 = new com.avaya.sce.runtime.Expression("expression91", "AIR_380_MENU_TBL:AIR_380_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo8.addExpression(be91);
		com.avaya.sce.runtime.Expression be92 = new com.avaya.sce.runtime.Expression("expression92", "AIR_55135_MENU_TBL:AIR_55135_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo8.addExpression(be92);
		com.avaya.sce.runtime.Expression be93 = new com.avaya.sce.runtime.Expression("expression93", "AIR_591933_MENU_TBL:AIR_591933_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo8.addExpression(be93);
		com.avaya.sce.runtime.Expression be94 = new com.avaya.sce.runtime.Expression("expression94", "AIR_591939_MENU_TBL:AIR_591939_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo8.addExpression(be94);
		com.avaya.sce.runtime.Expression be95 = new com.avaya.sce.runtime.Expression("expression95", "AIR_591980_MENU_TBL:AIR_591980_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo8.addExpression(be95);
		com.avaya.sce.runtime.Expression be96 = new com.avaya.sce.runtime.Expression("expression96", "AIR_591993_MENU_TBL:AIR_591993_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo8.addExpression(be96);
		com.avaya.sce.runtime.BooleanOperation bo9 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
		com.avaya.sce.runtime.Expression be97 = new com.avaya.sce.runtime.Expression("expression97", "AIR_380_MENU_TBL:AIR_380_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo9.addExpression(be97);
		com.avaya.sce.runtime.Expression be98 = new com.avaya.sce.runtime.Expression("expression98", "AIR_55135_MENU_TBL:AIR_55135_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo9.addExpression(be98);
		com.avaya.sce.runtime.Expression be99 = new com.avaya.sce.runtime.Expression("expression99", "AIR_591933_MENU_TBL:AIR_591933_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo9.addExpression(be99);
		com.avaya.sce.runtime.Expression be100 = new com.avaya.sce.runtime.Expression("expression100", "AIR_591939_MENU_TBL:AIR_591939_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo9.addExpression(be100);
		com.avaya.sce.runtime.Expression be101 = new com.avaya.sce.runtime.Expression("expression101", "AIR_591980_MENU_TBL:AIR_591980_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo9.addExpression(be101);
		com.avaya.sce.runtime.Expression be102 = new com.avaya.sce.runtime.Expression("expression102", "AIR_591993_MENU_TBL:AIR_591993_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo9.addExpression(be102);
		com.avaya.sce.runtime.Expression be103 = new com.avaya.sce.runtime.Expression("expression103", "AIR_380_MENU_TBL:AIR_380_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo9.addExpression(be103);
		com.avaya.sce.runtime.Expression be104 = new com.avaya.sce.runtime.Expression("expression104", "AIR_55135_MENU_TBL:AIR_55135_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo9.addExpression(be104);
		com.avaya.sce.runtime.Expression be105 = new com.avaya.sce.runtime.Expression("expression105", "AIR_591933_MENU_TBL:AIR_591933_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo9.addExpression(be105);
		com.avaya.sce.runtime.Expression be106 = new com.avaya.sce.runtime.Expression("expression106", "AIR_591939_MENU_TBL:AIR_591939_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo9.addExpression(be106);
		com.avaya.sce.runtime.Expression be107 = new com.avaya.sce.runtime.Expression("expression107", "AIR_591980_MENU_TBL:AIR_591980_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo9.addExpression(be107);
		com.avaya.sce.runtime.Expression be108 = new com.avaya.sce.runtime.Expression("expression108", "AIR_591993_MENU_TBL:AIR_591993_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo9.addExpression(be108);
		com.avaya.sce.runtime.BooleanOperation bo10 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
		com.avaya.sce.runtime.Expression be109 = new com.avaya.sce.runtime.Expression("expression109", "AIR_380_MENU_TBL:AIR_380_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo10.addExpression(be109);
		com.avaya.sce.runtime.Expression be110 = new com.avaya.sce.runtime.Expression("expression110", "AIR_55135_MENU_TBL:AIR_55135_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo10.addExpression(be110);
		com.avaya.sce.runtime.Expression be111 = new com.avaya.sce.runtime.Expression("expression111", "AIR_591933_MENU_TBL:AIR_591933_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo10.addExpression(be111);
		com.avaya.sce.runtime.Expression be112 = new com.avaya.sce.runtime.Expression("expression112", "AIR_591939_MENU_TBL:AIR_591939_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo10.addExpression(be112);
		com.avaya.sce.runtime.Expression be113 = new com.avaya.sce.runtime.Expression("expression113", "AIR_591980_MENU_TBL:AIR_591980_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo10.addExpression(be113);
		com.avaya.sce.runtime.Expression be114 = new com.avaya.sce.runtime.Expression("expression114", "AIR_591993_MENU_TBL:AIR_591993_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
		bo10.addExpression(be114);
		com.avaya.sce.runtime.Expression be115 = new com.avaya.sce.runtime.Expression("expression115", "AIR_380_MENU_TBL:AIR_380_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo10.addExpression(be115);
		com.avaya.sce.runtime.Expression be116 = new com.avaya.sce.runtime.Expression("expression116", "AIR_55135_MENU_TBL:AIR_55135_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo10.addExpression(be116);
		com.avaya.sce.runtime.Expression be117 = new com.avaya.sce.runtime.Expression("expression117", "AIR_591933_MENU_TBL:AIR_591933_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo10.addExpression(be117);
		com.avaya.sce.runtime.Expression be118 = new com.avaya.sce.runtime.Expression("expression118", "AIR_591939_MENU_TBL:AIR_591939_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo10.addExpression(be118);
		com.avaya.sce.runtime.Expression be119 = new com.avaya.sce.runtime.Expression("expression119", "AIR_591980_MENU_TBL:AIR_591980_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo10.addExpression(be119);
		com.avaya.sce.runtime.Expression be120 = new com.avaya.sce.runtime.Expression("expression120", "AIR_591993_MENU_TBL:AIR_591993_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
		bo10.addExpression(be120);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(291)).evaluate(mySession, bo1)) {
			actions = new java.util.ArrayList(1);
			com.avaya.sce.runtime.BooleanOperation bo11 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be121 = new com.avaya.sce.runtime.Expression("expression121", "AIR_380_MENU_TBL:AIR_380_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo11.addExpression(be121);
			com.avaya.sce.runtime.Expression be122 = new com.avaya.sce.runtime.Expression("expression122", "AIR_55135_MENU_TBL:AIR_55135_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo11.addExpression(be122);
			com.avaya.sce.runtime.Expression be123 = new com.avaya.sce.runtime.Expression("expression123", "AIR_591933_MENU_TBL:AIR_591933_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo11.addExpression(be123);
			com.avaya.sce.runtime.Expression be124 = new com.avaya.sce.runtime.Expression("expression124", "AIR_591939_MENU_TBL:AIR_591939_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo11.addExpression(be124);
			com.avaya.sce.runtime.Expression be125 = new com.avaya.sce.runtime.Expression("expression125", "AIR_591980_MENU_TBL:AIR_591980_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo11.addExpression(be125);
			com.avaya.sce.runtime.Expression be126 = new com.avaya.sce.runtime.Expression("expression126", "AIR_591993_MENU_TBL:AIR_591993_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo11.addExpression(be126);
			com.avaya.sce.runtime.BooleanOperation bo12 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be127 = new com.avaya.sce.runtime.Expression("expression127", "AIR_380_MENU_TBL:AIR_380_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo12.addExpression(be127);
			com.avaya.sce.runtime.Expression be128 = new com.avaya.sce.runtime.Expression("expression128", "AIR_55135_MENU_TBL:AIR_55135_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo12.addExpression(be128);
			com.avaya.sce.runtime.Expression be129 = new com.avaya.sce.runtime.Expression("expression129", "AIR_591933_MENU_TBL:AIR_591933_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo12.addExpression(be129);
			com.avaya.sce.runtime.Expression be130 = new com.avaya.sce.runtime.Expression("expression130", "AIR_591939_MENU_TBL:AIR_591939_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo12.addExpression(be130);
			com.avaya.sce.runtime.Expression be131 = new com.avaya.sce.runtime.Expression("expression131", "AIR_591980_MENU_TBL:AIR_591980_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo12.addExpression(be131);
			com.avaya.sce.runtime.Expression be132 = new com.avaya.sce.runtime.Expression("expression132", "AIR_591993_MENU_TBL:AIR_591993_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo12.addExpression(be132);
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

			if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(664)).evaluate(mySession, bo11)) {
				actions = new java.util.ArrayList(8);
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L1", "", true).setDebugId(650));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L1", "", true).setDebugId(651));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L1", "", true).setDebugId(652));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591939_MENU_TBL:AIR_591939_MENU_L1", "", true).setDebugId(653));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591980_MENU_TBL:AIR_591980_MENU_L1", "", true).setDebugId(654));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591993_MENU_TBL:AIR_591993_MENU_L1", "", true).setDebugId(655));
				actions.add(new com.avaya.sce.runtime.Next("CF_Menulog-repeate", "L1_*").setDebugId(656));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(678)).evaluate(mySession, bo12)) {
				actions = new java.util.ArrayList(8);
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L1", "", true).setDebugId(686));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L1", "", true).setDebugId(687));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L1", "", true).setDebugId(688));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591939_MENU_TBL:AIR_591939_MENU_L1", "", true).setDebugId(689));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591980_MENU_TBL:AIR_591980_MENU_L1", "", true).setDebugId(690));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591993_MENU_TBL:AIR_591993_MENU_L1", "", true).setDebugId(691));
				actions.add(new com.avaya.sce.runtime.Next("CF_Menulog-back", "L1_#").setDebugId(692));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			}

		} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(306)).evaluate(mySession, bo2)) {
			actions = new java.util.ArrayList(1);
			com.avaya.sce.runtime.BooleanOperation bo13 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be133 = new com.avaya.sce.runtime.Expression("expression133", "AIR_380_MENU_TBL:AIR_380_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo13.addExpression(be133);
			com.avaya.sce.runtime.Expression be134 = new com.avaya.sce.runtime.Expression("expression134", "AIR_55135_MENU_TBL:AIR_55135_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo13.addExpression(be134);
			com.avaya.sce.runtime.Expression be135 = new com.avaya.sce.runtime.Expression("expression135", "AIR_591933_MENU_TBL:AIR_591933_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo13.addExpression(be135);
			com.avaya.sce.runtime.Expression be136 = new com.avaya.sce.runtime.Expression("expression136", "AIR_591939_MENU_TBL:AIR_591939_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo13.addExpression(be136);
			com.avaya.sce.runtime.Expression be137 = new com.avaya.sce.runtime.Expression("expression137", "AIR_591980_MENU_TBL:AIR_591980_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo13.addExpression(be137);
			com.avaya.sce.runtime.Expression be138 = new com.avaya.sce.runtime.Expression("expression138", "AIR_591993_MENU_TBL:AIR_591993_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo13.addExpression(be138);
			com.avaya.sce.runtime.BooleanOperation bo14 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be139 = new com.avaya.sce.runtime.Expression("expression139", "AIR_380_MENU_TBL:AIR_380_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo14.addExpression(be139);
			com.avaya.sce.runtime.Expression be140 = new com.avaya.sce.runtime.Expression("expression140", "AIR_55135_MENU_TBL:AIR_55135_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo14.addExpression(be140);
			com.avaya.sce.runtime.Expression be141 = new com.avaya.sce.runtime.Expression("expression141", "AIR_591933_MENU_TBL:AIR_591933_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo14.addExpression(be141);
			com.avaya.sce.runtime.Expression be142 = new com.avaya.sce.runtime.Expression("expression142", "AIR_591939_MENU_TBL:AIR_591939_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo14.addExpression(be142);
			com.avaya.sce.runtime.Expression be143 = new com.avaya.sce.runtime.Expression("expression143", "AIR_591980_MENU_TBL:AIR_591980_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo14.addExpression(be143);
			com.avaya.sce.runtime.Expression be144 = new com.avaya.sce.runtime.Expression("expression144", "AIR_591993_MENU_TBL:AIR_591993_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo14.addExpression(be144);
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

			if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(705)).evaluate(mySession, bo13)) {
				actions = new java.util.ArrayList(8);
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L2", "", true).setDebugId(740));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L2", "", true).setDebugId(741));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L2", "", true).setDebugId(742));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591939_MENU_TBL:AIR_591939_MENU_L2", "", true).setDebugId(743));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591980_MENU_TBL:AIR_591980_MENU_L2", "", true).setDebugId(744));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591993_MENU_TBL:AIR_591993_MENU_L2", "", true).setDebugId(745));
				actions.add(new com.avaya.sce.runtime.Next("CF_Menulog-repeate", "L2_*").setDebugId(746));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(706)).evaluate(mySession, bo14)) {
				actions = new java.util.ArrayList(14);
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L1", "", true).setDebugId(747));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L2", "", true).setDebugId(754));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L1", "", true).setDebugId(748));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L2", "", true).setDebugId(755));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L1", "", true).setDebugId(749));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L2", "", true).setDebugId(756));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591939_MENU_TBL:AIR_591939_MENU_L1", "", true).setDebugId(750));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591939_MENU_TBL:AIR_591939_MENU_L2", "", true).setDebugId(757));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591980_MENU_TBL:AIR_591980_MENU_L1", "", true).setDebugId(751));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591980_MENU_TBL:AIR_591980_MENU_L2", "", true).setDebugId(758));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591993_MENU_TBL:AIR_591993_MENU_L1", "", true).setDebugId(752));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591993_MENU_TBL:AIR_591993_MENU_L2", "", true).setDebugId(759));
				actions.add(new com.avaya.sce.runtime.Next("CF_Menulog-back", "L2_#").setDebugId(753));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			}

		} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(760)).evaluate(mySession, bo3)) {
			actions = new java.util.ArrayList(1);
			com.avaya.sce.runtime.BooleanOperation bo15 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be145 = new com.avaya.sce.runtime.Expression("expression145", "AIR_380_MENU_TBL:AIR_380_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo15.addExpression(be145);
			com.avaya.sce.runtime.Expression be146 = new com.avaya.sce.runtime.Expression("expression146", "AIR_55135_MENU_TBL:AIR_55135_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo15.addExpression(be146);
			com.avaya.sce.runtime.Expression be147 = new com.avaya.sce.runtime.Expression("expression147", "AIR_591933_MENU_TBL:AIR_591933_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo15.addExpression(be147);
			com.avaya.sce.runtime.Expression be148 = new com.avaya.sce.runtime.Expression("expression148", "AIR_591939_MENU_TBL:AIR_591939_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo15.addExpression(be148);
			com.avaya.sce.runtime.Expression be149 = new com.avaya.sce.runtime.Expression("expression149", "AIR_591980_MENU_TBL:AIR_591980_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo15.addExpression(be149);
			com.avaya.sce.runtime.Expression be150 = new com.avaya.sce.runtime.Expression("expression150", "AIR_591993_MENU_TBL:AIR_591993_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo15.addExpression(be150);
			com.avaya.sce.runtime.BooleanOperation bo16 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be151 = new com.avaya.sce.runtime.Expression("expression151", "AIR_380_MENU_TBL:AIR_380_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo16.addExpression(be151);
			com.avaya.sce.runtime.Expression be152 = new com.avaya.sce.runtime.Expression("expression152", "AIR_55135_MENU_TBL:AIR_55135_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo16.addExpression(be152);
			com.avaya.sce.runtime.Expression be153 = new com.avaya.sce.runtime.Expression("expression153", "AIR_591933_MENU_TBL:AIR_591933_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo16.addExpression(be153);
			com.avaya.sce.runtime.Expression be154 = new com.avaya.sce.runtime.Expression("expression154", "AIR_591939_MENU_TBL:AIR_591939_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo16.addExpression(be154);
			com.avaya.sce.runtime.Expression be155 = new com.avaya.sce.runtime.Expression("expression155", "AIR_591980_MENU_TBL:AIR_591980_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo16.addExpression(be155);
			com.avaya.sce.runtime.Expression be156 = new com.avaya.sce.runtime.Expression("expression156", "AIR_591993_MENU_TBL:AIR_591993_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo16.addExpression(be156);
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

			if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(774)).evaluate(mySession, bo15)) {
				actions = new java.util.ArrayList(8);
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L3", "", true).setDebugId(782));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L3", "", true).setDebugId(783));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L3", "", true).setDebugId(784));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591939_MENU_TBL:AIR_591939_MENU_L3", "", true).setDebugId(785));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591980_MENU_TBL:AIR_591980_MENU_L3", "", true).setDebugId(786));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591993_MENU_TBL:AIR_591993_MENU_L3", "", true).setDebugId(787));
				actions.add(new com.avaya.sce.runtime.Next("CF_Menulog-repeate", "L3_*").setDebugId(788));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(789)).evaluate(mySession, bo16)) {
				actions = new java.util.ArrayList(14);
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L3", "", true).setDebugId(797));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L2", "", true).setDebugId(798));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L3", "", true).setDebugId(799));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L2", "", true).setDebugId(800));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L3", "", true).setDebugId(801));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L2", "", true).setDebugId(802));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591939_MENU_TBL:AIR_591939_MENU_L3", "", true).setDebugId(803));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591939_MENU_TBL:AIR_591939_MENU_L2", "", true).setDebugId(804));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591980_MENU_TBL:AIR_591980_MENU_L3", "", true).setDebugId(805));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591980_MENU_TBL:AIR_591980_MENU_L2", "", true).setDebugId(806));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591993_MENU_TBL:AIR_591993_MENU_L3", "", true).setDebugId(807));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591993_MENU_TBL:AIR_591993_MENU_L2", "", true).setDebugId(808));
				actions.add(new com.avaya.sce.runtime.Next("CF_Menulog-back", "L3_#").setDebugId(809));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			}

		} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(810)).evaluate(mySession, bo4)) {
			actions = new java.util.ArrayList(1);
			com.avaya.sce.runtime.BooleanOperation bo17 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be157 = new com.avaya.sce.runtime.Expression("expression157", "AIR_380_MENU_TBL:AIR_380_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo17.addExpression(be157);
			com.avaya.sce.runtime.Expression be158 = new com.avaya.sce.runtime.Expression("expression158", "AIR_55135_MENU_TBL:AIR_55135_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo17.addExpression(be158);
			com.avaya.sce.runtime.Expression be159 = new com.avaya.sce.runtime.Expression("expression159", "AIR_591933_MENU_TBL:AIR_591933_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo17.addExpression(be159);
			com.avaya.sce.runtime.Expression be160 = new com.avaya.sce.runtime.Expression("expression160", "AIR_591939_MENU_TBL:AIR_591939_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo17.addExpression(be160);
			com.avaya.sce.runtime.Expression be161 = new com.avaya.sce.runtime.Expression("expression161", "AIR_591980_MENU_TBL:AIR_591980_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo17.addExpression(be161);
			com.avaya.sce.runtime.Expression be162 = new com.avaya.sce.runtime.Expression("expression162", "AIR_591993_MENU_TBL:AIR_591993_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo17.addExpression(be162);
			com.avaya.sce.runtime.BooleanOperation bo18 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be163 = new com.avaya.sce.runtime.Expression("expression163", "AIR_380_MENU_TBL:AIR_380_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo18.addExpression(be163);
			com.avaya.sce.runtime.Expression be164 = new com.avaya.sce.runtime.Expression("expression164", "AIR_55135_MENU_TBL:AIR_55135_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo18.addExpression(be164);
			com.avaya.sce.runtime.Expression be165 = new com.avaya.sce.runtime.Expression("expression165", "AIR_591933_MENU_TBL:AIR_591933_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo18.addExpression(be165);
			com.avaya.sce.runtime.Expression be166 = new com.avaya.sce.runtime.Expression("expression166", "AIR_591939_MENU_TBL:AIR_591939_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo18.addExpression(be166);
			com.avaya.sce.runtime.Expression be167 = new com.avaya.sce.runtime.Expression("expression167", "AIR_591980_MENU_TBL:AIR_591980_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo18.addExpression(be167);
			com.avaya.sce.runtime.Expression be168 = new com.avaya.sce.runtime.Expression("expression168", "AIR_591993_MENU_TBL:AIR_591993_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo18.addExpression(be168);
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

			if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(824)).evaluate(mySession, bo17)) {
				actions = new java.util.ArrayList(8);
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L4", "", true).setDebugId(832));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L4", "", true).setDebugId(833));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L4", "", true).setDebugId(834));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591939_MENU_TBL:AIR_591939_MENU_L4", "", true).setDebugId(835));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591980_MENU_TBL:AIR_591980_MENU_L4", "", true).setDebugId(836));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591993_MENU_TBL:AIR_591993_MENU_L4", "", true).setDebugId(837));
				actions.add(new com.avaya.sce.runtime.Next("CF_Menulog-repeate", "L4_*").setDebugId(838));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(839)).evaluate(mySession, bo18)) {
				actions = new java.util.ArrayList(14);
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L3", "", true).setDebugId(848));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L3", "", true).setDebugId(850));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L3", "", true).setDebugId(852));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591939_MENU_TBL:AIR_591939_MENU_L3", "", true).setDebugId(854));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591980_MENU_TBL:AIR_591980_MENU_L3", "", true).setDebugId(856));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591993_MENU_TBL:AIR_591993_MENU_L3", "", true).setDebugId(858));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L4", "", true).setDebugId(1172));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L4", "", true).setDebugId(1173));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L4", "", true).setDebugId(1174));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591939_MENU_TBL:AIR_591939_MENU_L4", "", true).setDebugId(1175));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591980_MENU_TBL:AIR_591980_MENU_L4", "", true).setDebugId(1176));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591993_MENU_TBL:AIR_591993_MENU_L4", "", true).setDebugId(1177));
				actions.add(new com.avaya.sce.runtime.Next("CF_Menulog-back", "L4_#").setDebugId(859));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			}

		} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(860)).evaluate(mySession, bo5)) {
			actions = new java.util.ArrayList(1);
			com.avaya.sce.runtime.BooleanOperation bo19 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be169 = new com.avaya.sce.runtime.Expression("expression169", "AIR_380_MENU_TBL:AIR_380_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo19.addExpression(be169);
			com.avaya.sce.runtime.Expression be170 = new com.avaya.sce.runtime.Expression("expression170", "AIR_55135_MENU_TBL:AIR_55135_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo19.addExpression(be170);
			com.avaya.sce.runtime.Expression be171 = new com.avaya.sce.runtime.Expression("expression171", "AIR_591933_MENU_TBL:AIR_591933_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo19.addExpression(be171);
			com.avaya.sce.runtime.Expression be172 = new com.avaya.sce.runtime.Expression("expression172", "AIR_591939_MENU_TBL:AIR_591939_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo19.addExpression(be172);
			com.avaya.sce.runtime.Expression be173 = new com.avaya.sce.runtime.Expression("expression173", "AIR_591980_MENU_TBL:AIR_591980_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo19.addExpression(be173);
			com.avaya.sce.runtime.Expression be174 = new com.avaya.sce.runtime.Expression("expression174", "AIR_591993_MENU_TBL:AIR_591993_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo19.addExpression(be174);
			com.avaya.sce.runtime.BooleanOperation bo20 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be175 = new com.avaya.sce.runtime.Expression("expression175", "AIR_380_MENU_TBL:AIR_380_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo20.addExpression(be175);
			com.avaya.sce.runtime.Expression be176 = new com.avaya.sce.runtime.Expression("expression176", "AIR_55135_MENU_TBL:AIR_55135_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo20.addExpression(be176);
			com.avaya.sce.runtime.Expression be177 = new com.avaya.sce.runtime.Expression("expression177", "AIR_591933_MENU_TBL:AIR_591933_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo20.addExpression(be177);
			com.avaya.sce.runtime.Expression be178 = new com.avaya.sce.runtime.Expression("expression178", "AIR_591939_MENU_TBL:AIR_591939_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo20.addExpression(be178);
			com.avaya.sce.runtime.Expression be179 = new com.avaya.sce.runtime.Expression("expression179", "AIR_591980_MENU_TBL:AIR_591980_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo20.addExpression(be179);
			com.avaya.sce.runtime.Expression be180 = new com.avaya.sce.runtime.Expression("expression180", "AIR_591993_MENU_TBL:AIR_591993_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo20.addExpression(be180);
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

			if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(874)).evaluate(mySession, bo19)) {
				actions = new java.util.ArrayList(8);
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L5", "", true).setDebugId(882));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L5", "", true).setDebugId(883));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L5", "", true).setDebugId(884));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591939_MENU_TBL:AIR_591939_MENU_L5", "", true).setDebugId(885));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591980_MENU_TBL:AIR_591980_MENU_L5", "", true).setDebugId(886));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591993_MENU_TBL:AIR_591993_MENU_L5", "", true).setDebugId(887));
				actions.add(new com.avaya.sce.runtime.Next("CF_Menulog-repeate", "L5_*").setDebugId(888));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(889)).evaluate(mySession, bo20)) {
				actions = new java.util.ArrayList(14);
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L4", "", true).setDebugId(1190));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L4", "", true).setDebugId(1191));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L4", "", true).setDebugId(1192));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591939_MENU_TBL:AIR_591939_MENU_L4", "", true).setDebugId(1193));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591980_MENU_TBL:AIR_591980_MENU_L4", "", true).setDebugId(1194));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591993_MENU_TBL:AIR_591993_MENU_L4", "", true).setDebugId(1195));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L5", "", true).setDebugId(1202));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L5", "", true).setDebugId(1203));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L5", "", true).setDebugId(1204));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591939_MENU_TBL:AIR_591939_MENU_L5", "", true).setDebugId(1205));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591980_MENU_TBL:AIR_591980_MENU_L5", "", true).setDebugId(1206));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591993_MENU_TBL:AIR_591993_MENU_L5", "", true).setDebugId(1207));
				actions.add(new com.avaya.sce.runtime.Next("CF_Menulog-back", "L5_#").setDebugId(909));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			}

		} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(910)).evaluate(mySession, bo6)) {
			actions = new java.util.ArrayList(1);
			com.avaya.sce.runtime.BooleanOperation bo21 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be181 = new com.avaya.sce.runtime.Expression("expression181", "AIR_380_MENU_TBL:AIR_380_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo21.addExpression(be181);
			com.avaya.sce.runtime.Expression be182 = new com.avaya.sce.runtime.Expression("expression182", "AIR_55135_MENU_TBL:AIR_55135_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo21.addExpression(be182);
			com.avaya.sce.runtime.Expression be183 = new com.avaya.sce.runtime.Expression("expression183", "AIR_591933_MENU_TBL:AIR_591933_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo21.addExpression(be183);
			com.avaya.sce.runtime.Expression be184 = new com.avaya.sce.runtime.Expression("expression184", "AIR_591939_MENU_TBL:AIR_591939_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo21.addExpression(be184);
			com.avaya.sce.runtime.Expression be185 = new com.avaya.sce.runtime.Expression("expression185", "AIR_591980_MENU_TBL:AIR_591980_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo21.addExpression(be185);
			com.avaya.sce.runtime.Expression be186 = new com.avaya.sce.runtime.Expression("expression186", "AIR_591993_MENU_TBL:AIR_591993_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo21.addExpression(be186);
			com.avaya.sce.runtime.BooleanOperation bo22 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be187 = new com.avaya.sce.runtime.Expression("expression187", "AIR_380_MENU_TBL:AIR_380_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo22.addExpression(be187);
			com.avaya.sce.runtime.Expression be188 = new com.avaya.sce.runtime.Expression("expression188", "AIR_55135_MENU_TBL:AIR_55135_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo22.addExpression(be188);
			com.avaya.sce.runtime.Expression be189 = new com.avaya.sce.runtime.Expression("expression189", "AIR_591933_MENU_TBL:AIR_591933_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo22.addExpression(be189);
			com.avaya.sce.runtime.Expression be190 = new com.avaya.sce.runtime.Expression("expression190", "AIR_591939_MENU_TBL:AIR_591939_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo22.addExpression(be190);
			com.avaya.sce.runtime.Expression be191 = new com.avaya.sce.runtime.Expression("expression191", "AIR_591980_MENU_TBL:AIR_591980_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo22.addExpression(be191);
			com.avaya.sce.runtime.Expression be192 = new com.avaya.sce.runtime.Expression("expression192", "AIR_591993_MENU_TBL:AIR_591993_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo22.addExpression(be192);
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

			if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(924)).evaluate(mySession, bo21)) {
				actions = new java.util.ArrayList(8);
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L6", "", true).setDebugId(932));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L6", "", true).setDebugId(933));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L6", "", true).setDebugId(934));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591939_MENU_TBL:AIR_591939_MENU_L6", "", true).setDebugId(935));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591980_MENU_TBL:AIR_591980_MENU_L6", "", true).setDebugId(936));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591993_MENU_TBL:AIR_591993_MENU_L6", "", true).setDebugId(937));
				actions.add(new com.avaya.sce.runtime.Next("CF_Menulog-repeate", "L6_*").setDebugId(938));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(939)).evaluate(mySession, bo22)) {
				actions = new java.util.ArrayList(14);
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L5", "", true).setDebugId(1220));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L5", "", true).setDebugId(1221));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L5", "", true).setDebugId(1222));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591939_MENU_TBL:AIR_591939_MENU_L5", "", true).setDebugId(1223));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591980_MENU_TBL:AIR_591980_MENU_L5", "", true).setDebugId(1224));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591993_MENU_TBL:AIR_591993_MENU_L5", "", true).setDebugId(1225));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L6", "", true).setDebugId(1226));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L6", "", true).setDebugId(1227));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L6", "", true).setDebugId(1228));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591939_MENU_TBL:AIR_591939_MENU_L6", "", true).setDebugId(1229));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591980_MENU_TBL:AIR_591980_MENU_L6", "", true).setDebugId(1230));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591993_MENU_TBL:AIR_591993_MENU_L6", "", true).setDebugId(1231));
				actions.add(new com.avaya.sce.runtime.Next("CF_Menulog-back", "L6_#").setDebugId(959));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			}

		} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(960)).evaluate(mySession, bo7)) {
			actions = new java.util.ArrayList(1);
			com.avaya.sce.runtime.BooleanOperation bo23 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be193 = new com.avaya.sce.runtime.Expression("expression193", "AIR_380_MENU_TBL:AIR_380_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo23.addExpression(be193);
			com.avaya.sce.runtime.Expression be194 = new com.avaya.sce.runtime.Expression("expression194", "AIR_55135_MENU_TBL:AIR_55135_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo23.addExpression(be194);
			com.avaya.sce.runtime.Expression be195 = new com.avaya.sce.runtime.Expression("expression195", "AIR_591933_MENU_TBL:AIR_591933_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo23.addExpression(be195);
			com.avaya.sce.runtime.Expression be196 = new com.avaya.sce.runtime.Expression("expression196", "AIR_591939_MENU_TBL:AIR_591939_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo23.addExpression(be196);
			com.avaya.sce.runtime.Expression be197 = new com.avaya.sce.runtime.Expression("expression197", "AIR_591980_MENU_TBL:AIR_591980_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo23.addExpression(be197);
			com.avaya.sce.runtime.Expression be198 = new com.avaya.sce.runtime.Expression("expression198", "AIR_591993_MENU_TBL:AIR_591993_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo23.addExpression(be198);
			com.avaya.sce.runtime.BooleanOperation bo24 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be199 = new com.avaya.sce.runtime.Expression("expression199", "AIR_380_MENU_TBL:AIR_380_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo24.addExpression(be199);
			com.avaya.sce.runtime.Expression be200 = new com.avaya.sce.runtime.Expression("expression200", "AIR_55135_MENU_TBL:AIR_55135_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo24.addExpression(be200);
			com.avaya.sce.runtime.Expression be201 = new com.avaya.sce.runtime.Expression("expression201", "AIR_591933_MENU_TBL:AIR_591933_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo24.addExpression(be201);
			com.avaya.sce.runtime.Expression be202 = new com.avaya.sce.runtime.Expression("expression202", "AIR_591939_MENU_TBL:AIR_591939_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo24.addExpression(be202);
			com.avaya.sce.runtime.Expression be203 = new com.avaya.sce.runtime.Expression("expression203", "AIR_591980_MENU_TBL:AIR_591980_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo24.addExpression(be203);
			com.avaya.sce.runtime.Expression be204 = new com.avaya.sce.runtime.Expression("expression204", "AIR_591993_MENU_TBL:AIR_591993_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo24.addExpression(be204);
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

			if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(974)).evaluate(mySession, bo23)) {
				actions = new java.util.ArrayList(8);
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L7", "", true).setDebugId(982));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L7", "", true).setDebugId(983));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L7", "", true).setDebugId(984));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591939_MENU_TBL:AIR_591939_MENU_L7", "", true).setDebugId(985));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591980_MENU_TBL:AIR_591980_MENU_L7", "", true).setDebugId(986));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591993_MENU_TBL:AIR_591993_MENU_L7", "", true).setDebugId(987));
				actions.add(new com.avaya.sce.runtime.Next("CF_Menulog-repeate", "L7_*").setDebugId(988));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(989)).evaluate(mySession, bo24)) {
				actions = new java.util.ArrayList(14);
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L6", "", true).setDebugId(1244));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L6", "", true).setDebugId(1245));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L6", "", true).setDebugId(1246));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591939_MENU_TBL:AIR_591939_MENU_L6", "", true).setDebugId(1247));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591980_MENU_TBL:AIR_591980_MENU_L6", "", true).setDebugId(1248));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591993_MENU_TBL:AIR_591993_MENU_L6", "", true).setDebugId(1249));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L7", "", true).setDebugId(1250));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L7", "", true).setDebugId(1251));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L7", "", true).setDebugId(1252));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591939_MENU_TBL:AIR_591939_MENU_L7", "", true).setDebugId(1253));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591980_MENU_TBL:AIR_591980_MENU_L7", "", true).setDebugId(1254));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591993_MENU_TBL:AIR_591993_MENU_L7", "", true).setDebugId(1255));
				actions.add(new com.avaya.sce.runtime.Next("CF_Menulog-back", "L7_#").setDebugId(1009));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			}

		} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(1010)).evaluate(mySession, bo8)) {
			actions = new java.util.ArrayList(1);
			com.avaya.sce.runtime.BooleanOperation bo25 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be205 = new com.avaya.sce.runtime.Expression("expression205", "AIR_380_MENU_TBL:AIR_380_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo25.addExpression(be205);
			com.avaya.sce.runtime.Expression be206 = new com.avaya.sce.runtime.Expression("expression206", "AIR_55135_MENU_TBL:AIR_55135_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo25.addExpression(be206);
			com.avaya.sce.runtime.Expression be207 = new com.avaya.sce.runtime.Expression("expression207", "AIR_591933_MENU_TBL:AIR_591933_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo25.addExpression(be207);
			com.avaya.sce.runtime.Expression be208 = new com.avaya.sce.runtime.Expression("expression208", "AIR_591939_MENU_TBL:AIR_591939_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo25.addExpression(be208);
			com.avaya.sce.runtime.Expression be209 = new com.avaya.sce.runtime.Expression("expression209", "AIR_591980_MENU_TBL:AIR_591980_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo25.addExpression(be209);
			com.avaya.sce.runtime.Expression be210 = new com.avaya.sce.runtime.Expression("expression210", "AIR_591993_MENU_TBL:AIR_591993_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo25.addExpression(be210);
			com.avaya.sce.runtime.BooleanOperation bo26 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be211 = new com.avaya.sce.runtime.Expression("expression211", "AIR_380_MENU_TBL:AIR_380_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo26.addExpression(be211);
			com.avaya.sce.runtime.Expression be212 = new com.avaya.sce.runtime.Expression("expression212", "AIR_55135_MENU_TBL:AIR_55135_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo26.addExpression(be212);
			com.avaya.sce.runtime.Expression be213 = new com.avaya.sce.runtime.Expression("expression213", "AIR_591933_MENU_TBL:AIR_591933_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo26.addExpression(be213);
			com.avaya.sce.runtime.Expression be214 = new com.avaya.sce.runtime.Expression("expression214", "AIR_591939_MENU_TBL:AIR_591939_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo26.addExpression(be214);
			com.avaya.sce.runtime.Expression be215 = new com.avaya.sce.runtime.Expression("expression215", "AIR_591980_MENU_TBL:AIR_591980_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo26.addExpression(be215);
			com.avaya.sce.runtime.Expression be216 = new com.avaya.sce.runtime.Expression("expression216", "AIR_591993_MENU_TBL:AIR_591993_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo26.addExpression(be216);
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

			if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(1024)).evaluate(mySession, bo25)) {
				actions = new java.util.ArrayList(8);
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L8", "", true).setDebugId(1032));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L8", "", true).setDebugId(1033));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L8", "", true).setDebugId(1034));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591939_MENU_TBL:AIR_591939_MENU_L8", "", true).setDebugId(1035));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591980_MENU_TBL:AIR_591980_MENU_L8", "", true).setDebugId(1036));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591993_MENU_TBL:AIR_591993_MENU_L8", "", true).setDebugId(1037));
				actions.add(new com.avaya.sce.runtime.Next("CF_Menulog-repeate", "L8_*").setDebugId(1038));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(1039)).evaluate(mySession, bo26)) {
				actions = new java.util.ArrayList(14);
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L7", "", true).setDebugId(1268));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L7", "", true).setDebugId(1269));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L7", "", true).setDebugId(1270));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591939_MENU_TBL:AIR_591939_MENU_L7", "", true).setDebugId(1271));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591980_MENU_TBL:AIR_591980_MENU_L7", "", true).setDebugId(1272));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591993_MENU_TBL:AIR_591993_MENU_L7", "", true).setDebugId(1273));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L8", "", true).setDebugId(1274));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L8", "", true).setDebugId(1275));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L8", "", true).setDebugId(1276));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591939_MENU_TBL:AIR_591939_MENU_L8", "", true).setDebugId(1277));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591980_MENU_TBL:AIR_591980_MENU_L8", "", true).setDebugId(1278));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591993_MENU_TBL:AIR_591993_MENU_L8", "", true).setDebugId(1279));
				actions.add(new com.avaya.sce.runtime.Next("CF_Menulog-back", "L8_#").setDebugId(1059));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			}

		} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(1060)).evaluate(mySession, bo9)) {
			actions = new java.util.ArrayList(1);
			com.avaya.sce.runtime.BooleanOperation bo27 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be217 = new com.avaya.sce.runtime.Expression("expression217", "AIR_380_MENU_TBL:AIR_380_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo27.addExpression(be217);
			com.avaya.sce.runtime.Expression be218 = new com.avaya.sce.runtime.Expression("expression218", "AIR_55135_MENU_TBL:AIR_55135_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo27.addExpression(be218);
			com.avaya.sce.runtime.Expression be219 = new com.avaya.sce.runtime.Expression("expression219", "AIR_591933_MENU_TBL:AIR_591933_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo27.addExpression(be219);
			com.avaya.sce.runtime.Expression be220 = new com.avaya.sce.runtime.Expression("expression220", "AIR_591939_MENU_TBL:AIR_591939_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo27.addExpression(be220);
			com.avaya.sce.runtime.Expression be221 = new com.avaya.sce.runtime.Expression("expression221", "AIR_591980_MENU_TBL:AIR_591980_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo27.addExpression(be221);
			com.avaya.sce.runtime.Expression be222 = new com.avaya.sce.runtime.Expression("expression222", "AIR_591993_MENU_TBL:AIR_591993_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo27.addExpression(be222);
			com.avaya.sce.runtime.BooleanOperation bo28 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be223 = new com.avaya.sce.runtime.Expression("expression223", "AIR_380_MENU_TBL:AIR_380_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo28.addExpression(be223);
			com.avaya.sce.runtime.Expression be224 = new com.avaya.sce.runtime.Expression("expression224", "AIR_55135_MENU_TBL:AIR_55135_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo28.addExpression(be224);
			com.avaya.sce.runtime.Expression be225 = new com.avaya.sce.runtime.Expression("expression225", "AIR_591933_MENU_TBL:AIR_591933_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo28.addExpression(be225);
			com.avaya.sce.runtime.Expression be226 = new com.avaya.sce.runtime.Expression("expression226", "AIR_591939_MENU_TBL:AIR_591939_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo28.addExpression(be226);
			com.avaya.sce.runtime.Expression be227 = new com.avaya.sce.runtime.Expression("expression227", "AIR_591980_MENU_TBL:AIR_591980_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo28.addExpression(be227);
			com.avaya.sce.runtime.Expression be228 = new com.avaya.sce.runtime.Expression("expression228", "AIR_591993_MENU_TBL:AIR_591993_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo28.addExpression(be228);
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

			if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(1074)).evaluate(mySession, bo27)) {
				actions = new java.util.ArrayList(8);
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L9", "", true).setDebugId(1082));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L9", "", true).setDebugId(1083));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L9", "", true).setDebugId(1084));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591939_MENU_TBL:AIR_591939_MENU_L9", "", true).setDebugId(1085));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591980_MENU_TBL:AIR_591980_MENU_L9", "", true).setDebugId(1086));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591993_MENU_TBL:AIR_591993_MENU_L9", "", true).setDebugId(1087));
				actions.add(new com.avaya.sce.runtime.Next("CF_Menulog-repeate", "L9_*").setDebugId(1088));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(1089)).evaluate(mySession, bo28)) {
				actions = new java.util.ArrayList(14);
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L8", "", true).setDebugId(1292));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L8", "", true).setDebugId(1293));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L8", "", true).setDebugId(1294));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591939_MENU_TBL:AIR_591939_MENU_L8", "", true).setDebugId(1295));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591980_MENU_TBL:AIR_591980_MENU_L8", "", true).setDebugId(1296));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591993_MENU_TBL:AIR_591993_MENU_L8", "", true).setDebugId(1297));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L9", "", true).setDebugId(1298));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L9", "", true).setDebugId(1299));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L9", "", true).setDebugId(1300));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591939_MENU_TBL:AIR_591939_MENU_L9", "", true).setDebugId(1301));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591980_MENU_TBL:AIR_591980_MENU_L9", "", true).setDebugId(1302));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591993_MENU_TBL:AIR_591993_MENU_L9", "", true).setDebugId(1303));
				actions.add(new com.avaya.sce.runtime.Next("CF_Menulog-back", "L9_#").setDebugId(1109));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			}

		} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(1110)).evaluate(mySession, bo10)) {
			actions = new java.util.ArrayList(1);
			com.avaya.sce.runtime.BooleanOperation bo29 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be229 = new com.avaya.sce.runtime.Expression("expression229", "AIR_380_MENU_TBL:AIR_380_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo29.addExpression(be229);
			com.avaya.sce.runtime.Expression be230 = new com.avaya.sce.runtime.Expression("expression230", "AIR_55135_MENU_TBL:AIR_55135_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo29.addExpression(be230);
			com.avaya.sce.runtime.Expression be231 = new com.avaya.sce.runtime.Expression("expression231", "AIR_591933_MENU_TBL:AIR_591933_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo29.addExpression(be231);
			com.avaya.sce.runtime.Expression be232 = new com.avaya.sce.runtime.Expression("expression232", "AIR_591939_MENU_TBL:AIR_591939_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo29.addExpression(be232);
			com.avaya.sce.runtime.Expression be233 = new com.avaya.sce.runtime.Expression("expression233", "AIR_591980_MENU_TBL:AIR_591980_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo29.addExpression(be233);
			com.avaya.sce.runtime.Expression be234 = new com.avaya.sce.runtime.Expression("expression234", "AIR_591993_MENU_TBL:AIR_591993_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo29.addExpression(be234);
			com.avaya.sce.runtime.BooleanOperation bo30 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be235 = new com.avaya.sce.runtime.Expression("expression235", "AIR_380_MENU_TBL:AIR_380_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo30.addExpression(be235);
			com.avaya.sce.runtime.Expression be236 = new com.avaya.sce.runtime.Expression("expression236", "AIR_55135_MENU_TBL:AIR_55135_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo30.addExpression(be236);
			com.avaya.sce.runtime.Expression be237 = new com.avaya.sce.runtime.Expression("expression237", "AIR_591933_MENU_TBL:AIR_591933_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo30.addExpression(be237);
			com.avaya.sce.runtime.Expression be238 = new com.avaya.sce.runtime.Expression("expression238", "AIR_591939_MENU_TBL:AIR_591939_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo30.addExpression(be238);
			com.avaya.sce.runtime.Expression be239 = new com.avaya.sce.runtime.Expression("expression239", "AIR_591980_MENU_TBL:AIR_591980_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo30.addExpression(be239);
			com.avaya.sce.runtime.Expression be240 = new com.avaya.sce.runtime.Expression("expression240", "AIR_591993_MENU_TBL:AIR_591993_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo30.addExpression(be240);
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

			if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(1124)).evaluate(mySession, bo29)) {
				actions = new java.util.ArrayList(8);
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L10", "", true).setDebugId(1132));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L10", "", true).setDebugId(1133));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L10", "", true).setDebugId(1134));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591939_MENU_TBL:AIR_591939_MENU_L10", "", true).setDebugId(1135));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591980_MENU_TBL:AIR_591980_MENU_L10", "", true).setDebugId(1136));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591993_MENU_TBL:AIR_591993_MENU_L10", "", true).setDebugId(1137));
				actions.add(new com.avaya.sce.runtime.Next("CF_Menulog-repeate", "L10_*").setDebugId(1138));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(1139)).evaluate(mySession, bo30)) {
				actions = new java.util.ArrayList(14);
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L9", "", true).setDebugId(1316));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L9", "", true).setDebugId(1317));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L9", "", true).setDebugId(1318));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591939_MENU_TBL:AIR_591939_MENU_L9", "", true).setDebugId(1319));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591980_MENU_TBL:AIR_591980_MENU_L9", "", true).setDebugId(1320));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591993_MENU_TBL:AIR_591993_MENU_L9", "", true).setDebugId(1321));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L10", "", true).setDebugId(1322));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L10", "", true).setDebugId(1323));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L10", "", true).setDebugId(1324));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591939_MENU_TBL:AIR_591939_MENU_L10", "", true).setDebugId(1325));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591980_MENU_TBL:AIR_591980_MENU_L10", "", true).setDebugId(1326));
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591993_MENU_TBL:AIR_591993_MENU_L10", "", true).setDebugId(1327));
				actions.add(new com.avaya.sce.runtime.Next("CF_Menulog-back", "L10_#").setDebugId(1159));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			}

		} else {
			actions = new java.util.ArrayList(1);
			actions.add(new com.avaya.sce.runtime.Next("CF_Menulog-end").setDebugId(1331));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;
		}


		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
}
