package flow.subflow.CF_Menulog;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2018年6月6日 下午03時14分07秒
 */
public class Temp extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2018年6月6日 下午03時14分07秒
	 */
	public Temp() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2024年11月22日 下午07時48分53秒
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = null;
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2024年11月22日 下午07時48分53秒
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2024年11月22日 下午07時48分53秒
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		com.avaya.sce.runtime.BooleanOperation bo1 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
		com.avaya.sce.runtime.Expression be1 = new com.avaya.sce.runtime.Expression("expression1", "S_USERDATA:DNIS", com.avaya.sce.runtime.Expression.INT_EQUAL, "80437039380", false);
		bo1.addExpression(be1);
		com.avaya.sce.runtime.Expression be2 = new com.avaya.sce.runtime.Expression("expression2", "S_USERDATA:DNIS", com.avaya.sce.runtime.Expression.INT_EQUAL, "2149380", false);
		bo1.addExpression(be2);
		com.avaya.sce.runtime.Expression be3 = new com.avaya.sce.runtime.Expression("expression3", "S_USERDATA:DNIS", com.avaya.sce.runtime.Expression.INT_EQUAL, "49380", false);
		bo1.addExpression(be3);
		com.avaya.sce.runtime.Expression be4 = new com.avaya.sce.runtime.Expression("expression4", "S_USERDATA:DNIS", com.avaya.sce.runtime.Expression.INT_EQUAL, "2011137", false);
		bo1.addExpression(be4);
		com.avaya.sce.runtime.Expression be5 = new com.avaya.sce.runtime.Expression("expression5", "S_USERDATA:DNIS", com.avaya.sce.runtime.Expression.INT_EQUAL, "21137", false);
		bo1.addExpression(be5);
		com.avaya.sce.runtime.BooleanOperation bo2 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
		com.avaya.sce.runtime.Expression be6 = new com.avaya.sce.runtime.Expression("expression6", "S_USERDATA:DNIS", com.avaya.sce.runtime.Expression.INT_EQUAL, "80437039913", false);
		bo2.addExpression(be6);
		com.avaya.sce.runtime.Expression be7 = new com.avaya.sce.runtime.Expression("expression7", "S_USERDATA:DNIS", com.avaya.sce.runtime.Expression.INT_EQUAL, "437039913", false);
		bo2.addExpression(be7);
		com.avaya.sce.runtime.Expression be8 = new com.avaya.sce.runtime.Expression("expression8", "S_USERDATA:DNIS", com.avaya.sce.runtime.Expression.INT_EQUAL, "2149913", false);
		bo2.addExpression(be8);
		com.avaya.sce.runtime.Expression be9 = new com.avaya.sce.runtime.Expression("expression9", "S_USERDATA:DNIS", com.avaya.sce.runtime.Expression.INT_EQUAL, "49913", false);
		bo2.addExpression(be9);
		com.avaya.sce.runtime.Expression be10 = new com.avaya.sce.runtime.Expression("expression10", "S_USERDATA:DNIS", com.avaya.sce.runtime.Expression.INT_EQUAL, "2011136", false);
		bo2.addExpression(be10);
		com.avaya.sce.runtime.Expression be11 = new com.avaya.sce.runtime.Expression("expression11", "S_USERDATA:DNIS", com.avaya.sce.runtime.Expression.INT_EQUAL, "21136", false);
		bo2.addExpression(be11);
		com.avaya.sce.runtime.BooleanOperation bo3 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
		com.avaya.sce.runtime.Expression be12 = new com.avaya.sce.runtime.Expression("expression12", "S_USERDATA:DNIS", com.avaya.sce.runtime.Expression.INT_EQUAL, "80437039469", false);
		bo3.addExpression(be12);
		com.avaya.sce.runtime.Expression be13 = new com.avaya.sce.runtime.Expression("expression13", "S_USERDATA:DNIS", com.avaya.sce.runtime.Expression.INT_EQUAL, "2149469", false);
		bo3.addExpression(be13);
		com.avaya.sce.runtime.Expression be14 = new com.avaya.sce.runtime.Expression("expression14", "S_USERDATA:DNIS", com.avaya.sce.runtime.Expression.INT_EQUAL, "49469", false);
		bo3.addExpression(be14);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(309)).evaluate(mySession, bo1)) {
			actions = new java.util.ArrayList(1);
			com.avaya.sce.runtime.BooleanOperation bo4 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be15 = new com.avaya.sce.runtime.Expression("expression15", "AIR_380_MENU_TBL:AIR_380_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo4.addExpression(be15);
			com.avaya.sce.runtime.Expression be16 = new com.avaya.sce.runtime.Expression("expression16", "AIR_380_MENU_TBL:AIR_380_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo4.addExpression(be16);
			com.avaya.sce.runtime.BooleanOperation bo5 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be17 = new com.avaya.sce.runtime.Expression("expression17", "AIR_380_MENU_TBL:AIR_380_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo5.addExpression(be17);
			com.avaya.sce.runtime.Expression be18 = new com.avaya.sce.runtime.Expression("expression18", "AIR_380_MENU_TBL:AIR_380_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo5.addExpression(be18);
			com.avaya.sce.runtime.BooleanOperation bo6 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be19 = new com.avaya.sce.runtime.Expression("expression19", "AIR_380_MENU_TBL:AIR_380_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo6.addExpression(be19);
			com.avaya.sce.runtime.Expression be20 = new com.avaya.sce.runtime.Expression("expression20", "AIR_380_MENU_TBL:AIR_380_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo6.addExpression(be20);
			com.avaya.sce.runtime.BooleanOperation bo7 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be21 = new com.avaya.sce.runtime.Expression("expression21", "AIR_380_MENU_TBL:AIR_380_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo7.addExpression(be21);
			com.avaya.sce.runtime.Expression be22 = new com.avaya.sce.runtime.Expression("expression22", "AIR_380_MENU_TBL:AIR_380_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo7.addExpression(be22);
			com.avaya.sce.runtime.BooleanOperation bo8 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be23 = new com.avaya.sce.runtime.Expression("expression23", "AIR_380_MENU_TBL:AIR_380_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo8.addExpression(be23);
			com.avaya.sce.runtime.Expression be24 = new com.avaya.sce.runtime.Expression("expression24", "AIR_380_MENU_TBL:AIR_380_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo8.addExpression(be24);
			com.avaya.sce.runtime.BooleanOperation bo9 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be25 = new com.avaya.sce.runtime.Expression("expression25", "AIR_380_MENU_TBL:AIR_380_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo9.addExpression(be25);
			com.avaya.sce.runtime.Expression be26 = new com.avaya.sce.runtime.Expression("expression26", "AIR_380_MENU_TBL:AIR_380_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo9.addExpression(be26);
			com.avaya.sce.runtime.BooleanOperation bo10 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be27 = new com.avaya.sce.runtime.Expression("expression27", "AIR_380_MENU_TBL:AIR_380_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo10.addExpression(be27);
			com.avaya.sce.runtime.Expression be28 = new com.avaya.sce.runtime.Expression("expression28", "AIR_380_MENU_TBL:AIR_380_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo10.addExpression(be28);
			com.avaya.sce.runtime.BooleanOperation bo11 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be29 = new com.avaya.sce.runtime.Expression("expression29", "AIR_380_MENU_TBL:AIR_380_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo11.addExpression(be29);
			com.avaya.sce.runtime.Expression be30 = new com.avaya.sce.runtime.Expression("expression30", "AIR_380_MENU_TBL:AIR_380_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo11.addExpression(be30);
			com.avaya.sce.runtime.BooleanOperation bo12 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be31 = new com.avaya.sce.runtime.Expression("expression31", "AIR_380_MENU_TBL:AIR_380_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo12.addExpression(be31);
			com.avaya.sce.runtime.Expression be32 = new com.avaya.sce.runtime.Expression("expression32", "AIR_380_MENU_TBL:AIR_380_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo12.addExpression(be32);
			com.avaya.sce.runtime.BooleanOperation bo13 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be33 = new com.avaya.sce.runtime.Expression("expression33", "AIR_380_MENU_TBL:AIR_380_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo13.addExpression(be33);
			com.avaya.sce.runtime.Expression be34 = new com.avaya.sce.runtime.Expression("expression34", "AIR_380_MENU_TBL:AIR_380_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo13.addExpression(be34);
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

			if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(330)).evaluate(mySession, bo4)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (340)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition1", "AIR_380_MENU_TBL:AIR_380_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(340)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L1", "", true).setDebugId(342));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition2", "AIR_380_MENU_TBL:AIR_380_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(341)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L1", "", true).setDebugId(343));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(344)).evaluate(mySession, bo5)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (349)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition3", "AIR_380_MENU_TBL:AIR_380_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(349)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L2", "", true).setDebugId(350));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition4", "AIR_380_MENU_TBL:AIR_380_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(351)).evaluate(mySession)) {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L1", "", true).setDebugId(352));
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L2", "", true).setDebugId(353));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(354)).evaluate(mySession, bo6)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (359)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition5", "AIR_380_MENU_TBL:AIR_380_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(359)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L3", "", true).setDebugId(360));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition6", "AIR_380_MENU_TBL:AIR_380_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(361)).evaluate(mySession)) {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L2", "", true).setDebugId(363));
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L3", "", true).setDebugId(362));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(364)).evaluate(mySession, bo7)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (369)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition7", "AIR_380_MENU_TBL:AIR_380_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(369)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L4", "", true).setDebugId(370));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition8", "AIR_380_MENU_TBL:AIR_380_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(371)).evaluate(mySession)) {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L3", "", true).setDebugId(372));
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L4", "", true).setDebugId(373));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(374)).evaluate(mySession, bo8)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (379)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition9", "AIR_380_MENU_TBL:AIR_380_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(379)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L5", "", true).setDebugId(380));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition10", "AIR_380_MENU_TBL:AIR_380_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(381)).evaluate(mySession)) {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L4", "", true).setDebugId(382));
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L5", "", true).setDebugId(383));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(384)).evaluate(mySession, bo9)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (389)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition11", "AIR_380_MENU_TBL:AIR_380_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(389)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L6", "", true).setDebugId(390));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition12", "AIR_380_MENU_TBL:AIR_380_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(391)).evaluate(mySession)) {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L5", "", true).setDebugId(392));
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L6", "", true).setDebugId(393));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(394)).evaluate(mySession, bo10)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (399)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition13", "AIR_380_MENU_TBL:AIR_380_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(399)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L7", "", true).setDebugId(400));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition14", "AIR_380_MENU_TBL:AIR_380_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(401)).evaluate(mySession)) {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L6", "", true).setDebugId(402));
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L7", "", true).setDebugId(403));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(404)).evaluate(mySession, bo11)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (409)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition15", "AIR_380_MENU_TBL:AIR_380_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(409)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L8", "", true).setDebugId(410));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition16", "AIR_380_MENU_TBL:AIR_380_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(411)).evaluate(mySession)) {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L7", "", true).setDebugId(412));
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L8", "", true).setDebugId(413));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(414)).evaluate(mySession, bo12)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (419)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition17", "AIR_380_MENU_TBL:AIR_380_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(419)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L9", "", true).setDebugId(420));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition18", "AIR_380_MENU_TBL:AIR_380_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(421)).evaluate(mySession)) {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L8", "", true).setDebugId(422));
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L9", "", true).setDebugId(423));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(424)).evaluate(mySession, bo13)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (429)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition19", "AIR_380_MENU_TBL:AIR_380_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(429)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L10", "", true).setDebugId(430));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition20", "AIR_380_MENU_TBL:AIR_380_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(431)).evaluate(mySession)) {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L9", "", true).setDebugId(432));
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_380_MENU_TBL:AIR_380_MENU_L10", "", true).setDebugId(433));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			}

		} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(434)).evaluate(mySession, bo2)) {
			actions = new java.util.ArrayList(1);
			com.avaya.sce.runtime.BooleanOperation bo14 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be35 = new com.avaya.sce.runtime.Expression("expression35", "AIR_55135_MENU_TBL:AIR_55135_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo14.addExpression(be35);
			com.avaya.sce.runtime.Expression be36 = new com.avaya.sce.runtime.Expression("expression36", "AIR_55135_MENU_TBL:AIR_55135_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo14.addExpression(be36);
			com.avaya.sce.runtime.BooleanOperation bo15 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be37 = new com.avaya.sce.runtime.Expression("expression37", "AIR_55135_MENU_TBL:AIR_55135_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo15.addExpression(be37);
			com.avaya.sce.runtime.Expression be38 = new com.avaya.sce.runtime.Expression("expression38", "AIR_55135_MENU_TBL:AIR_55135_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo15.addExpression(be38);
			com.avaya.sce.runtime.BooleanOperation bo16 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be39 = new com.avaya.sce.runtime.Expression("expression39", "AIR_55135_MENU_TBL:AIR_55135_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo16.addExpression(be39);
			com.avaya.sce.runtime.Expression be40 = new com.avaya.sce.runtime.Expression("expression40", "AIR_55135_MENU_TBL:AIR_55135_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo16.addExpression(be40);
			com.avaya.sce.runtime.BooleanOperation bo17 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be41 = new com.avaya.sce.runtime.Expression("expression41", "AIR_55135_MENU_TBL:AIR_55135_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo17.addExpression(be41);
			com.avaya.sce.runtime.Expression be42 = new com.avaya.sce.runtime.Expression("expression42", "AIR_55135_MENU_TBL:AIR_55135_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo17.addExpression(be42);
			com.avaya.sce.runtime.BooleanOperation bo18 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be43 = new com.avaya.sce.runtime.Expression("expression43", "AIR_55135_MENU_TBL:AIR_55135_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo18.addExpression(be43);
			com.avaya.sce.runtime.Expression be44 = new com.avaya.sce.runtime.Expression("expression44", "AIR_55135_MENU_TBL:AIR_55135_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo18.addExpression(be44);
			com.avaya.sce.runtime.BooleanOperation bo19 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be45 = new com.avaya.sce.runtime.Expression("expression45", "AIR_55135_MENU_TBL:AIR_55135_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo19.addExpression(be45);
			com.avaya.sce.runtime.Expression be46 = new com.avaya.sce.runtime.Expression("expression46", "AIR_55135_MENU_TBL:AIR_55135_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo19.addExpression(be46);
			com.avaya.sce.runtime.BooleanOperation bo20 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be47 = new com.avaya.sce.runtime.Expression("expression47", "AIR_55135_MENU_TBL:AIR_55135_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo20.addExpression(be47);
			com.avaya.sce.runtime.Expression be48 = new com.avaya.sce.runtime.Expression("expression48", "AIR_55135_MENU_TBL:AIR_55135_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo20.addExpression(be48);
			com.avaya.sce.runtime.BooleanOperation bo21 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be49 = new com.avaya.sce.runtime.Expression("expression49", "AIR_55135_MENU_TBL:AIR_55135_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo21.addExpression(be49);
			com.avaya.sce.runtime.Expression be50 = new com.avaya.sce.runtime.Expression("expression50", "AIR_55135_MENU_TBL:AIR_55135_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo21.addExpression(be50);
			com.avaya.sce.runtime.BooleanOperation bo22 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be51 = new com.avaya.sce.runtime.Expression("expression51", "AIR_55135_MENU_TBL:AIR_55135_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo22.addExpression(be51);
			com.avaya.sce.runtime.Expression be52 = new com.avaya.sce.runtime.Expression("expression52", "AIR_55135_MENU_TBL:AIR_55135_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo22.addExpression(be52);
			com.avaya.sce.runtime.BooleanOperation bo23 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be53 = new com.avaya.sce.runtime.Expression("expression53", "AIR_55135_MENU_TBL:AIR_55135_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo23.addExpression(be53);
			com.avaya.sce.runtime.Expression be54 = new com.avaya.sce.runtime.Expression("expression54", "AIR_55135_MENU_TBL:AIR_55135_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo23.addExpression(be54);
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

			if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(442)).evaluate(mySession, bo14)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (447)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition21", "AIR_55135_MENU_TBL:AIR_55135_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(447)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L1", "", true).setDebugId(449));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition22", "AIR_55135_MENU_TBL:AIR_55135_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(448)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L1", "", true).setDebugId(450));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(451)).evaluate(mySession, bo15)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (456)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition23", "AIR_55135_MENU_TBL:AIR_55135_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(456)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L2", "", true).setDebugId(457));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition24", "AIR_55135_MENU_TBL:AIR_55135_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(458)).evaluate(mySession)) {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L1", "", true).setDebugId(459));
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L2", "", true).setDebugId(460));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(461)).evaluate(mySession, bo16)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (466)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition25", "AIR_55135_MENU_TBL:AIR_55135_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(466)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L3", "", true).setDebugId(467));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition26", "AIR_55135_MENU_TBL:AIR_55135_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(468)).evaluate(mySession)) {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L2", "", true).setDebugId(469));
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L3", "", true).setDebugId(470));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(471)).evaluate(mySession, bo17)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (476)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition27", "AIR_55135_MENU_TBL:AIR_55135_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(476)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L4", "", true).setDebugId(477));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition28", "AIR_55135_MENU_TBL:AIR_55135_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(478)).evaluate(mySession)) {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L3", "", true).setDebugId(479));
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L4", "", true).setDebugId(480));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(481)).evaluate(mySession, bo18)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (486)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition29", "AIR_55135_MENU_TBL:AIR_55135_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(486)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L5", "", true).setDebugId(487));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition30", "AIR_55135_MENU_TBL:AIR_55135_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(488)).evaluate(mySession)) {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L4", "", true).setDebugId(489));
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L5", "", true).setDebugId(490));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(491)).evaluate(mySession, bo19)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (496)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition31", "AIR_55135_MENU_TBL:AIR_55135_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(496)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L6", "", true).setDebugId(497));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition32", "AIR_55135_MENU_TBL:AIR_55135_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(498)).evaluate(mySession)) {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L5", "", true).setDebugId(499));
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L6", "", true).setDebugId(500));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(501)).evaluate(mySession, bo20)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (506)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition33", "AIR_55135_MENU_TBL:AIR_55135_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(506)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L7", "", true).setDebugId(507));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition34", "AIR_55135_MENU_TBL:AIR_55135_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(508)).evaluate(mySession)) {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L6", "", true).setDebugId(509));
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L7", "", true).setDebugId(510));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(511)).evaluate(mySession, bo21)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (516)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition35", "AIR_55135_MENU_TBL:AIR_55135_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(516)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L8", "", true).setDebugId(517));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition36", "AIR_55135_MENU_TBL:AIR_55135_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(518)).evaluate(mySession)) {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L7", "", true).setDebugId(519));
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L8", "", true).setDebugId(520));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(521)).evaluate(mySession, bo22)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (526)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition37", "AIR_55135_MENU_TBL:AIR_55135_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(526)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L9", "", true).setDebugId(527));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition38", "AIR_55135_MENU_TBL:AIR_55135_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(528)).evaluate(mySession)) {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L8", "", true).setDebugId(529));
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L9", "", true).setDebugId(530));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(531)).evaluate(mySession, bo23)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (536)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition39", "AIR_55135_MENU_TBL:AIR_55135_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(536)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L10", "", true).setDebugId(537));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition40", "AIR_55135_MENU_TBL:AIR_55135_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(538)).evaluate(mySession)) {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L9", "", true).setDebugId(539));
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_55135_MENU_TBL:AIR_55135_MENU_L10", "", true).setDebugId(540));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			}

		} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(541)).evaluate(mySession, bo3)) {
			actions = new java.util.ArrayList(1);
			com.avaya.sce.runtime.BooleanOperation bo24 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be55 = new com.avaya.sce.runtime.Expression("expression55", "AIR_591933_MENU_TBL:AIR_591933_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo24.addExpression(be55);
			com.avaya.sce.runtime.Expression be56 = new com.avaya.sce.runtime.Expression("expression56", "AIR_591933_MENU_TBL:AIR_591933_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo24.addExpression(be56);
			com.avaya.sce.runtime.BooleanOperation bo25 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be57 = new com.avaya.sce.runtime.Expression("expression57", "AIR_591933_MENU_TBL:AIR_591933_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo25.addExpression(be57);
			com.avaya.sce.runtime.Expression be58 = new com.avaya.sce.runtime.Expression("expression58", "AIR_591933_MENU_TBL:AIR_591933_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo25.addExpression(be58);
			com.avaya.sce.runtime.BooleanOperation bo26 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be59 = new com.avaya.sce.runtime.Expression("expression59", "AIR_591933_MENU_TBL:AIR_591933_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo26.addExpression(be59);
			com.avaya.sce.runtime.Expression be60 = new com.avaya.sce.runtime.Expression("expression60", "AIR_591933_MENU_TBL:AIR_591933_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo26.addExpression(be60);
			com.avaya.sce.runtime.BooleanOperation bo27 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be61 = new com.avaya.sce.runtime.Expression("expression61", "AIR_591933_MENU_TBL:AIR_591933_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo27.addExpression(be61);
			com.avaya.sce.runtime.Expression be62 = new com.avaya.sce.runtime.Expression("expression62", "AIR_591933_MENU_TBL:AIR_591933_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo27.addExpression(be62);
			com.avaya.sce.runtime.BooleanOperation bo28 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be63 = new com.avaya.sce.runtime.Expression("expression63", "AIR_591933_MENU_TBL:AIR_591933_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo28.addExpression(be63);
			com.avaya.sce.runtime.Expression be64 = new com.avaya.sce.runtime.Expression("expression64", "AIR_591933_MENU_TBL:AIR_591933_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo28.addExpression(be64);
			com.avaya.sce.runtime.BooleanOperation bo29 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be65 = new com.avaya.sce.runtime.Expression("expression65", "AIR_591933_MENU_TBL:AIR_591933_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo29.addExpression(be65);
			com.avaya.sce.runtime.Expression be66 = new com.avaya.sce.runtime.Expression("expression66", "AIR_591933_MENU_TBL:AIR_591933_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo29.addExpression(be66);
			com.avaya.sce.runtime.BooleanOperation bo30 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be67 = new com.avaya.sce.runtime.Expression("expression67", "AIR_591933_MENU_TBL:AIR_591933_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo30.addExpression(be67);
			com.avaya.sce.runtime.Expression be68 = new com.avaya.sce.runtime.Expression("expression68", "AIR_591933_MENU_TBL:AIR_591933_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo30.addExpression(be68);
			com.avaya.sce.runtime.BooleanOperation bo31 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be69 = new com.avaya.sce.runtime.Expression("expression69", "AIR_591933_MENU_TBL:AIR_591933_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo31.addExpression(be69);
			com.avaya.sce.runtime.Expression be70 = new com.avaya.sce.runtime.Expression("expression70", "AIR_591933_MENU_TBL:AIR_591933_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo31.addExpression(be70);
			com.avaya.sce.runtime.BooleanOperation bo32 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be71 = new com.avaya.sce.runtime.Expression("expression71", "AIR_591933_MENU_TBL:AIR_591933_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo32.addExpression(be71);
			com.avaya.sce.runtime.Expression be72 = new com.avaya.sce.runtime.Expression("expression72", "AIR_591933_MENU_TBL:AIR_591933_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo32.addExpression(be72);
			com.avaya.sce.runtime.BooleanOperation bo33 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
			com.avaya.sce.runtime.Expression be73 = new com.avaya.sce.runtime.Expression("expression73", "AIR_591933_MENU_TBL:AIR_591933_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false);
			bo33.addExpression(be73);
			com.avaya.sce.runtime.Expression be74 = new com.avaya.sce.runtime.Expression("expression74", "AIR_591933_MENU_TBL:AIR_591933_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false);
			bo33.addExpression(be74);
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

			if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(546)).evaluate(mySession, bo24)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (551)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition41", "AIR_591933_MENU_TBL:AIR_591933_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(551)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L1", "", true).setDebugId(553));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition42", "AIR_591933_MENU_TBL:AIR_591933_MENU_L1", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(552)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L1", "", true).setDebugId(554));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(556)).evaluate(mySession, bo25)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (561)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition43", "AIR_591933_MENU_TBL:AIR_591933_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(561)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L2", "", true).setDebugId(562));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition44", "AIR_591933_MENU_TBL:AIR_591933_MENU_L2", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(563)).evaluate(mySession)) {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L1", "", true).setDebugId(564));
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L2", "", true).setDebugId(565));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(566)).evaluate(mySession, bo26)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (571)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition45", "AIR_591933_MENU_TBL:AIR_591933_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(571)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L3", "", true).setDebugId(572));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition46", "AIR_591933_MENU_TBL:AIR_591933_MENU_L3", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(573)).evaluate(mySession)) {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L2", "", true).setDebugId(575));
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L3", "", true).setDebugId(574));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(576)).evaluate(mySession, bo27)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (581)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition47", "AIR_591933_MENU_TBL:AIR_591933_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(581)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L4", "", true).setDebugId(582));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition48", "AIR_591933_MENU_TBL:AIR_591933_MENU_L4", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(583)).evaluate(mySession)) {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L3", "", true).setDebugId(584));
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L4", "", true).setDebugId(585));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(586)).evaluate(mySession, bo28)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (591)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition49", "AIR_591933_MENU_TBL:AIR_591933_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(591)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L5", "", true).setDebugId(592));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition50", "AIR_591933_MENU_TBL:AIR_591933_MENU_L5", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(593)).evaluate(mySession)) {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L4", "", true).setDebugId(594));
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L5", "", true).setDebugId(595));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(596)).evaluate(mySession, bo29)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (601)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition51", "AIR_591933_MENU_TBL:AIR_591933_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(601)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L6", "", true).setDebugId(602));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition52", "AIR_591933_MENU_TBL:AIR_591933_MENU_L6", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(603)).evaluate(mySession)) {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L5", "", true).setDebugId(604));
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L6", "", true).setDebugId(605));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(606)).evaluate(mySession, bo30)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (611)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition53", "AIR_591933_MENU_TBL:AIR_591933_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(611)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L7", "", true).setDebugId(612));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition54", "AIR_591933_MENU_TBL:AIR_591933_MENU_L7", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(613)).evaluate(mySession)) {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L6", "", true).setDebugId(614));
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L7", "", true).setDebugId(615));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(616)).evaluate(mySession, bo31)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (621)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition55", "AIR_591933_MENU_TBL:AIR_591933_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(621)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L8", "", true).setDebugId(622));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition56", "AIR_591933_MENU_TBL:AIR_591933_MENU_L8", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(623)).evaluate(mySession)) {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L7", "", true).setDebugId(624));
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L8", "", true).setDebugId(625));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(626)).evaluate(mySession, bo32)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (631)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition57", "AIR_591933_MENU_TBL:AIR_591933_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(631)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L9", "", true).setDebugId(632));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition58", "AIR_591933_MENU_TBL:AIR_591933_MENU_L9", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(633)).evaluate(mySession)) {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L8", "", true).setDebugId(634));
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L9", "", true).setDebugId(635));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition").setDebugId(636)).evaluate(mySession, bo33)) {
				actions = new java.util.ArrayList(1);
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

				// switch start (641)
				if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition59", "AIR_591933_MENU_TBL:AIR_591933_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "*", false).setDebugId(641)).evaluate(mySession)) {
					actions = new java.util.ArrayList(1);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L10", "", true).setDebugId(642));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition60", "AIR_591933_MENU_TBL:AIR_591933_MENU_L10", com.avaya.sce.runtime.Expression.STRING_EQUAL, "#", false).setDebugId(643)).evaluate(mySession)) {
					actions = new java.util.ArrayList(2);
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L9", "", true).setDebugId(644));
					actions.add(new com.avaya.sce.runtime.varoperations.Assign("AIR_591933_MENU_TBL:AIR_591933_MENU_L10", "", true).setDebugId(645));
					if(evaluateActions(actions, mySession)) {
						return true;
					}
					actions = null;

				}

			}

		}

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
}
