package flow.subflow.CF_Check_FandKDataFor380;

/**
 * This servlet is used to forward the request to the entry point of a
 * project callflow (subflow).
 * Last generated by Orchestration Designer at: 2017年10月13日 下午02時35分05秒
 */
public class API_getCashSubscriberInfoByKey extends com.avaya.sce.runtime.Subflow {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2017年10月13日 下午02時35分05秒
	 */
	public API_getCashSubscriberInfoByKey() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the name of the subflow that is being invoked.  This name is used for
	 * determining the URL mapping for the the entry point of the subflow..
	 *
	 * @return the name of the subflow
	 * Last generated by Orchestration Designer at: 2024年10月9日 下午05時54分44秒
	 */
	protected String getSubflowName() {
		return("API_getCashSubscriberInfoByKey");
	}
	/**
	 * Returns the name of the mapping of sub flow exit points to the URL mappings
	 * of the servlets to return back to in the calling flow.
	 *
	 * @return map of sub flow exit points to servlets in the calling flow.
	 * Last generated by Orchestration Designer at: 2024年10月9日 下午05時54分44秒
	 */
	protected java.util.Map<String,String> getExitPoints() {
		java.util.Map<String, String> exitPoints;
		exitPoints = new java.util.HashMap<String, String>();
		exitPoints.put("API_getCashSubscriberInfoByKey-End", "CF_Check_FandKDataFor380-select_FE_NEWCASH_TBL");
		exitPoints.put("API_getCashSubscriberInfoByKey-next", "CF_Check_FandKDataFor380-Assign_RequestIDandNameandLocale");
		return exitPoints;
	}
}
