package Chinese.grammars;

/**
 * This class is generated automatically.
 * Only exit this class for Dynamic External grammars and override the method String getURL().
 * Last generated by Orchestration Designer at: 2024年11月12日 上午10時58分22秒
 */
public class ICCardPW extends com.avaya.sce.runtime.Grammar {

    //{{START:CLASS:FIELDS
    //}}END:CLASS:FIELDS

    /**
    * Constructor for ICCardPW.
    */
    public ICCardPW() {
		//{{START:CLASS:CONSTRUCTOR
        super();
        setRootLanguage("zh-tw");
        setMode("voice");
        setBuiltin(true);
        setBuiltinMode("grammar");
        setType("number");
        setOptions("");
		//}}END:CLASS:CONSTRUCTOR
    }

}

