package Chinese.grammars;

/**
 * This class is generated automatically.
 * Only exit this class for Dynamic External grammars and override the method String getURL().
 * Last generated by Orchestration Designer at: 2024年11月14日 上午10時44分18秒
 */
public class InputICCard extends com.avaya.sce.runtime.Grammar {

    //{{START:CLASS:FIELDS
    //}}END:CLASS:FIELDS

    /**
    * Constructor for InputICCard.
    */
    public InputICCard() {
		//{{START:CLASS:CONSTRUCTOR
        super();
        setRootLanguage("zh-tw");
        setMode("dtmf");
        setBuiltin(true);
        setBuiltinMode("dtmf");
        setType("number");
        setOptions("");
		//}}END:CLASS:CONSTRUCTOR
    }

}

